// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::kyc::verification::VerificationTag
 */
export enum VerificationTag {
    /** TODO: Model Documentation for Enumeration Literal IDENTITY_VERIFICATION value "IDENTITY_VERIFICATION": $literal.enumerationLiteralDisplay */
    IDENTITY_VERIFICATION = "IDENTITY_VERIFICATION",
    /** TODO: Model Documentation for Enumeration Literal SANCTIONS_DETAILS_VERIFICATION value "SANCTIONS_DETAILS_VERIFICATION": $literal.enumerationLiteralDisplay */
    SANCTIONS_DETAILS_VERIFICATION = "SANCTIONS_DETAILS_VERIFICATION",
    /** TODO: Model Documentation for Enumeration Literal PEP_VERIFICATION value "PEP_VERIFICATION": $literal.enumerationLiteralDisplay */
    PEP_VERIFICATION = "PEP_VERIFICATION",
    /** TODO: Model Documentation for Enumeration Literal SOURCE_OF_FUNDS_VERIFICATION value "SOURCE_OF_FUNDS_VERIFICATION": $literal.enumerationLiteralDisplay */
    SOURCE_OF_FUNDS_VERIFICATION = "SOURCE_OF_FUNDS_VERIFICATION",
    /** TODO: Model Documentation for Enumeration Literal EMPLOYMENT_VERIFICATION value "EMPLOYMENT_VERIFICATION": $literal.enumerationLiteralDisplay */
    EMPLOYMENT_VERIFICATION = "EMPLOYMENT_VERIFICATION",
    /** TODO: Model Documentation for Enumeration Literal ADDRESS_VERIFICATION value "ADDRESS_VERIFICATION": $literal.enumerationLiteralDisplay */
    ADDRESS_VERIFICATION = "ADDRESS_VERIFICATION",
    /** TODO: Model Documentation for Enumeration Literal SANCTIONS_MATCH_VERIFICATION value "SANCTIONS_MATCH_VERIFICATION": $literal.enumerationLiteralDisplay */
    SANCTIONS_MATCH_VERIFICATION = "SANCTIONS_MATCH_VERIFICATION"
}
