// Generated by andromda-angular cartridge (usecase\use-case.ts.vsl) DO NOT EDIT
import {
    OnInit,
    inject,
    Component,
    AfterViewInit,
    signal,
    Signal,
    linkedSignal,
    ViewChild,
    effect,
    OnDestroy,
} from '@angular/core';
import { form } from '@angular/forms/signals';
import { FormField } from '@angular/forms/signals';
import { ActivatedRoute, Router } from '@angular/router';
import { KycRecordControllerImpl } from '@controllers/kyc/kyc-record-controller-impl';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { KycRecordApi } from '@services/bw/co/centralkyc/kyc/kyc-record-api';
import { KycRecordApiStore } from '@store/bw/co/centralkyc/kyc/kyc-record-api.store';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from '@shared/loader/loader';
import { ToastrService } from 'ngx-toastr';
import { MatPaginator } from '@angular/material/paginator';
import { ColumnModel } from '@models/column.model';
import { ActionTemplate } from '@models/action-template';
import { KycRecordDTO } from '@models/bw/co/centralkyc/kyc/kyc-record-dto';
import { KycRecordSearchCriteria } from '@models/bw/co/centralkyc/kyc/kyc-record-search-criteria';
import { SearchObject } from '@models/search-object';
import { TargetEntity } from '@models/bw/co/centralkyc/target-entity';
import { KycComplianceStatus } from '@models/bw/co/centralkyc/kyc/kyc-compliance-status';
import { Page } from '@models/page.model';
import { RouterModule } from '@angular/router';

export class KycRecordSearchForm {
    name: string | any = null;
    registration: string | any = null;
    target: TargetEntity | any = null;
    targetId: string | any = null;
    statuses: Array<KycComplianceStatus> | any = [];
}

@Component({
  selector: 'app-kyc-records',
  templateUrl: './kyc-records.html',
  styleUrls: ['./kyc-records.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
    RouterModule,
  ],
})
export class KycRecordsComponent implements OnInit, AfterViewInit, OnDestroy {

    protected route: ActivatedRoute = inject(ActivatedRoute);
    protected router: Router = inject(Router);
    protected useCaseScope: UseCaseScope = inject(UseCaseScope);
    readonly kycRecordApi = inject(KycRecordApi);
    readonly kycRecordApiStore = inject(KycRecordApiStore);
    readonly kycRecordController = inject(KycRecordControllerImpl);
    toaster: ToastrService = inject(ToastrService);

    kycRecordSearchForm: KycRecordSearchForm = new KycRecordSearchForm();
    kycRecordSearchSignal = signal(this.kycRecordSearchForm);
    kycRecordSearchSignalForm = form(this.kycRecordSearchSignal, (path) => {});

    loaderMessage = linkedSignal(() => this.kycRecordApiStore.loaderMessage());
    messages = linkedSignal(() => this.kycRecordApiStore.messages());
    success = linkedSignal(() => this.kycRecordApiStore.success());
    loading = linkedSignal(() => this.kycRecordApiStore.loading());
    error = linkedSignal(() => this.kycRecordApiStore.error());

    @ViewChild('kycRecordsTable') kycRecordsTable!: TableComponent<KycRecordDTO>;
    kycRecordsTableSignal = linkedSignal(() => this.kycRecordApiStore.dataPage());
    kycRecordsTablePaged: boolean = true;

    kycRecordsTableColumns: ColumnModel[] = [
        new ColumnModel('name', 'name', false),
        new ColumnModel('identityNo', 'identity.no', false),
        new ColumnModel('target', 'target', false),
        new ColumnModel('kycStatus', 'kyc.status', false),
        new ColumnModel('expiryDate', 'expiry.date', false),
    ];

    kycRecordsTableColumnsActions: ActionTemplate[] = [
        {
            id: 'kyc-record-details',
            label: 'details',
            icon: 'remove_red_eye',
            tooltip: 'details',
        },
    ];

    showKycRecordsActions = true;

    TargetEntityT: any = TargetEntity;
    TargetEntityOptions = Object.keys(this.TargetEntityT);
    KycComplianceStatusT: any = KycComplianceStatus;
    KycComplianceStatusOptions = Object.keys(this.KycComplianceStatusT);

    constructor() {
        effect(() => {
            let messages = this.messages();

            if (this.success() && !this.loading()) {
                this.toaster.success(messages[0]);
            }

            if (this.error() && !this.loading()) {
                this.toaster.error(messages[0]);
            }
        });
    }

    ngOnInit() {
    }

    ngAfterViewInit() {
        this.kycRecordsTable?.tablePaginator?.page?.subscribe({
            next: (paginator: MatPaginator) => {
                this.doSearch(paginator.pageIndex, paginator.pageSize);
            },
        });
    }

    ngOnDestroy() {
    }

    kycRecordSearchFormReset() {
        this.kycRecordSearchSignal.set(new KycRecordSearchForm());
    }

    kycRecordSearch(): void {
        this.doSearch();
    }

    private doSearch(pageNumber: number = 0, pageSize: number = 10): void {
        let value = this.kycRecordSearchSignal();

        let searchCriteria = new KycRecordSearchCriteria();
        searchCriteria.name = value.name;
        searchCriteria.registration = value.registration;
        searchCriteria.target = value.target;
        searchCriteria.targetIds = [value.targetId];
        searchCriteria.statuses = value.statuses;

        let criteria = new SearchObject<KycRecordSearchCriteria>();
        criteria.pageNumber = pageNumber;
        criteria.pageSize = pageSize;
        criteria.criteria = searchCriteria;

        this.kycRecordApiStore.pagedSearch({
            criteria: criteria
        });
    }

    kycRecordsTableActionClicked(event: any): void {
        switch (event.action) {
            case 'kyc-record-details':
                this.router.navigate(['/kyc/details'], {
                    queryParams: { id: event.row.id }
                });
                break;
        }
    }

}
