package bw.co.knowvera.config;

import java.util.List;

import org.springframework.http.HttpMethod;

/**
 * Endpoints reachable without a token.
 * <p>
 * Generated by {@code keycloak/generate_authz.py} from PUBLIC_ENDPOINTS and PUBLIC_INFRASTRUCTURE;
 * do not edit by hand.
 */
public final class PublicEndpoints {

    public record Endpoint(HttpMethod method, String pattern) {
    }

    /** Framework endpoints (all HTTP methods). */
    public static final List<String> INFRASTRUCTURE = List.of(
            "/swagger-ui/**",
            "/v3/**",
            "/actuator/health",
            "/actuator/health/**",
            "/actuator/info");

    /** API endpoints. */
    public static final List<Endpoint> ENDPOINTS = List.of(
            new Endpoint(HttpMethod.GET, "/analytics/count"),
            new Endpoint(HttpMethod.GET, "/analytics/count/by-organisation/*"),
            new Endpoint(HttpMethod.GET, "/client-requests/*/confirm"),
            new Endpoint(HttpMethod.GET, "/client-requests/confirm-token/*"),
            new Endpoint(HttpMethod.GET, "/individuals/request/*"),
            new Endpoint(HttpMethod.GET, "/organisations/request/*"));

    private PublicEndpoints() {
    }
}
