// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.document.type;

import java.util.Collection;
import java.util.Optional;

import org.apache.commons.collections4.CollectionUtils;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.centralkyc.AuditTracker;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@Tag(name = "Document Types", description = "Operations related to document types.")
public class DocumentTypeApiImpl implements DocumentTypeApi {

    private final DocumentTypeService documentTypeService;

    public DocumentTypeApiImpl(DocumentTypeService documentTypeService) {
        this.documentTypeService = documentTypeService;
    }

    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<DocumentTypeDTO> findById(String id) {

        try {

            return ResponseEntity.ok(documentTypeService.findById(id));

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    @Operation(summary = "Get All Document Types", description = "Get all document types")
    public ResponseEntity<Collection<DocumentTypeDTO>> getAll() {

        try {

            Collection<DocumentTypeDTO> results = documentTypeService.getAll();

            if (CollectionUtils.isEmpty(results)) {

                return ResponseEntity.noContent().build();
            }   

            return ResponseEntity.ok(results);

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    @Operation(summary = "Get All Document Types Paged", description = "Get all document types with pagination")
    public ResponseEntity<Page<DocumentTypeDTO>> getAllPaged(Integer pageNumber,
            Integer pageSize) {

        try {
            Page<DocumentTypeDTO> results = documentTypeService.getAll(pageNumber, pageSize);

            if (CollectionUtils.isEmpty(results.getContent())) {

                return ResponseEntity.noContent().build();
            }

            return ResponseEntity.ok(results);
        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    @Operation(summary = "Search Document Types Paged", description = "Search document types with pagination")
    public ResponseEntity<Page<DocumentTypeDTO>> pagedSearch(String criteria,
            Integer pageNumber,
            Integer pageSize) {

        try {

            Page<DocumentTypeDTO> results = documentTypeService.search(criteria, pageNumber, pageSize);

            if (CollectionUtils.isEmpty(results.getContent())) {

                return ResponseEntity.noContent().build();
            }

            return ResponseEntity.ok(results);

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    @Operation(summary = "Remove Document Type", description = "Remove the document type with the given id")
    public ResponseEntity<Boolean> remove(String id) {

        try {

            return ResponseEntity.ok(documentTypeService.remove(id));

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    @Operation(summary = "Save Document Type", description = "Save the document type. If the id is not provided, a new document type will be created.")
    public ResponseEntity<DocumentTypeDTO> save(DocumentTypeDTO documentType) {

        try {

            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(documentType, authentication);

            if (documentType.getExpectedFields() != null) {

                documentType.getExpectedFields().forEach(field -> {
                    AuditTracker.auditTrail(field, authentication);
                });
            }

            if (documentType.getVerificationDataConfigs() != null) {

                documentType.getVerificationDataConfigs().forEach(config -> {
                    AuditTracker.auditTrail(config, authentication);
                });
            }

            return ResponseEntity.status(HttpStatus.CREATED).body(documentTypeService.save(documentType));

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    @Operation(summary = "Search Document Types", description = "Search document types by criteria")
    public ResponseEntity<Collection<DocumentTypeDTO>> search(String criteria) {

        try {
            Collection<DocumentTypeDTO> results = documentTypeService.search(criteria);

            if (CollectionUtils.isEmpty(results)) {

                return ResponseEntity.noContent().build();
            }

            return ResponseEntity.ok(results);

        } catch (Exception e) {

            throw e;
        }

    }
}
