server {
    listen 80 default_server; # Added default_server
    server_name _; # Specific domain

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
