// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.document;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;
import org.jspecify.annotations.Nullable;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.core.io.InputStreamResource;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.QueueObject;
import bw.co.centralkyc.SearchObject;
import bw.co.centralkyc.TargetEntity;
import bw.co.centralkyc.document.processor.DocumentProcessorService;
import bw.co.centralkyc.minio.MinioService;
import bw.co.centralkyc.properties.RabbitProperties;
import jakarta.validation.Valid;

@RestController
public class DocumentApiImpl implements DocumentApi {

    private final MinioService minioService;
    private final DocumentService documentService;
    private final DocumentProcessorService documentProcessor;
    private final RabbitTemplate rabbitTemplate;
    private final RabbitProperties rabbitProperties;

    public DocumentApiImpl(DocumentService documentService, RabbitTemplate rabbitTemplate, MinioService minioService,
            DocumentProcessorService documentProcessor, RabbitProperties rabbitProperties) {

        this.documentService = documentService;
        this.minioService = minioService;
        this.documentProcessor = documentProcessor;
        this.rabbitTemplate = rabbitTemplate;
        this.rabbitProperties = rabbitProperties;
    }

    @Override
    public ResponseEntity<Collection<DocumentListDTO>> findByDocumentType(String documentTypeId) {

        try {

            return ResponseEntity.ok(documentService.findByDocumentType(documentTypeId));

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    public ResponseEntity<DocumentDTO> findById(String id) {

        try {

            return ResponseEntity.ok(documentService.findById(id));

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<DocumentListDTO>> findByTarget(
            bw.co.centralkyc.TargetEntity target, String targetId) {

        try {

            return ResponseEntity.ok(documentService.findByTarget(target, targetId));
        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<DocumentListDTO>> getAll() {
        return ResponseEntity.ok(documentService.getAll());

    }

    @Override
    public ResponseEntity<Page<DocumentListDTO>> getAllPaged(Integer pageNumber, Integer pageSize) {

        try {

            return ResponseEntity.ok(documentService.getAll(pageNumber, pageSize));

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    public ResponseEntity<Boolean> remove(String id) {

        try {

            DocumentDTO document = documentService.findById(id);
            if (document == null) {
                throw new IllegalArgumentException("Document not found with id: " + id);
            }

            // minioService.deleteFile(document.getUrl());

            return ResponseEntity.ok(documentService.remove(id));

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    public ResponseEntity<DocumentDTO> save(DocumentDTO document) {

        try {

            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(document, authentication);
            return ResponseEntity.ok(documentService.save(document));

        } catch (Exception e) {

            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<DocumentListDTO>> search(SearchObject<DocumentSearchCriteria> criteria) {

        try {

            return ResponseEntity.ok(documentService.search(criteria.getCriteria(), Set.copyOf(criteria.getSortings())));
        } catch (Exception e) {

            throw e;
        }

    }

    private String constructFilePath(TargetEntity target, String targetId, String purpose, String fileName) {
        StringBuilder filePath = new StringBuilder();
        filePath.append(target).append("/").append(targetId);

        if (StringUtils.isNotBlank(purpose)) {
            filePath.append("/").append(purpose);
        }

        filePath.append("/").append(fileName);

        return filePath.toString();
    }

    private String uploadToMinio(MultipartFile file, String fileName) throws Exception {
        // Upload the file to MinIO
        try (InputStream inputStream = file.getInputStream()) {

            String url = minioService.uploadFile(fileName, inputStream, file.getSize(), file.getContentType());
            return url;

        } catch (IOException e) {
            e.printStackTrace();
            throw new DocumentServiceException("Error uploading file: " + file.getOriginalFilename());
        }
    }

    @Override
    public ResponseEntity<DocumentDTO> upload(TargetEntity target, String targetId,
            String documentTypeId, String purpose, MultipartFile file) {

        try {

            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            Jwt jwt = (Jwt) authentication.getPrincipal();

            String username = jwt.getClaimAsString("preferred_username");

            DocumentDTO document = new DocumentDTO();
            document.setCreatedAt(LocalDateTime.now());
            document.setCreatedBy(username);
            document.setTarget(target);
            document.setTargetId(targetId);
            document.setFileName(file.getOriginalFilename());

            Map<String, Object> metadata = new HashMap<>();
            metadata.put("fileSize", file.getSize());
            metadata.put("fileType", file.getContentType());
            metadata.put("contentType", file.getContentType());

            document.setMetadata(metadata);

            String filePath = constructFilePath(target, targetId, purpose, file.getOriginalFilename());
            try {
                document.setUrl(uploadToMinio(file, filePath));
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
                throw new DocumentServiceException("Error uploading file: " + file.getOriginalFilename());
            }

            document.setDocumentTypeId(documentTypeId);

            document = documentService.save(document);
            QueueObject queueObject = new QueueObject(
                    document.getId(),
                    target,
                    targetId);

            rabbitTemplate.convertAndSend(rabbitProperties.getTextExtractionQueueExchange(),
                    rabbitProperties.getTextExtractionQueueRoutingKey(), queueObject);

            return ResponseEntity.ok(document);

        } catch (Exception e) {

            throw e;
        }

    }

    private InputStreamResource downloadFromMinio(String url) throws Exception {

        // Download the file from MinIO
        InputStream inputStream = minioService.downloadFile(url);
        // Process the input stream as needed
        InputStreamResource resource = new InputStreamResource(inputStream);
        return resource;
    }

    @Override
    public ResponseEntity<InputStreamResource> downloadFile(String id) {
        try {

            DocumentDTO document = documentService.findById(id);
            InputStreamResource data = downloadFromMinio(document.getUrl());
            ResponseEntity<InputStreamResource> response = ResponseEntity.status(HttpStatus.OK)
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + document.getUrl() + "\"")
                    .contentType(MediaType.APPLICATION_OCTET_STREAM)
                    .body(data);

            return response;

        } catch (Exception e) {
            e.printStackTrace();
            throw new DocumentServiceException("Error downloading file: " + e.getMessage());
        }
    }

    public ResponseEntity<InputStreamResource> downloadFileByUrl(@RequestParam String objectName) throws Exception {

        InputStreamResource data = downloadFromMinio(objectName);
        ResponseEntity<InputStreamResource> response = ResponseEntity.status(HttpStatus.OK)
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + objectName + "\"")
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .body(data);

        return response;

    }

    @Override
    public ResponseEntity<DocumentDTO> updateDocument(String id, MultipartFile file) throws Exception {

        DocumentDTO document = documentService.findById(id);
        if (document == null) {
            throw new IllegalArgumentException("Document not found with id: " + id);
        }

        String fileName = file.getOriginalFilename();
        if (fileName == null || fileName.isBlank()) {
            throw new IllegalArgumentException("Uploaded file must have a name");
        }

        String filePath;
        if (StringUtils.isNotBlank(document.getUrl())) {
            int lastSlash = document.getUrl().lastIndexOf("/");
            String basePath = lastSlash > 0 ? document.getUrl().substring(0, lastSlash) : "";
            filePath = basePath + "/" + fileName;
        } else {
            filePath = constructFilePath(document.getTarget(), document.getTargetId(), id, fileName);
        }

        if (filePath == null || filePath.isBlank()) {
            throw new IllegalArgumentException("Computed filePath is null or empty for document: " + id);
        }

        // Upload to MinIO
        String url = uploadToMinio(file, filePath);
        document.setUrl(url);
        document.setFileName(fileName);

        Map<String, Object> metadata = new HashMap<>();
        metadata.put("fileSize", file.getSize());
        metadata.put("fileType", file.getContentType());
        metadata.put("contentType", file.getContentType());
        document.setMetadata(metadata);

        document = documentService.save(document);

        // Send to queue
        rabbitTemplate.convertAndSend(
                rabbitProperties.getTextExtractionQueueExchange(),
                rabbitProperties.getTextExtractionQueueRoutingKey(),
                new QueueObject(document.getId(), document.getTarget(), document.getTargetId()));

        return ResponseEntity.ok(document);

    }

    @Override
    public @Nullable ResponseEntity<Page<DocumentListDTO>> searchPaged(
            @Valid SearchObject<DocumentSearchCriteria> criteria) throws Exception {
        
        try {
            Page<DocumentListDTO> results = documentService.search(criteria);
            return ResponseEntity.ok(results);
        } catch (Exception e) {
            throw e;
        }
        
    }

    @Override
    public ResponseEntity<Page<DocumentListDTO>> findMyDocumentsPaged(TargetEntity target, @Nullable Integer pageNumber,
            @Nullable Integer pageSize) throws Exception {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'findByDocumentsPaged'");
    }

    @Override
    public @Nullable ResponseEntity<Collection<DocumentListDTO>> findMyDocuments(TargetEntity target) throws Exception {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'findMyDocuments'");
    }

    @Override
    public ResponseEntity<DocumentDTO> analyseDocument(String id) throws Exception {

        try {
            DocumentDTO document = documentService.findById(id);
            if (document == null) {
                throw new IllegalArgumentException("Document not found with id: " + id);
            }

            
            QueueObject queueObject = new QueueObject(
                    document.getId(),
                    document.getTarget(),
                    document.getTargetId());

            rabbitTemplate.convertAndSend(rabbitProperties.getTextExtractionQueueExchange(),
                    rabbitProperties.getTextExtractionQueueRoutingKey(), queueObject);

            return ResponseEntity.ok(documentService.findById(id));
        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<DocumentDTO> updateFileContent(String id, String content) throws Exception {
        
        try {

//            DocumentDTO doc = documentService.findById(id);

            // QueueObject queueObject = new QueueObject(
            //         doc.getId(),
            //         doc.getTarget(),
            //         doc.getTargetId());

            // rabbitTemplate.convertAndSend(rabbitProperties.getTextCleanupQueueExchange(),
            //         rabbitProperties.getTextCleanupQueueRoutingKey(), queueObject);

            return ResponseEntity.ok(documentService.updateFileContent(id, content));
        } catch (Exception e) {
            throw e;
        }

    }
}