// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.sequence;

import org.springframework.stereotype.Repository;

/**
 * @see SequencePart
 */
@Repository("sequencePartDao")
public class SequencePartDaoImpl
    extends SequencePartDaoBase
{
    
    public SequencePartDaoImpl(
        SequenceGeneratorRepository sequenceGeneratorRepository,
        SequencePartRepository sequencePartRepository
    ) {

        super(
            sequenceGeneratorRepository,
            sequencePartRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toSequencePartDTO(
        SequencePart source,
        SequencePartDTO target)
    {
        // TODO verify behavior of toSequencePartDTO
        super.toSequencePartDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SequencePartDTO toSequencePartDTO(final SequencePart entity)
    {
        // TODO verify behavior of toSequencePartDTO
        return super.toSequencePartDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private SequencePart loadSequencePartFromSequencePartDTO(SequencePartDTO sequencePartDTO)
    {
        // TODO implement loadSequencePartFromSequencePartDTO
        throw new UnsupportedOperationException("bw.co.centralkyc.sequence.loadSequencePartFromSequencePartDTO(SequencePartDTO) not yet implemented.");

        /* A typical implementation looks like this:
        if (sequencePartDTO.getId() == null)
        {
            return  SequencePart.Factory.newInstance();
        }
        else
        {
            return this.sequencePartRepository.findById(sequencePartDTO.getId())
                .orElseThrow(() -> new SequencePartServiceException("Entity not found for id: " + sequencePartDTO.getId()));
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public SequencePart sequencePartDTOToEntity(SequencePartDTO sequencePartDTO)
    {
        // TODO verify behavior of sequencePartDTOToEntity
        SequencePart entity = this.loadSequencePartFromSequencePartDTO(sequencePartDTO);
        this.sequencePartDTOToEntity(sequencePartDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void sequencePartDTOToEntity(
        SequencePartDTO source,
        SequencePart target,
        boolean copyIfNull)
    {
        // TODO verify behavior of sequencePartDTOToEntity
        super.sequencePartDTOToEntity(source, target, copyIfNull);
    }
}