// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.individual;

import bw.co.centralkyc.document.DocumentMapper;
import bw.co.centralkyc.individual.employment.EmploymentRecordMapper;
import bw.co.centralkyc.organisation.OrganisationMapper;
import bw.co.centralkyc.organisation.branch.BranchMapper;
import bw.co.centralkyc.utils.MappingUtils;

import java.util.Collection;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.beans.factory.annotation.Autowired;

@Mapper(
    componentModel = "spring", uses = {
        DocumentMapper.class,
        EmploymentRecordMapper.class,
        BranchMapper.class,
        OrganisationMapper.class,
        MappingUtils.class
})
public abstract class IndividualMapper {
    
    /**
     * Converts this entity to an object of type {@link IndividualDTO}.
     * @param entity
     * @return IndividualDTO
     */
    @Mapping(target = "organisation", ignore = true)
    @Mapping(source = "branch", target = "branch")
    @Mapping(source = "branch.organisation.name", target = "branch.organisation")
    @Mapping(source = "branch.organisation.id", target = "branch.organisationId")
    @Mapping(target = "employmentRecords", ignore = true)
    public abstract IndividualDTO toIndividualDTO(Individual entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link IndividualDTO}.
     * @param entities
     * @return Collection<IndividualDTO>     */
    public abstract List<IndividualDTO> toIndividualDTOCollection(Collection<Individual> entities);

    /**
     * Converts an instance of type {@link IndividualDTO} to this DAO's entity.
     * @param individualDTO
     * @return Individual
     */
    @InheritInverseConfiguration
    @Mapping(target = "branch", ignore = true)
    @Mapping(target = "employmentRecords", ignore = true)
    @Mapping(target = "documents", ignore = true)
    public abstract Individual individualDTOToEntity(IndividualDTO individualDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateIndividualFromIndividualDTO(IndividualDTO individualDTO, @MappingTarget Individual entity);

    /**
     * Converts this entity to an object of type {@link IndividualListDTO}.
     * @param entity
     * @return IndividualListDTO
     */
    @Mapping(target = "name", expression = "java(getIndividualName(entity))")
    public abstract IndividualListDTO toIndividualListDTO(Individual entity);

    protected String getIndividualName(Individual entity) {

        StringBuilder nameBuilder = new StringBuilder();
        if (StringUtils.isNotBlank(entity.getFirstName())) {
            nameBuilder.append(entity.getFirstName());
        }

        if(StringUtils.isNotBlank(entity.getMiddleName())) {
            if (nameBuilder.length() > 0) {
                nameBuilder.append(" ");
            }
            nameBuilder.append(entity.getMiddleName());
        }

        if (StringUtils.isNotBlank(entity.getSurname())) {
            if (nameBuilder.length() > 0) {
                nameBuilder.append(" ");
            }
            nameBuilder.append(entity.getSurname());
        }

        return nameBuilder.toString();
    }

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link IndividualListDTO}.
     * @param entities
     * @return Collection<IndividualListDTO>     */
    public abstract List<IndividualListDTO> toIndividualListDTOCollection(Collection<Individual> entities);

    /**
     * Converts an instance of type {@link IndividualListDTO} to this DAO's entity.
     * @param individualListDTO
     * @return Individual
     */
    @InheritInverseConfiguration
    public abstract Individual individualListDTOToEntity(IndividualListDTO individualListDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateIndividualFromIndividualListDTO(IndividualListDTO individualListDTO, @MappingTarget Individual entity);

}