// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, effect, inject, Input, linkedSignal, Signal } from '@angular/core';
import { EditOrganisationComponent } from '@views/organisation/edit/edit-organisation';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { Loader } from "@shared/loader/loader";
import { applyEach, form, FormField, required } from '@angular/forms/signals';
import { RouterModule } from "@angular/router";
import { OrganisationDTO } from '@app/models/bw/co/centralkyc/organisation/organisation-dto';

@Component({
  selector: 'app-edit-organisation',
  templateUrl: './edit-organisation.html',
  styleUrls: ['./edit-organisation.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    Loader,
    FormField,
    RouterModule
],
})
export class EditOrganisationImplComponent extends EditOrganisationComponent {
  @Input() id: string = '';
  override error = linkedSignal(() => this.organisationApiStore.error());
  override messages = linkedSignal(() => this.organisationApiStore.messages());
  override success = linkedSignal(() => this.organisationApiStore.success());
  override loading = linkedSignal(() => this.organisationApiStore.loading());
  override loaderMessage = linkedSignal(() => this.organisationApiStore.loaderMessage());

  override editOrganisationSignalForm = form(this.editOrganisationSignal, (path) => {
      required(path.isClient, { message: 'is.client.required' })
      required(path.status, { message: 'status.required' })
      required(path.kycStatus, { message: 'kyc.status.required' })
      required(path.registrationNo, { message: 'registration.no.required' })
      required(path.code, { message: 'code.required' })
      required(path.name, { message: 'name.required' })
      required(path.countryOfRegistration, { message: 'country.of.registration.required' })
      required(path.description, { message: 'description.required' })
      required(path.postalAddress, { message: 'postal.address.required' })
      required(path.physicalAddress, { message: 'physical.address.required' })
      required(path.domains, { message: 'domains.required' });
      applyEach(path.phoneNumbers, (phonePath) => {
        required(phonePath.type, { message: 'phone.type.required' });
        required(phonePath.phoneNumber, { message: 'phone.number.required' });
      });
    });

  countries: string[] = [
    'Unknown', 'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
    'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
    'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica',
    'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
    'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
    'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
    'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel',
    'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea, North', 'Korea, South', 'Kosovo',
    'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
    'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
    'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
    'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman',
    'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
    'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe',
    'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
    'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
    'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
    'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City',
    'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
  ];

  constructor() {
    super();

    effect(() => {
      let organisation = this.organisationApiStore.data() || new OrganisationDTO();

      console.log(organisation)
      this.editOrganisationSignal.update((value) => ({
        ...organisation
      }))
    });
  }

  override ngOnInit() {
    this.organisationApiStore.reset();

    this.route.queryParams.subscribe(params => {
      const id = params['id'];
      if (id) {
        this.id = id;
        this.organisationApiStore.findById({id: id});
      }
    });

  }

  doNgOnDestroy(): void { }

  override beforeEditOrganisationSave(form: any): void {

    this.editOrganisationSignalForm().invalid()

    let value = this.editOrganisationSignal();
    let org = {
      code: value.code,
      description: value.description,
      domains: value.domains,
      phoneNumbers: value.phoneNumbers,
      status: value.status,
      postalAddress: value.postalAddress,
      physicalAddress: value.physicalAddress,
      contactEmailAddress: value.contactEmailAddress,
      name: value.name,
      registrationNo: value.registrationNo,
      createdAt: value.createdAt,
      createdBy: value.createdBy,
      modifiedAt: value.modifiedAt,
      modifiedBy: value.modifiedBy,
      isClient: value.isClient,
      kycStatus: value.kycStatus,
      countryOfRegistration: value.countryOfRegistration,
      id: value.id
    } as OrganisationDTO;

    this.organisationApiStore.save({organisation: org});
  }
}
