// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { OrganisationController } from '@controllers/organisation/organisation-controller';

@Injectable()
export class OrganisationControllerImpl extends OrganisationController {

    constructor() {
        super();
    }

}
