// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.kyvera.subscription;

import bw.co.kyvera.invoice.KycInvoiceMapper;
import bw.co.kyvera.organisation.OrganisationMapper;
import bw.co.kyvera.utils.MappingUtils;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.beans.factory.annotation.Autowired;

@Mapper(
    componentModel = "spring",
    uses = {
        MappingUtils.class,
        KycInvoiceMapper.class,
        OrganisationMapper.class
    }
)
public abstract class KycSubscriptionMapper {

    @Autowired
    protected KycInvoiceMapper kycInvoiceMapper;
    
    @Autowired
    protected OrganisationMapper organisationMapper;
    
    
    /**
     * Converts this entity to an object of type {@link KycSubscriptionDTO}.
     * @param entity
     * @return KycSubscriptionDTO
     */
    // WARNING! No conversion for target.startDate (can't convert source.getStartDate():java.util.Date to java.util.Date)
    // WARNING! No conversion for target.endDate (can't convert source.getEndDate():java.util.Date to java.util.Date)
    @Mapping(target = "organisationId", source = "organisation.id")
    @Mapping(target = "organisationName", source = "organisation.name")
    @Mapping(target = "organisationCode", source = "organisation.code")
    @Mapping(target = "organisationRegistrationNo", source = "organisation.registrationNo")
    @Mapping(target = "invoices", source = "kycInvoices")
    public abstract KycSubscriptionDTO toKycSubscriptionDTO(KycSubscription entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link KycSubscriptionDTO}.
     * @param entities
     * @return Collection<KycSubscriptionDTO>     */
    public abstract List<KycSubscriptionDTO> toKycSubscriptionDTOCollection(Collection<KycSubscription> entities);

    /**
     * Converts an instance of type {@link KycSubscriptionDTO} to this DAO's entity.
     * @param kycSubscriptionDTO
     * @return KycSubscription
     */
    // No conversion for target.startDate (can't convert source.getStartDate():java.util.Date to java.util.Date)
    // No conversion for target.endDate (can't convert source.getEndDate():java.util.Date to java.util.Date)
    @InheritInverseConfiguration
    @Mapping(target = "kycInvoices", ignore = true)
    public abstract KycSubscription kycSubscriptionDTOToEntity(KycSubscriptionDTO kycSubscriptionDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    // No conversion for target.startDate (can't convert source.getStartDate():java.util.Date to java.util.Date
    // No conversion for target.endDate (can't convert source.getEndDate():java.util.Date to java.util.Date
    @InheritInverseConfiguration
    public abstract void updateKycSubscriptionFromKycSubscriptionDTO(KycSubscriptionDTO kycSubscriptionDTO, @MappingTarget KycSubscription entity);

}