// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.knowvera.contact;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

import bw.co.knowvera.logging.Audit;
import bw.co.knowvera.contact.ContactApi;
import bw.co.knowvera.contact.ContactDTO;
import bw.co.knowvera.contact.ContactService;
import bw.co.knowvera.contact.ContactServiceException;
import bw.co.knowvera.contact.ContactType;

@RestController
@Tag(name = "Client Contact Management", description = "Clients may contact us.")
public class ContactApiImpl implements ContactApi {

    private static final Logger logger = LoggerFactory.getLogger(ContactApiImpl.class);
        protected final ContactService contactService;
    
    public ContactApiImpl(
        ContactService contactService    ) {
        
        this.contactService = contactService;
    }

    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    @Audit(entity = "CONTACT", eventLabel="#id", logData = false)
    public ResponseEntity<ContactDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new ContactServiceException(e.getCause().getMessage()) : e;
        } 
    }

    @Override
    @Operation(summary = "Find Contacts by Type", description = "Get the contacts of the given type")
    @Audit(entity = "CONTACT", logData = false)
    public ResponseEntity<List<ContactDTO>> findByType(ContactType type) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new ContactServiceException(e.getCause().getMessage()) : e;
        } 
    }

    @Override
    @Operation(summary = "Find Contacts by Type with Pagination", description = "Get the contacts of the given type with pagination")
    @Audit(entity = "CONTACT", logData = false)
    public ResponseEntity<Page<ContactDTO>> findByTypePaged(ContactType type, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new ContactServiceException(e.getCause().getMessage()) : e;
        } 
    }

    @Override
    @Operation(summary = "Get All Contacts", description = "Get all contacts")
    @Audit(entity = "CONTACT", logData = false)
    public ResponseEntity<List<ContactDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new ContactServiceException(e.getCause().getMessage()) : e;
        } 
    }

    @Override
    @Operation(summary = "Get All Contacts Paged", description = "Get all contacts with pagination")
    @Audit(entity = "CONTACT", logData = false)
    public ResponseEntity<Page<ContactDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new ContactServiceException(e.getCause().getMessage()) : e;
        } 
    }

    @Override
    @Operation(summary = "Remove Contact", description = "Remove the contact with the given id")
    @Audit(entity = "CONTACT", eventLabel="#id", logData = false)
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new ContactServiceException(e.getCause().getMessage()) : e;
        } 
    }

    @Override
    @Operation(summary = "Save Contact", description = "Save the contact. If the id is not provided, a new contact will be created.")
    @Audit(entity = "CONTACT", eventLabel="#document.id", logData = true)
    public ResponseEntity<ContactDTO> save(ContactDTO document) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new ContactServiceException(e.getCause().getMessage()) : e;
        } 
    }

    @Override
    @Operation(summary = "Search Contacts", description = "Search contacts by criteria")
    @Audit(entity = "CONTACT", logData = false)
    public ResponseEntity<List<ContactDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new ContactServiceException(e.getCause().getMessage()) : e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return contactService
     */
    protected ContactService getContactService()
    {
        return this.contactService;
    }
}