// Generated by andromda-angular cartridge (view\view.component.spec.ts.vsl) DO NOT EDIT!
import { waitForAsync, ComponentFixture, TestBed } from '@angular/core/testing';
import { DocumentDetailsImplComponent } from '@views/document/details/document-details-impl';
import { EditDocumentComponent } from '@views/document/edit/edit-document';

describe('EditDocumentComponent', () => {
	let component: EditDocumentComponent;
	let fixture: ComponentFixture<EditDocumentComponent>;

	beforeEach(waitForAsync(() => {
		TestBed.configureTestingModule({
			declarations: [EditDocumentComponent]
		})
			.compileComponents();
	}));

	beforeEach(() => {
		// fixture = TestBed.createComponent(EditDocumentComponent);
		// component = fixture.componentInstance;
		// fixture.detectChanges();
	});

	it('should create', () => {
		// expect(component).toBeTruthy();
	});
});
