// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, inject, linkedSignal, signal } from '@angular/core';
import { InvoiceDetailsComponent } from '@views/invoice/details/invoice-details';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { Loader } from "@shared/loader/loader";
import { DocumentApiStore } from '@app/store/bw/co/centralkyc/document/document-api.store';

@Component({
  selector: 'app-invoice-details',
  templateUrl: './invoice-details.html',
  styleUrls: ['./invoice-details.scss'],
  standalone: true,
  imports: [
    CommonModule,
    MaterialModule,
    TranslateModule,
    Loader,
  ],
})
export class InvoiceDetailsImplComponent extends InvoiceDetailsComponent {

  documentApiStore = inject(DocumentApiStore);

  override loading = linkedSignal(() => this.kycInvoiceApiStore.loading());
  override error = linkedSignal(() => this.kycInvoiceApiStore.error());
  override messages = linkedSignal(() => this.kycInvoiceApiStore.messages());
  override success = linkedSignal(() => this.kycInvoiceApiStore.success());

  kycInvoice = linkedSignal(() => this.kycInvoiceApiStore.data());

  // File upload state
  uploadingInvoiceDoc = signal(false);
  uploadingProofOfPayment = signal(false);

  constructor() {
    super();
  }

  override ngOnInit() {
    this.route.queryParams.subscribe((params) => {
      const id = params['id'];
      if (id) {
        this.kycInvoiceApiStore.findById({ id: id });
      }
    });

  }

  attachInvoiceDocument(): void {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = 'application/pdf,image/jpeg,image/jpg,image/png,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    input.onchange = (event: any) => {
      const file = event.target.files[0];
      if (file) {
        this.handleInvoiceDocumentUpload(file);
      }
    };
    input.click();
  }

  attachProofOfPayment(): void {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = 'application/pdf,image/jpeg,image/jpg,image/png,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    input.onchange = (event: any) => {
      const file = event.target.files[0];
      if (file) {
        this.handleProofOfPaymentUpload(file);
      }
    };
    input.click();
  }

  private handleInvoiceDocumentUpload(file: File): void {
    if (!this.validateFile(file)) {
      return;
    }

    const invoice = this.kycInvoice();
    if (!invoice?.id) {
      this.toaster.error('No invoice selected for document upload');
      return;
    }

    this.uploadingInvoiceDoc.set(true);

    // For now, we'll use a placeholder approach since INVOICE is not in TargetEntity
    // You may need to add INVOICE to the TargetEntity enum or use the ORGANISATION target
    // TODO: Update this once INVOICE is added to TargetEntity enum
    this.documentApiStore.upload({
      target: 'INVOICE' as any, // Using string as workaround
      targetId: invoice.id,
      documentTypeId: 'INVOICE_DOCUMENT',
      file: file,
    });

    // Watch for success/error through signals with effect
    setTimeout(() => {
      if (this.documentApiStore.success()) {
        this.uploadingInvoiceDoc.set(false);
        this.toaster.success('Invoice document uploaded successfully');
        // Reload invoice data to get updated document
        if (invoice.id) {
          this.kycInvoiceApiStore.findById({ id: invoice.id });
        }
      } else if (this.documentApiStore.error()) {
        this.uploadingInvoiceDoc.set(false);
        this.toaster.error('Failed to upload invoice document');
      }
    }, 2000); // Give time for upload to complete
  }

  private handleProofOfPaymentUpload(file: File): void {
    if (!this.validateFile(file)) {
      return;
    }

    const invoice = this.kycInvoice();
    if (!invoice?.id) {
      this.toaster.error('No invoice selected for document upload');
      return;
    }

    this.uploadingProofOfPayment.set(true);

    // For now, we'll use a placeholder approach since INVOICE is not in TargetEntity
    // You may need to add INVOICE to the TargetEntity enum or use the ORGANISATION target
    // TODO: Update this once INVOICE is added to TargetEntity enum
    this.documentApiStore.upload({
      target: 'INVOICE' as any, // Using string as workaround
      targetId: invoice.id,
      documentTypeId: 'PROOF_OF_PAYMENT',
      file: file,
    });

    // Watch for success/error through signals with effect
    setTimeout(() => {
      if (this.documentApiStore.success()) {
        this.uploadingProofOfPayment.set(false);
        this.toaster.success('Proof of payment uploaded successfully');
        // Reload invoice data to get updated document
        if (invoice.id) {
          this.kycInvoiceApiStore.findById({ id: invoice.id });
        }
      } else if (this.documentApiStore.error()) {
        this.uploadingProofOfPayment.set(false);
        this.toaster.error('Failed to upload proof of payment');
      }
    }, 2000); // Give time for upload to complete
  }

  private validateFile(file: File): boolean {
    // Check file size (max 10MB)
    const maxSize = 10 * 1024 * 1024;
    if (file.size > maxSize) {
      this.toaster.error('File size must be less than 10MB');
      return false;
    }

    // Check file type
    const allowedTypes = [
      'application/pdf',
      'image/jpeg',
      'image/jpg',
      'image/png',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ];
    if (!allowedTypes.includes(file.type)) {
      this.toaster.error('Invalid file type. Only PDF, JPG, PNG, DOC, and DOCX files are allowed');
      return false;
    }

    return true;
  }

  doNgOnDestroy(): void {
  }

  override invoiceDetailsEdit() {

    this.router.navigate(['/invoice/edit'], { queryParams: { id: this.kycInvoice()?.id } });
  }
}
