// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.organisation.branch;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import java.util.Collection;

import org.apache.commons.lang3.StringUtils;
import org.springframework.data.domain.Page;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.organisation.OrganisationDTO;
import bw.co.centralkyc.organisation.OrganisationService;

@RestController
public class BranchApiImpl implements BranchApi {

    private final OrganisationService orgService;
    private final BranchService branchService;

    public BranchApiImpl(BranchService branchService, OrganisationService orgService) {
        
        this.orgService = orgService;
        this.branchService = branchService;
    }


    @Override
    public ResponseEntity<BranchDTO> findById(String id) {
        
        try {

            BranchDTO branch = branchService.findById(id);

            if(StringUtils.isBlank(branch.getOrganisationId())) {

                throw new BranchServiceException("This branch has no organisation.");
            }

            OrganisationDTO org = orgService.findById(branch.getOrganisationId());
            branch.setOrganisation(org.getName());

            return ResponseEntity.ok(branchService.findById(id));
        } catch (Exception e) {
            // logger.error(e.getMessage());
            e.printStackTrace();
            throw e;
        }


    }

    @Override
    public ResponseEntity<Collection<BranchDTO>> findByOrganisation(String organisationId) {
        
        try {
            OrganisationDTO org = orgService.findById(organisationId);
            return ResponseEntity.ok(branchService.findByOrganisation(org.getId()));
        } catch (Exception e) {
            // logger.error(e.getMessage());
            e.printStackTrace();
            throw e;
        }


    }

    @Override
    public ResponseEntity<Collection<BranchDTO>> findByOrganisationPaged(String organisationId, Integer pageNumber, Integer pageSize) {
        
        try {
            OrganisationDTO org = orgService.findById(organisationId);

            return ResponseEntity.ok(branchService.findByOrganisation(organisationId, pageNumber, pageSize));
            
        } catch (Exception e) {
            
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<BranchDTO>> getAll() {
        
        try {
            return ResponseEntity.ok(branchService.getAll());
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }


    }

    @Override
    public ResponseEntity<Page<BranchDTO>> getAllPaged(Integer pageNumber, Integer pageSize) {
        
        try {
            return ResponseEntity.ok(branchService.getAll(pageNumber, pageSize));
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }


    }

    @Override
    public ResponseEntity<Page<BranchDTO>> pagedSearch(String criteria, Integer pageNumber, Integer pageSize) {
        
        try {
            return ResponseEntity.ok(branchService.search(criteria, pageNumber, pageSize));
            
        } catch (Exception e) {
            // logger.error(e.getMessage());
            e.printStackTrace();
            throw e;
        }


    }

    @Override
    public ResponseEntity<Boolean> remove(String id) {
        
        try {

            return ResponseEntity.ok(branchService.remove(id));

        } catch (Exception e) {
            // logger.error(e.getMessage());
            e.printStackTrace();
            throw e;
        }


    }

    @Override
    public ResponseEntity<BranchDTO> save(BranchDTO branch) {
        
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(branch, authentication);
            return ResponseEntity.ok(branchService.save(branch));

        } catch (Exception e) {
            // logger.error(e.getMessage());
            e.printStackTrace();

            throw e;
        }


    }

    @Override
    public ResponseEntity<Collection<BranchDTO>> search(String criteria) {
        
        try {
            return ResponseEntity.ok(branchService.search(criteria));
            
        } catch (Exception e) {
            // logger.error(e.getMessage());
            e.printStackTrace();
            throw e;
        }


    }
}
