// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.kyc.verification;

import java.util.UUID;

import org.springframework.stereotype.Repository;

import bw.co.centralkyc.kyc.KycRecordRepository;

/**
 * @see KycVerification
 */
@Repository("kycVerificationDao")
public class KycVerificationDaoImpl
    extends KycVerificationDaoBase
{
    

    public KycVerificationDaoImpl(KycRecordRepository kycRecordRepository,
            KycVerificationRepository kycVerificationRepository) {
        super(kycRecordRepository, kycVerificationRepository);
        //TODO Auto-generated constructor stub
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toKycVerificationDTO(
        KycVerification source,
        KycVerificationDTO target)
    {
        // TODO verify behavior of toKycVerificationDTO
        super.toKycVerificationDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KycVerificationDTO toKycVerificationDTO(final KycVerification entity)
    {
        // TODO verify behavior of toKycVerificationDTO
        return super.toKycVerificationDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private KycVerification loadKycVerificationFromKycVerificationDTO(KycVerificationDTO kycVerificationDTO)
    {
        if (kycVerificationDTO.getId() == null)
        {
            return  KycVerification.Factory.newInstance();
        }
        else
        {
            return this.kycVerificationRepository.findById(UUID.fromString(kycVerificationDTO.getId()))
                .orElseThrow(() -> new KycVerificationServiceException("Entity not found for id: " + kycVerificationDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public KycVerification kycVerificationDTOToEntity(KycVerificationDTO kycVerificationDTO)
    {
        // TODO verify behavior of kycVerificationDTOToEntity
        KycVerification entity = this.loadKycVerificationFromKycVerificationDTO(kycVerificationDTO);
        this.kycVerificationDTOToEntity(kycVerificationDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void kycVerificationDTOToEntity(
        KycVerificationDTO source,
        KycVerification target,
        boolean copyIfNull)
    {
        // TODO verify behavior of kycVerificationDTOToEntity
        super.kycVerificationDTOToEntity(source, target, copyIfNull);
    }
}