// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::document::DataVerificationStatus
 */
export enum DataVerificationStatus {
    /** TODO: Model Documentation for Enumeration Literal UNVERIFIED value "UNVERIFIED": $literal.enumerationLiteralDisplay */
    UNVERIFIED = "UNVERIFIED",
    /** TODO: Model Documentation for Enumeration Literal VERIFIED value "VERIFIED": $literal.enumerationLiteralDisplay */
    VERIFIED = "VERIFIED",
    /** TODO: Model Documentation for Enumeration Literal VERIFICATION_FAILED value "VERIFICATION_FAILED": $literal.enumerationLiteralDisplay */
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
}
