// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::document::VerificationTagStatus
 */
export enum VerificationTagStatus {
    /** TODO: Model Documentation for Enumeration Literal UNCHECKED value "UNCHECKED": $literal.enumerationLiteralDisplay */
    UNCHECKED = "UNCHECKED",
    /** TODO: Model Documentation for Enumeration Literal SUCCESSFUL value "SUCCESSFUL": $literal.enumerationLiteralDisplay */
    SUCCESSFUL = "SUCCESSFUL",
    /** TODO: Model Documentation for Enumeration Literal FAILED value "FAILED": $literal.enumerationLiteralDisplay */
    FAILED = "FAILED"
}
