// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { CountDTO } from '@models/bw/co/centralkyc/analytics/count-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class AnalyticsApi {
    
    protected path = '/analytics';

    private http = inject(HttpClient);

    public countAnalytics(): Observable<CountDTO> {

        return this.http.get<CountDTO>(`${this.path}/count`);
    }

    public organisationCountAnalytics(organisationId: string): Observable<CountDTO> {

        return this.http.get<CountDTO>(`${this.path}/count/by-organisation/${organisationId}`);
    }

}
