import { TargetEntity } from '@models/bw/co/centralkyc/target-entity';
// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycRecordDTO } from '@models/bw/co/centralkyc/kyc/kyc-record-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';
import { KycRecordSearchCriteria } from '@app/models/bw/co/centralkyc/kyc/kyc-record-search-criteria';

@Injectable({
  providedIn: 'root'
})
export class KycRecordApi {

  protected path = '/kyc';

  private http = inject(HttpClient);

  public createIndividualRecord(individualId: string): Observable<KycRecordDTO> {

    return this.http.get<KycRecordDTO>(`${this.path}/individual/${individualId}`);
  }

  public createOrganisationRecord(organisationId: string): Observable<KycRecordDTO> {

    return this.http.get<KycRecordDTO>(`${this.path}/organisation/${organisationId}`);
  }

  public findById(id: string): Observable<KycRecordDTO> {

    return this.http.get<KycRecordDTO>(`${this.path}/${id}`);
  }

  public findByIdentityNo(identityNo: string): Observable<KycRecordDTO[]> {

    return this.http.get<KycRecordDTO[]>(`${this.path}/by-identity/${identityNo}`);
  }

  public findByIdentityNoPaged(identityNo: string, pageNumber: number, pageSize: number): Observable<Page<KycRecordDTO>> {


    return this.http.get<Page<KycRecordDTO>>(`${this.path}/by-identity/${identityNo}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public findByIndividual(individualId: string): Observable<KycRecordDTO[]> {
    return this.http.get<KycRecordDTO[]>(`${this.path}/by-individual/${individualId}`);
  }

  public findByIndividualPaged(individualId: string, pageNumber: number, pageSize: number): Observable<Page<KycRecordDTO>> {
    return this.http.get<Page<KycRecordDTO>>(`${this.path}/by-individual/${individualId}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public findByOrganisation(organisationId: string): Observable<KycRecordDTO[]> {
    return this.http.get<KycRecordDTO[]>(`${this.path}/by-organisation/${organisationId}`);
  }

  public findByOrganisationRegistration(registrationNo: string): Observable<KycRecordDTO[]> {
    return this.http.get<KycRecordDTO[]>(`${this.path}/by-organisation-registration/${registrationNo}`);
  }

  public findByOrganisationRegistrationPaged(registrationNo: string, pageNumber: number, pageSize: number): Observable<Page<KycRecordDTO>> {
    return this.http.get<Page<KycRecordDTO>>(`${this.path}/by-organisation_registration/${registrationNo}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public getAll(): Observable<KycRecordDTO[]> {

    return this.http.get<KycRecordDTO[]>(`${this.path}`);
  }

  public getAllPaged(pageNumber: number, pageSize: number): Observable<Page<KycRecordDTO>> {

    return this.http.get<Page<KycRecordDTO>>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public pagedSearch(criteria: SearchObject<KycRecordSearchCriteria>): Observable<Page<KycRecordDTO>> {

    return this.http.post<Page<KycRecordDTO>>(`${this.path}/search/paged`, criteria);
  }

  public remove(id: string): Observable<boolean> {

    return this.http.delete<boolean>(`${this.path}/${id}`);
  }

  public save(kycRecord: KycRecordDTO): Observable<KycRecordDTO> {

    return this.http.post<KycRecordDTO>(`${this.path}`, kycRecord);
  }

  public search(criteria: KycRecordSearchCriteria): Observable<KycRecordDTO[]> {

    return this.http.post<KycRecordDTO[]>(`${this.path}/search`, criteria);
  }

  public findMyCurrentRecord(ownerType: TargetEntity): Observable<KycRecordDTO> {

    return this.http.get<KycRecordDTO>(`${this.path}/my_current?ownerType=${ownerType}`);
  }

  public findMyRecords(): Observable<KycRecordDTO[]> {

    return this.http.get<KycRecordDTO[]>(`${this.path}/mine`);
  }

  public createNew(record: KycRecordDTO, files: File[]): Observable<KycRecordDTO> {

    const formData = new FormData();
    formData.append('record', new Blob([JSON.stringify(record)], { type: 'application/json' }));

    files.forEach((file, index) => {
      formData.append(`files`, file);
    });

    return this.http.post<KycRecordDTO>(`${this.path}/new`, formData);
  }
}
