// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by controller-advice.java.vsl in andromda-spring-cartridge. Do not modify by hand!.
//
package bw.co.knowvera.analytics;

import bw.co.knowvera.ErrorResponse;
import bw.co.knowvera.individual.IndividualServiceException;
import bw.co.knowvera.invoice.KycInvoiceServiceException;
import bw.co.knowvera.organisation.client.ClientRequestServiceException;
import bw.co.knowvera.subscription.KycSubscriptionServiceException;

import java.time.Instant;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Translates the errors thrown by {@link AnalyticsApiServiceBase}
 * into human-readable API responses for the analyticsApi endpoints.
 *
 * Scoped to {@link AnalyticsApi} only, and ordered ahead
 * of global exception handlers so that this advice's friendlier messages take precedence.
 */
@RestControllerAdvice(assignableTypes = AnalyticsApi.class)
@Order(Ordered.HIGHEST_PRECEDENCE)
public class AnalyticsApiControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(AnalyticsApiControllerAdvice.class);

    /**
     * Handles manual argument validation checks thrown by AnalyticsApiServiceBase.
     * Maps generated validation messages to friendly human-readable descriptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ErrorResponse> handleIllegalArgument(IllegalArgumentException ex) {
        String message = ex.getMessage() == null ? "" : ex.getMessage();
        String friendly = toFriendlyMessage(message);

        LOGGER.warn("AnalyticsApi validation failed: {}", message);

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.BAD_REQUEST.value(),
                HttpStatus.BAD_REQUEST.name(),
                friendly,
                Arrays.asList(ex.getMessage()),
                Instant.now()
        );

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(errorResponse);
    }

    /**
     * Handles {@link ClientRequestServiceException} thrown by referenced services.
     */
    @ExceptionHandler(ClientRequestServiceException.class)
    public ResponseEntity<ErrorResponse> handleClientRequestServiceException(ClientRequestServiceException ex) {
        LOGGER.error("Referenced service error (ClientRequestService)", ex);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ErrorResponse(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        HttpStatus.INTERNAL_SERVER_ERROR.name(),
                        "An error occurred while communicating with dependent services. Please try again shortly.",
                        null,
                        Instant.now()
                ));
    }
    /**
     * Handles {@link IndividualServiceException} thrown by referenced services.
     */
    @ExceptionHandler(IndividualServiceException.class)
    public ResponseEntity<ErrorResponse> handleIndividualServiceException(IndividualServiceException ex) {
        LOGGER.error("Referenced service error (IndividualService)", ex);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ErrorResponse(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        HttpStatus.INTERNAL_SERVER_ERROR.name(),
                        "An error occurred while communicating with dependent services. Please try again shortly.",
                        null,
                        Instant.now()
                ));
    }
    /**
     * Handles {@link KycSubscriptionServiceException} thrown by referenced services.
     */
    @ExceptionHandler(KycSubscriptionServiceException.class)
    public ResponseEntity<ErrorResponse> handleKycSubscriptionServiceException(KycSubscriptionServiceException ex) {
        LOGGER.error("Referenced service error (KycSubscriptionService)", ex);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ErrorResponse(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        HttpStatus.INTERNAL_SERVER_ERROR.name(),
                        "An error occurred while communicating with dependent services. Please try again shortly.",
                        null,
                        Instant.now()
                ));
    }
    /**
     * Handles {@link KycInvoiceServiceException} thrown by referenced services.
     */
    @ExceptionHandler(KycInvoiceServiceException.class)
    public ResponseEntity<ErrorResponse> handleKycInvoiceServiceException(KycInvoiceServiceException ex) {
        LOGGER.error("Referenced service error (KycInvoiceService)", ex);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ErrorResponse(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        HttpStatus.INTERNAL_SERVER_ERROR.name(),
                        "An error occurred while communicating with dependent services. Please try again shortly.",
                        null,
                        Instant.now()
                ));
    }

    /**
     * Maps validation messages thrown by AnalyticsApiServiceBase to plain-language equivalents.
     */
    private String toFriendlyMessage(String message) {
        if (message.contains(".organisationCountAnalytics(") && message.contains("'organisationId'")) {
            return "Organisation Id is required.";
        }


        // Fallback for any unmapped validation message
        return message;
    }
}