// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { VerificationDataConfigDTO } from '@models/bw/co/knowvera/document/type/verification/verification-data-config-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class VerificationDataConfigApi {
    
    protected path = '/document-type-verification';

    private http = inject(HttpClient);

    public findById(id: string): Observable<VerificationDataConfigDTO> {

        return this.http.get<VerificationDataConfigDTO>(`${this.path}/${id}`);
    }

    public remove(id: string): Observable<boolean> {

        return this.http.delete<boolean>(`${this.path}/${id}`);
    }

    public save(documentType: VerificationDataConfigDTO): Observable<VerificationDataConfigDTO> {

        return this.http.post<VerificationDataConfigDTO>(`${this.path}`, documentType);
    }

}
