// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { DocumentTypeDTO } from '@models/bw/co/centralkyc/document/type/document-type-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class DocumentTypeApi {

    protected path = '/document/type';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<DocumentTypeDTO | any> {

        return this.http.get<DocumentTypeDTO | any>(`${this.path}/${id}`);
    }

    public getAll(): Observable<DocumentTypeDTO[] | any[]> {

        return this.http.get<DocumentTypeDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<DocumentTypeDTO>[] | any[]> {

        return this.http.get<Page<DocumentTypeDTO>[] | any[]>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: string | any , pageNumber: number | any , pageSize: number | any ): Observable<Page<DocumentTypeDTO> | any> {

        return this.http.get<Page<DocumentTypeDTO> | any>(`${this.path}/search/paged?criteria=${criteria}&pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(documentType: DocumentTypeDTO | any ): Observable<DocumentTypeDTO | any> {

        return this.http.post<DocumentTypeDTO | any>(`${this.path}`, documentType);
    }

    public search(criteria: string | any ): Observable<DocumentTypeDTO[] | any[]> {

        return this.http.get<DocumentTypeDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

}
