// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchUsersComponent } from '@views/user/search/search-users';
import { SearchUsersVarsForm } from '@views/user/search/search-users';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';

@Component({
  selector: 'app-search-users',
  templateUrl: './search-users.html',
  styleUrls: ['./search-users.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
  ],
})
export class SearchUsersImplComponent extends SearchUsersComponent {

    constructor() {
        super();
    }

    doNgOnDestroy(): void {
    }
}
