// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { UserDTO } from '@models/bw/co/knowvera/user/user-dto';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class UserApi {

    protected path = '/users';

    private http = inject(HttpClient);

    public addRole(userId: string | any , role: string | any ): Observable<boolean | any> {

        return this.http.put<boolean | any>(`${this.path}/role?userId=${userId}&role=${role}`, {userId: userId, role: role});
    }

    /** Administrative reset to a temporary password (users:manage). Sent as a form body, never in the URL. */
    public changePassword(userId: string | any , newPassword: string | any ): Observable<string | any> {

        const body = new HttpParams({ fromObject: { userId, newPassword } });
        return this.http.post(`${this.path}/updatePassword`, body, { responseType: 'text' });
    }

    public findByBranchId(branchId: string | any ): Observable<UserDTO[] | any[]> {

        return this.http.get<UserDTO[] | any[]>(`${this.path}/branch-id/${branchId}/branchId/${branchId}`);
    }

    public findByBranchName(branch: string | any ): Observable<UserDTO[] | any[]> {

        return this.http.get<UserDTO[] | any[]>(`${this.path}/branch-name/${branch}`);
    }

    public findByClientRoles(roles: Set<string> | any , clientId: string | any ): Observable<UserDTO[] | any[]> {

        return this.http.get<UserDTO[] | any[]>(`${this.path}/client/roles?roles=${roles}`);
    }

    public findByIdentityNo(identityNo: string | any ): Observable<UserDTO | any> {

        return this.http.get<UserDTO | any>(`${this.path}/by-identity/${identityNo}/identityNo/${identityNo}`);
    }

    public findByOrganisationId(organisationId: string | any ): Observable<UserDTO[] | any[]> {

        return this.http.get<UserDTO[] | any[]>(`${this.path}/organisation-id/${organisationId}`);
    }

    public findByOrganisationName(organisation: string | any ): Observable<UserDTO[] | any[]> {

        return this.http.get<UserDTO[] | any[]>(`${this.path}/department-name/${organisation}`);
    }

    public findByRealmRoles(roles: Set<string> | any ): Observable<UserDTO[] | any[]> {

        return this.http.get<UserDTO[] | any[]>(`${this.path}/realm/roles?roles=${roles}`);
    }

    public findUserById(userId: string | any ): Observable<UserDTO | any> {

        return this.http.get<UserDTO | any>(`${this.path}?userId=${userId}`);
    }

    public loadUsers(): Observable<UserDTO[] | any[]> {

        return this.http.get<UserDTO[] | any[]>(`${this.path}/load`);
    }

    public removeRole(userId: string | any , role: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/role?userId=${userId}&role=${role}`);
    }

    public saveUser(user: UserDTO | any ): Observable<UserDTO | any> {

        return this.http.post<UserDTO | any>(`${this.path}/create`, user);
    }

    public search(criteria: string | any ): Observable<UserDTO[] | any[]> {

        return this.http.get<UserDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

    public updateUserName(userId: string | any , username: string | any ): Observable<boolean | any> {

        return this.http.patch<boolean | any>(`${this.path}/${userId}?username=${username}`, {userId: userId, username: username});
    }

    public addClientRoles(clientId: string | any, roles: string[] | any, userId: string | any): Observable<UserDTO | any> {

        return this.http.post<UserDTO | any>(`${this.path}/add-client-roles?clientId=${clientId}&roles=${roles}&userId=${userId}`, null);
    }
}
