// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchOrganisationsComponent } from '@views/organisation/search/search-organisations';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { OrganisationSearchCriteria } from '@app/models/bw/co/centralkyc/organisation/organisation-search-criteria';
import { SearchObject } from '@app/models/search-object';
import { Page } from '@app/models/page.model';
import { MatPaginator } from '@angular/material/paginator';

@Component({
  selector: 'app-search-organisations',
  templateUrl: './search-organisations.html',
  styleUrls: ['./search-organisations.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
  ],
})
export class SearchOrganisationsImplComponent extends SearchOrganisationsComponent {

    constructor() {
        super();
        this.organisationsTableSignal = this.organisationApiStore.dataPage;
    }

    doNgOnDestroy(): void {
    }

    override doNgAfterViewInit(): void {
    this.organisationsTable?.tablePaginator?.page?.subscribe({
      next: (paginator: MatPaginator) => {
        this.doSearch(paginator.pageIndex, paginator.pageSize);
      },
    });

    this.doSearch();
  }

  override beforeSearchOrganisationsSearch(form: any): void {
    this.doSearch();
  }

  private doSearch(pageNumber: number = 0, pageSize: number = 10): void {

    let value = this.searchOrganisationsSignal().criteria;

    let criteria = new SearchObject<OrganisationSearchCriteria>()
    criteria.pageNumber = pageNumber;
    criteria.pageSize = pageSize;
    criteria.criteria = value;

    this.organisationApiStore.pagedSearch({
      criteria: criteria
    });
  }
}
