// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, linkedSignal, Signal } from '@angular/core';
import { SearchDocumentTypesComponent } from '@views/document/type/search/search-document-types';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { MatPaginator } from '@angular/material/paginator';
import { Page } from '@app/models/page.model';
import { DocumentTypeDTO } from '@app/models/bw/co/centralkyc/document/type/document-type-dto';
import { ActionTemplate } from '@app/models/action-template';

@Component({
  selector: 'app-search-document-types',
  templateUrl: './search-document-types.html',
  styleUrls: ['./search-document-types.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
  ],
})
export class SearchDocumentTypesImplComponent extends SearchDocumentTypesComponent {

  override loading = linkedSignal(() => false);
  override loaderMessage = linkedSignal(() => '');

  override documentTypesTableColumnsActions: ActionTemplate[] = [
    {
      id: 'search-document-types-edit',
      label: 'edit',
      icon: 'edit'
    },
  ];

  override documentTypesTableSignal = linkedSignal(() => new Page<DocumentTypeDTO>());

  constructor() {
    super();
  }

  override doNgAfterViewInit(): void {
    this.documentTypesTable?.tablePaginator?.page?.subscribe({
      next: (paginator: MatPaginator) => {
        this.doSearch(paginator.pageIndex, paginator.pageSize);
      },
    });

    this.doSearch();
  }

  doNgOnDestroy(): void { }

  override beforeSearchDocumentTypesSearch(form: any): void {
    this.doSearch();
  }

  private doSearch(pageNumber: number = 0, pageSize: number = 10): void {
    let criteria = this.searchDocumentTypesSignal().criteria;

    this.loading.set(true);
    this.loaderMessage.set(`Loading page ${pageNumber} document types.`);

    this.documentTypeApi.pagedSearch(
      criteria ? criteria : '',
      pageNumber,
      pageSize
    ).subscribe({
      next: (documentTypePage: Page<DocumentTypeDTO>) => {

        this.documentTypesTableSignal.set(documentTypePage);
        this.loading.set(false);
      },
      error: (error) => {
        console.log(error);
        this.toaster.error(
          error.error?.message ? error.error.message : error.message
        );
        this.loading.set(false);
      }
    });
  }

  override documentTypesTableActionClicked(event: any) {
    switch (event.action) {

      case 'search-document-types-edit':

      this.router.navigate(['document', 'type', 'edit'], {queryParams: {
        id: event.row.id
      }})
        break
    }
  }
}
