// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.settings.kyc;

import bw.co.centralkyc.document.type.field.ExpectedFieldRepository;
import org.springframework.stereotype.Repository;

/**
 * @see GroupField
 */
@Repository("groupFieldDao")
public class GroupFieldDaoImpl
    extends GroupFieldDaoBase
{
    
    public GroupFieldDaoImpl(
        ExpectedFieldRepository expectedFieldRepository,
        KycFieldGroupRepository kycFieldGroupRepository,
        GroupFieldRepository groupFieldRepository
    ) {

        super(
            expectedFieldRepository,
            kycFieldGroupRepository,
            groupFieldRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toGroupFieldDTO(
        GroupField source,
        GroupFieldDTO target)
    {
        // TODO verify behavior of toGroupFieldDTO
        super.toGroupFieldDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupFieldDTO toGroupFieldDTO(final GroupField entity)
    {
        // TODO verify behavior of toGroupFieldDTO
        return super.toGroupFieldDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private GroupField loadGroupFieldFromGroupFieldDTO(GroupFieldDTO groupFieldDTO)
    {
        // TODO implement loadGroupFieldFromGroupFieldDTO
        throw new UnsupportedOperationException("bw.co.centralkyc.settings.kyc.loadGroupFieldFromGroupFieldDTO(GroupFieldDTO) not yet implemented.");

        /* A typical implementation looks like this:
        if (groupFieldDTO.getId() == null)
        {
            return  GroupField.Factory.newInstance();
        }
        else
        {
            return this.groupFieldRepository.findById(groupFieldDTO.getId())
                .orElseThrow(() -> new GroupFieldServiceException("Entity not found for id: " + groupFieldDTO.getId()));
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public GroupField groupFieldDTOToEntity(GroupFieldDTO groupFieldDTO)
    {
        // TODO verify behavior of groupFieldDTOToEntity
        GroupField entity = this.loadGroupFieldFromGroupFieldDTO(groupFieldDTO);
        this.groupFieldDTOToEntity(groupFieldDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void groupFieldDTOToEntity(
        GroupFieldDTO source,
        GroupField target,
        boolean copyIfNull)
    {
        // TODO verify behavior of groupFieldDTOToEntity
        super.groupFieldDTOToEntity(source, target, copyIfNull);
    }
}