// Generated by andromda-angular cartridge (view\components\component.ts.vsl) DO NOT EDIT
import {
  AfterViewInit,
  Component,
  inject,
  Input,
  OnDestroy,
  OnInit,
  ViewChild,
} from "@angular/core";
import {COMMA, ENTER} from '@angular/cdk/keycodes';
import {
  FormsModule,
  ReactiveFormsModule,
  FormGroup,
  FormControl,
  FormBuilder,
  Validators,
  FormArray,
} from "@angular/forms";
import { SelectItem } from "@app/utils/select-item";
import { MatSelectChange } from '@angular/material/select';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { MatChip, MatChipInput, MatChipInputEvent } from "@angular/material/chips";
import {MatAutocompleteSelectedEvent, MatAutocompleteModule} from '@angular/material/autocomplete';
import { MatDialog } from '@angular/material/dialog';
import { firstValueFrom, Observable, map, of, startWith } from "rxjs";
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { OrganisationListDTO } from '@models/bw/co/centralkyc/organisation/organisation-list-dto';
import { GeneralStatus } from '@models/bw/co/centralkyc/general-status';
import { BranchDTO } from '@models/bw/co/centralkyc/organisation/branch/branch-dto';
import { SearchObject } from '@models/search-object';
import { UserEditorComponent } from './user-editor';
import { TableComponent } from '@components/table/table';
import { FormField, PathKind, SchemaPathTree } from "@angular/forms/signals";

@Component({
  selector: "app-user-editor",
  templateUrl: "./user-editor.html",
  styleUrls: [],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    FormField,
  ]
})
export class UserEditorImplComponent extends UserEditorComponent {

    constructor() {
        super();
    }

    override createNewRoles(): String {
      throw new Error("Method not implemented.");
    }
}
