// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by controller-advice.java.vsl in andromda-spring-cartridge. Do not modify by hand!.
//
package bw.co.knowvera.invoice;

import bw.co.knowvera.ErrorResponse;
import java.time.Instant;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Translates the errors thrown by {@link KycInvoiceApiServiceBase}
 * into human-readable API responses for the kycInvoiceApi endpoints.
 *
 * Scoped to {@link KycInvoiceApi} only, and ordered ahead
 * of global exception handlers so that this advice's friendlier messages take precedence.
 */
@RestControllerAdvice(assignableTypes = KycInvoiceApi.class)
@Order(Ordered.HIGHEST_PRECEDENCE)
public class KycInvoiceApiControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(KycInvoiceApiControllerAdvice.class);

    /**
     * Handles manual argument validation checks thrown by KycInvoiceApiServiceBase.
     * Maps generated validation messages to friendly human-readable descriptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ErrorResponse> handleIllegalArgument(IllegalArgumentException ex) {
        String message = ex.getMessage() == null ? "" : ex.getMessage();
        String friendly = toFriendlyMessage(message);

        LOGGER.warn("KycInvoiceApi validation failed: {}", message);

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.BAD_REQUEST.value(),
                HttpStatus.BAD_REQUEST.name(),
                friendly,
                Arrays.asList(ex.getMessage()),
                Instant.now()
        );

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(errorResponse);
    }

    /**
     * Handles {@link KycInvoiceServiceException} thrown by referenced services.
     */
    @ExceptionHandler(KycInvoiceServiceException.class)
    public ResponseEntity<ErrorResponse> handleKycInvoiceServiceException(KycInvoiceServiceException ex) {
        LOGGER.error("Referenced service error (KycInvoiceService)", ex);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ErrorResponse(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        HttpStatus.INTERNAL_SERVER_ERROR.name(),
                        "An error occurred while communicating with dependent services. Please try again shortly.",
                        null,
                        Instant.now()
                ));
    }

    /**
     * Maps validation messages thrown by KycInvoiceApiServiceBase to plain-language equivalents.
     */
    private String toFriendlyMessage(String message) {
        if (message.contains(".findById(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".save(") && message.contains("'invoice'")) {
            return "Invoice is required.";
        }

        if (message.contains(".remove(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".upload(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".upload(") && message.contains("'purpose'")) {
            return "Purpose is required.";
        }

        if (message.contains(".upload(") && message.contains("'file'")) {
            return "File is required.";
        }

        if (message.contains(".generateInvoice(") && message.contains("'subscriptionId'")) {
            return "Subscription Id is required.";
        }

        if (message.contains(".findBySubscription(") && message.contains("'subscriptionId'")) {
            return "Subscription Id is required.";
        }

        if (message.contains(".findByOrganisation(") && message.contains("'organisationId'")) {
            return "Organisation Id is required.";
        }

        if (message.contains(".findBySubscriptionPaged(") && message.contains("'subscriptionId'")) {
            return "Subscription Id is required.";
        }

        if (message.contains(".findByOrganisationPaged(") && message.contains("'organisationId'")) {
            return "Organisation Id is required.";
        }


        // Fallback for any unmapped validation message
        return message;
    }
}