// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.kyvera.sequence;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import bw.co.kyvera.utils.MappingUtils;

@Mapper(
    componentModel = "spring",
    uses = {
        SequencePartMapper.class,
        MappingUtils.class
    }
)
public abstract class SequenceGeneratorMapper {
    
    /**
     * Converts this entity to an object of type {@link SequenceGeneratorDTO}.
     * @param entity
     * @return SequenceGeneratorDTO
     */
    @Mapping(source = "sequenceParts", target = "sequenceParts")
    public abstract SequenceGeneratorDTO toSequenceGeneratorDTO(SequenceGenerator entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link SequenceGeneratorDTO}.
     * @param entities
     * @return Collection<SequenceGeneratorDTO>     */
    public abstract List<SequenceGeneratorDTO> toSequenceGeneratorDTOCollection(Collection<SequenceGenerator> entities);

    /**
     * Converts an instance of type {@link SequenceGeneratorDTO} to this DAO's entity.
     * @param sequenceGeneratorDTO
     * @return SequenceGenerator
     */
    @InheritInverseConfiguration
    public abstract SequenceGenerator sequenceGeneratorDTOToEntity(SequenceGeneratorDTO sequenceGeneratorDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateSequenceGeneratorFromSequenceGeneratorDTO(SequenceGeneratorDTO sequenceGeneratorDTO, @MappingTarget SequenceGenerator entity);

}