// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.knowvera.kyc.fields;

import bw.co.knowvera.document.type.field.ExpectedFieldMapper;
import bw.co.knowvera.utils.MappingUtils;
import bw.co.knowvera.kyc.fields.GroupFieldValue;
import bw.co.knowvera.kyc.fields.GroupFieldValueDTO;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        ExpectedFieldMapper.class,
        KycReportSectionMapper.class,
        MappingUtils.class
    }
)
public abstract class GroupFieldValueMapper {
    
    /**
     * Converts this entity to an object of type {@link GroupFieldValueDTO}.
     * @param entity
     * @return GroupFieldValueDTO
     */
    @Mapping(source = "kycReportSection.id", target = "reportSectionId")
    @Mapping(source = "expectedField.id", target = "fieldId")
    @Mapping(source = "expectedField.field", target = "field")
    @Mapping(source = "expectedField.fieldLabel", target = "fieldLabel")
    @Mapping(source = "expectedField.mandatory", target = "mandatory")
    @Mapping(target = "fieldGroupId", ignore = true)
    public abstract GroupFieldValueDTO toGroupFieldValueDTO(GroupFieldValue entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link GroupFieldValueDTO}.
     * @param entities
     * @return Collection<GroupFieldValueDTO>     */
    public abstract List<GroupFieldValueDTO> toGroupFieldValueDTOCollection(Collection<GroupFieldValue> entities);

    /**
     * Converts an instance of type {@link GroupFieldValueDTO} to this DAO's entity.
     * @param groupFieldValueDTO
     * @return GroupFieldValue
     */
    @InheritInverseConfiguration
    public abstract GroupFieldValue groupFieldValueDTOToEntity(GroupFieldValueDTO groupFieldValueDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateGroupFieldValueFromGroupFieldValueDTO(GroupFieldValueDTO groupFieldValueDTO, @MappingTarget GroupFieldValue entity);

}