// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by controller-advice.java.vsl in andromda-spring-cartridge. Do not modify by hand!.
//
package bw.co.knowvera.subscription;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.context.request.WebRequest;

import bw.co.knowvera.ValidationMapping;

import java.net.URI;
import java.time.Instant;
import java.util.List;

/**
 * Translates the errors thrown by {@link KycSubscriptionApiServiceBase}
 * into human-readable API responses for the kycSubscriptionApi endpoints.
 *
 * Scoped to {@link KycSubscriptionApi} only, and ordered ahead
 * of global exception handlers so that this advice's friendlier messages take precedence.
 */
@RestControllerAdvice(assignableTypes = KycSubscriptionApi.class)
@Order(Ordered.HIGHEST_PRECEDENCE)
public class KycSubscriptionApiControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(KycSubscriptionApiControllerAdvice.class);

    /**
     * Ordered list of validation-message mappings.
     * Each entry matches a method-name substring and (optionally) a
     * field-name substring against the raw exception message, and
     * supplies the user-facing replacement text.
     */
    private static final List<ValidationMapping> VALIDATION_MAPPINGS = List.of(

            new ValidationMapping(".findById(", "'id'",
                    "Id is required."),

            new ValidationMapping(".save(", "'subscription'",
                    "Subscription is required."),

            new ValidationMapping(".remove(", "'id'",
                    "Id is required."),

            new ValidationMapping(".findByOrganisation(", "'organisationId'",
                    "Organisation Id is required.")
    );

    /**
     * Handles manual argument validation checks thrown by KycSubscriptionApiServiceBase.
     * Maps generated validation messages to friendly human-readable descriptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ProblemDetail> handleIllegalArgument(
            IllegalArgumentException ex,
            WebRequest request) {

        String message = ex.getMessage() == null ? "" : ex.getMessage();
        String friendly = toFriendlyMessage(message);

        List<String> errors = message.isBlank()
                ? List.of()
                : List.of(message);

        LOGGER.warn("KycSubscriptionApi validation failed: {}", message);

        ProblemDetail problemDetail = buildProblemDetail(
                HttpStatus.BAD_REQUEST,
                "service-validation-error",
                "KycSubscriptionApi validation failed",
                friendly,
                request,
                errors
        );

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(problemDetail);
    }

    /**
     * Handles {@link KycSubscriptionServiceException} thrown by referenced services.
     */
    @ExceptionHandler(KycSubscriptionServiceException.class)
    public ResponseEntity<ProblemDetail> handleKycSubscriptionServiceException(
            KycSubscriptionServiceException ex,
            WebRequest request) {

        LOGGER.error("Referenced service error (KycSubscriptionService)", ex);

        ProblemDetail problemDetail = buildProblemDetail(
                HttpStatus.INTERNAL_SERVER_ERROR,
                "service-error",
                "KycSubscriptionApi service error",
                "An error occurred while communicating with dependent services. Please try again shortly.",
                request,
                List.of()
        );

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(problemDetail);
    }

    /**
     * Builds an RFC 9457 {@link ProblemDetail} response body, with
     * {@code timestamp} and {@code errors} as extension members.
     */
    private ProblemDetail buildProblemDetail(
            HttpStatus status,
            String type,
            String title,
            String detail,
            WebRequest request,
            List<String> errors) {

        ProblemDetail problemDetail = ProblemDetail.forStatusAndDetail(status, detail);
        problemDetail.setType(URI.create(type));
        problemDetail.setTitle(title);
        problemDetail.setInstance(URI.create(getInstanceUri(request)));
        problemDetail.setProperty("timestamp", Instant.now());
        problemDetail.setProperty("errors", errors);

        return problemDetail;
    }

    /**
     * Extracts the request URI from the Spring WebRequest.
     */
    private String getInstanceUri(WebRequest request) {
        return request.getDescription(false)
                .replace("uri=", "");
    }

    /**
     * Maps validation messages thrown by KycSubscriptionApiServiceBase to
     * plain-language equivalents, using {@link #VALIDATION_MAPPINGS}.
     *
     * <p>
     * Unlike the other advice classes in this codebase, the fallback here
     * returns the raw exception message rather than a generic sentence —
     * preserved from the original generated behavior.
     * </p>
     */
    private String toFriendlyMessage(String message) {

        return VALIDATION_MAPPINGS.stream()
                .filter(mapping -> mapping.matches(message))
                .map(ValidationMapping::friendlyMessage)
                .findFirst()
                .orElse(message);
    }
}