// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.knowvera.subscription;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.knowvera.AuditTracker;
import bw.co.knowvera.PropertySearchOrder;
import bw.co.knowvera.SearchObject;
import bw.co.knowvera.logging.Audit;
import bw.co.knowvera.subscription.KycSubscriptionApi;
import bw.co.knowvera.subscription.KycSubscriptionDTO;
import bw.co.knowvera.subscription.KycSubscriptionService;
import bw.co.knowvera.subscription.SubscriptionSearchCriteria;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@Tag(name = "KYC Subscriptions", description = "Operations related to KYC subscriptions.")
public class KycSubscriptionApiImpl implements KycSubscriptionApi {
    
    private final KycSubscriptionService kycSubscriptionService;
    // private final KeycloakOrganisationService keycloakOrganisationService;

    public KycSubscriptionApiImpl(KycSubscriptionService kycSubscriptionService) {
        
        this.kycSubscriptionService = kycSubscriptionService;
    }

    @Override
    @Operation(summary = "Find KYC Subscription by ID", description = "Find a KYC subscription by its ID")
    @Audit(entity = "KYC_SUBSCRIPTION", eventLabel="#id", logData = false)
    public ResponseEntity<KycSubscriptionDTO> findById(String id) throws Exception {
        try {

            KycSubscriptionDTO subscription = kycSubscriptionService.findById(id);
            return ResponseEntity.ok(subscription);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    @Operation(summary = "Get All KYC Subscriptions", description = "Retrieve all KYC subscriptions")
    @Audit(entity = "KYC_SUBSCRIPTION", logData = false)
    public ResponseEntity<List<KycSubscriptionDTO>> getAll() throws Exception {
        try {
            List<KycSubscriptionDTO> subscriptions = kycSubscriptionService.getAll();
            return ResponseEntity.ok(subscriptions);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
 

    @Override
    @Operation(summary = "Get All KYC Subscriptions Paged", description = "Retrieve all KYC subscriptions with pagination") 
    @Audit(entity = "KYC_SUBSCRIPTION", logData = false)
    public ResponseEntity<Page<KycSubscriptionDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            Page<KycSubscriptionDTO> page = kycSubscriptionService.getAll(pageNumber, pageSize);
            return ResponseEntity.ok(page);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    @Operation(summary = "Paged Search KYC Subscriptions", description = "Search KYC subscriptions with pagination")
    @Audit(entity = "KYC_SUBSCRIPTION", logData = false)
    public ResponseEntity<Page<KycSubscriptionDTO>> pagedSearch(SearchObject<SubscriptionSearchCriteria> criteria) throws Exception {
        try {
            Page<KycSubscriptionDTO> page = kycSubscriptionService.search(criteria);

            return ResponseEntity.ok(page);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    @Operation(summary = "Remove KYC Subscription", description = "Remove a KYC subscription by its ID")
    @Audit(entity = "KYC_SUBSCRIPTION", eventLabel="#id", logData = false)
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(kycSubscriptionService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    @Operation(summary = "Save KYC Subscription", description = "Save a KYC subscription")
    @Audit(entity = "KYC_SUBSCRIPTION", eventLabel="#subscription.id", logData = true)
    public ResponseEntity<KycSubscriptionDTO> save(KycSubscriptionDTO subscription) throws Exception {

        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(subscription, authentication);

            return ResponseEntity.ok(kycSubscriptionService.save(subscription));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    @Operation(summary = "Search KYC Subscriptions", description = "Search KYC subscriptions based on criteria")
    @Audit(entity = "KYC_SUBSCRIPTION", logData = false)
    public ResponseEntity<List<KycSubscriptionDTO>> search(SearchObject<SubscriptionSearchCriteria> criteria) throws Exception {
        try {

            Set<PropertySearchOrder> sortOrders = new HashSet<>();
            if(criteria.getSortings() != null){
                sortOrders.addAll(criteria.getSortings());
            }
            
            List<KycSubscriptionDTO> subscriptions = kycSubscriptionService.search(criteria.getCriteria(), sortOrders);
            return ResponseEntity.ok(subscriptions);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    @Operation(summary = "Find KYC Subscriptions by Organisation", description = "Find KYC subscriptions by organisation ID")
    @Audit(entity = "KYC_SUBSCRIPTION", eventLabel="#arg0", logData = false)
    public ResponseEntity<List<KycSubscriptionDTO>> findByOrganisation(String arg0) throws Exception {
        
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            String username = "anonymousUser";
            if(authentication != null) {

                username = authentication.getName();
            }
            List<KycSubscriptionDTO> subscriptions = kycSubscriptionService.findByOrganisation(arg0, username);
            return ResponseEntity.ok(subscriptions);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }
}