// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycSubscriptionDTO } from '@models/bw/co/centralkyc/subscription/kyc-subscription-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class KycSubscriptionApi {

  protected path = '/subscription';

  private http = inject(HttpClient);

  public findById(id: string | any): Observable<KycSubscriptionDTO | any> {

    return this.http.get<KycSubscriptionDTO | any>(`${this.path}/${id}`);
  }

  public getAll(): Observable<KycSubscriptionDTO[] | any[]> {

    return this.http.get<KycSubscriptionDTO[] | any[]>(`${this.path}`);
  }

  public getAllPaged(pageNumber: number | any, pageSize: number | any): Observable<Page<KycSubscriptionDTO> | any> {

    return this.http.get<Page<KycSubscriptionDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public pagedSearch(criteria: string | any, pageNumber: number | any, pageSize: number | any): Observable<Page<KycSubscriptionDTO> | any> {

    return this.http.get<Page<KycSubscriptionDTO> | any>(`${this.path}/search/paged?criteria=${criteria}&pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public remove(id: string | any): Observable<boolean | any> {

    return this.http.delete<boolean | any>(`${this.path}/${id}`);
  }

  public save(subscription: KycSubscriptionDTO | any): Observable<KycSubscriptionDTO | any> {

    return this.http.post<KycSubscriptionDTO | any>(`${this.path}`, subscription);
  }

  public search(criteria: string | any): Observable<KycSubscriptionDTO[] | any[]> {

    return this.http.get<KycSubscriptionDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
  }

  public findByOrganisation(organisationId: string | any): Observable<KycSubscriptionDTO[] | any[]> {

    return this.http.get<KycSubscriptionDTO[] | any[]>(`${this.path}/by-organisation/${organisationId}`);
  }
}
