// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.kyc;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.PropertySearchOrder;
import bw.co.centralkyc.SearchObject;
import bw.co.centralkyc.SortOrder;
import bw.co.centralkyc.TargetEntity;
import bw.co.centralkyc.document.DocumentApi;
import bw.co.centralkyc.document.DocumentDTO;
import bw.co.centralkyc.individual.IndividualDTO;
import bw.co.centralkyc.individual.IndividualService;
import bw.co.centralkyc.keycloak.KeycloakOrganisationService;
import bw.co.centralkyc.keycloak.KeycloakUserService;
import bw.co.centralkyc.organisation.OrganisationDTO;
import bw.co.centralkyc.user.UserDTO;

import java.time.LocalDate;
import java.util.*;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.Strings;
import org.jspecify.annotations.Nullable;
import org.springframework.data.domain.Page;

@RestController
public class KycRecordApiImpl implements KycRecordApi {

    private final KycRecordService kycRecordService;
    private final KeycloakOrganisationService keycloakOrganisationService;
    private final KeycloakUserService keycloakUserService;
    private final IndividualService individualService;
    private final DocumentApi documentApi;

    public KycRecordApiImpl(KycRecordService kycRecordService,
            KeycloakOrganisationService keycloakOrganisationService,
            KeycloakUserService keycloakUserService,
            IndividualService individualService,
            DocumentApi documentApi) {

        this.kycRecordService = kycRecordService;
        this.keycloakOrganisationService = keycloakOrganisationService;
        this.keycloakUserService = keycloakUserService;
        this.individualService = individualService;
        this.documentApi = documentApi;
    }

    private void updateOrganisations(Collection<KycRecordDTO> records) {

        if (records == null || records.isEmpty()) {
            return;
        }

        for (KycRecordDTO record : records) {

            if (record.getTarget() == TargetEntity.ORGANISATION && record.getTargetId() != null) {

                try {

                    OrganisationDTO org = keycloakOrganisationService.findById(record.getTargetId());

                    if (org != null) {

                        // record.setName(org.getName());
                        // record.setIdentityNo(org.getRegistrationNo());
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

    }

    @Override
    public ResponseEntity<KycRecordDTO> findById(String id) throws Exception {

        try {

            KycRecordDTO record = kycRecordService.findById(id);
            updateOrganisations(List.of(record));

            return ResponseEntity.ok(record);

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordListDTO>> findByIdentityNo(String identityNo)
            throws Exception {

        try {
            Collection<KycRecordListDTO> records = kycRecordService.findByIdentityNo(identityNo);
            // updateOrganisations(records);
            return ResponseEntity.ok(records);

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordListDTO>> findByIndividual(String individualId)
            throws Exception {

        try {
            Collection<KycRecordListDTO> records = kycRecordService.findByIndividual(individualId);
            // updateOrganisations(records);
            return ResponseEntity.ok(records);

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordListDTO>> getAll() throws Exception {

        try {
            Collection<KycRecordListDTO> records = kycRecordService.getAll();
            // updateOrganisations(records);
            return ResponseEntity.ok(records);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordListDTO>> getAllPaged(Integer pageNumber, Integer pageSize)
            throws Exception {

        try {
            Page<KycRecordListDTO> records = kycRecordService.getAll(pageNumber, pageSize);
            // updateOrganisations(records.getContent());
            return ResponseEntity.ok(records);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordListDTO>> pagedSearch(SearchObject<KycRecordSearchCriteria> criteria)
            throws Exception {

        try {
            Page<KycRecordListDTO> records = kycRecordService.search(criteria);
            // updateOrganisations(records.getContent());
            return ResponseEntity.ok(records);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {

            return ResponseEntity.ok(kycRecordService.remove(id));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> save(KycRecordDTO kycRecord) throws Exception {
        try {

            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(kycRecord, authentication);

            KycRecordDTO savedRecord = kycRecordService.save(kycRecord);
            updateOrganisations(List.of(savedRecord));
            return ResponseEntity.ok(savedRecord);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordListDTO>> search(KycRecordSearchCriteria criteria) throws Exception {
        try {

            Collection<KycRecordListDTO> records = kycRecordService.search(criteria, Set.<PropertySearchOrder>of());
            // updateOrganisations(records);

            return ResponseEntity.ok(records);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordListDTO>> findByIdentityNoPaged(String identityNo, Integer pageNumber,
            Integer pageSize) throws Exception {

        try {

            Page<KycRecordListDTO> records = kycRecordService.findByIdentityNo(identityNo, pageNumber, pageSize);
            // updateOrganisations(records.getContent());
            return ResponseEntity.ok(records);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordListDTO>> findByIndividualPaged(String individualId, Integer pageNumber,
            Integer pageSize) throws Exception {

        try {
            Page<KycRecordListDTO> records = kycRecordService.findByIndividual(individualId, pageNumber, pageSize);
            // updateOrganisations(records.getContent());
            return ResponseEntity.ok(records);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordListDTO>> findByOrganisation(String organisationId) throws Exception {

        try {
            Collection<KycRecordListDTO> records = kycRecordService.findByOrganisation(organisationId);
            // updateOrganisations(records);
            return ResponseEntity.ok(records);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordListDTO>> findByOrganisationRegistration(String registrationNo)
            throws Exception {

        try {

            OrganisationDTO org = keycloakOrganisationService.findByRegistrationNo(registrationNo);

            if (org == null) {
                throw new Exception("Organisation not found for registration no: " + registrationNo);
            }

            Collection<KycRecordListDTO> records = kycRecordService.findByOrganisation(org.getId());
            // updateOrganisations(records);

            return ResponseEntity.ok(records);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordListDTO>> findByOrganisationRegistrationPaged(String registrationNo,
            Integer pageNumber, Integer pageSize) throws Exception {

        try {
            OrganisationDTO org = keycloakOrganisationService.findByRegistrationNo(registrationNo);

            if (org == null) {
                throw new Exception("Organisation not found for registration no: " + registrationNo);
            }

            Page<KycRecordListDTO> records = kycRecordService.findByOrganisation(org.getId(), pageNumber, pageSize);
            // updateOrganisations(records.getContent());

            return ResponseEntity.ok(records);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> createIndividualRecord(String individualId) throws Exception {

        try {

            String username = "anonymousUser";
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication != null) {

                username = authentication.getName();
            }

            KycRecordDTO record = kycRecordService.createTargetRecord(individualId, TargetEntity.INDIVIDUAL, username);
            updateOrganisations(List.of(record));

            return ResponseEntity.ok(record);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> createOrganisationRecord(String organisationId) throws Exception {

        try {

            String username = "anonymousUser";
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication != null) {

                username = authentication.getName();
            }

            KycRecordDTO record = kycRecordService.createTargetRecord(organisationId, TargetEntity.ORGANISATION,
                    username);
            updateOrganisations(List.of(record));

            return ResponseEntity.ok(record);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> findMyCurrentRecord(TargetEntity ownerType) throws Exception {

        try {
            String username = "anonymousUser";
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication != null) {

                username = authentication.getName();
            }

            UserDTO user = keycloakUserService.findByUsername(username);
            IndividualDTO individual = individualService.findByUserId(user.getUserId());

            if (individual == null || StringUtils.isBlank(individual.getId())) {

                throw new Exception("No individual or organisation associated with user: " + username);
            }

            KycRecordDTO current = kycRecordService.findLatestValidForOwner(individual.getId(), ownerType,
                    LocalDate.now());

            return ResponseEntity
                    .ok(current);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    private KycRecordSearchCriteria buildSearchCriteriaForCurrentUser() throws Exception {

        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || !authentication.isAuthenticated()) {

            throw new KycRecordServiceException("User is not authenticated");
        }

        Jwt jwt = (Jwt) authentication.getPrincipal();

        UserDTO user = keycloakUserService.findUserById(jwt.getSubject());

        List<String> targetIds = new ArrayList<>();

        if (StringUtils.isNotBlank(user.getOrganisationId())) {

            targetIds.add(user.getOrganisationId());
        }

        IndividualDTO individual = individualService.findByUserId(user.getUserId());

        if (individual != null && StringUtils.isNotBlank(individual.getId())) {

            targetIds.add(individual.getId());
        }

        KycRecordSearchCriteria criteria = new KycRecordSearchCriteria();
        criteria.setTargetIds(targetIds);

        return criteria;
    }

    @Override
    public ResponseEntity<Collection<KycRecordListDTO>> findMyRecords() throws Exception {

        try {

            KycRecordSearchCriteria criteria = buildSearchCriteriaForCurrentUser();

            Collection<KycRecordListDTO> records = kycRecordService.search(criteria, Set.<PropertySearchOrder>of());
            // updateOrganisations(records);

            return ResponseEntity.ok(records);

        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> createNew(KycRecordDTO record,
            List<MultipartFile> files) throws Exception {

        if (record != null && StringUtils.isNotBlank(record.getId())) {

            throw new KycRecordServiceException("This is an existing record.");
        }

        try {

            String username = "anonymousUser";
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication != null) {

                username = authentication.getName();
            }

            // Keep a record of the incoming documents to preserve sequence
            List<DocumentDTO> docs = record.getDocuments();

            AuditTracker.auditTrail(record, authentication);

            docs.forEach(d -> {
                AuditTracker.auditTrail(d, authentication);
                d.setTarget(TargetEntity.KYC_RECORD);
                d.setTargetId(record.getId());
            });

            // Save the record first to generate IDs for documents, then upload files and
            // update document records with file info
            KycRecordDTO createdRecord = kycRecordService.createNew(record, username);

            if (files != null) {
                for (int i = 0; i < files.size(); i++) {

                    DocumentDTO doc = docs.get(i);
                    DocumentDTO savedDoc = createdRecord.getDocuments().stream()
                            .filter(d -> Strings.CS.equals(d.getDocumentTypeId(), doc.getDocumentTypeId()))
                            .findFirst()
                            .orElseThrow(() -> new Exception(
                                    "Document not found in created record for file: " + doc.getFileName()));
                    ResponseEntity<DocumentDTO> uploadResponse = documentApi
                            .updateDocument(savedDoc.getId(), files.get(i));

                    if (uploadResponse == null || uploadResponse.getBody() == null
                            || uploadResponse.getStatusCode().isError()) {

                        throw new Exception("Failed to upload document: " + doc.getFileName());
                    }

                    DocumentDTO uploaded = uploadResponse.getBody();

                    if (StringUtils.isBlank(doc.getId())) {
                        doc.setId(uploaded.getId());
                        doc.setCreatedAt(uploaded.getCreatedAt());
                        doc.setModifiedAt(uploaded.getModifiedAt());
                    }

                    doc.setModifiedAt(uploaded.getModifiedAt());
                    doc.setModifiedBy(uploaded.getModifiedBy());
                    doc.setFileContent(uploaded.getFileContent());
                    doc.setMetadata(uploaded.getMetadata());
                    doc.setUrl(uploaded.getUrl());
                    doc.setFileName(uploaded.getFileName());

                }
            }

            createdRecord.setDocuments(docs);
            return ResponseEntity.ok(createdRecord);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> removeRecordFile(String id, @Nullable String documentId) throws Exception {
        try {

            DocumentDTO doc = documentApi.findById(documentId).getBody();
            if (doc == null) {
                throw new Exception("Document not found for id: " + documentId);
            }

            if (doc.getTarget() != TargetEntity.KYC_RECORD) {
                throw new Exception("Document with id: " + documentId + " is not associated with a KYC record");
            }

            KycRecordDTO record = kycRecordService.removeRecordFile(id, documentId);

            documentApi.remove(documentId);

            return ResponseEntity.ok(record);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> updateRecordFiles(String id, List<DocumentDTO> documents,
            List<MultipartFile> files) throws Exception {
        try {

            // Ensure all documents are associated with the record and have valid targets before proceeding with uploads
            documents.forEach(doc -> {

                if(doc.getTarget() != null && doc.getTarget() != TargetEntity.KYC_RECORD) {
                    throw new RuntimeException("Document with id: " + doc.getId() + " is not associated with a KYC record");
                }   

                if(StringUtils.isNotBlank(doc.getTargetId()) && !doc.getTargetId().equals(id)) {

                    throw new RuntimeException("Document with id: " + doc.getId() + " is not associated with KYC record with id: " + id);
                }

            });

            List<DocumentDTO> saved = new ArrayList<>();
            // KycRecordDTO record = kycRecordService.findById(id);

            if (files != null) {
                for (int i = 0; i < files.size(); i++) {

                    DocumentDTO doc = documents.get(i);

                    if (StringUtils.isBlank(doc.getId())) {

                        DocumentDTO created = documentApi
                                .upload(TargetEntity.KYC_RECORD, id, doc.getDocumentTypeId(), id, files.get(i))
                                .getBody();
                        saved.add(created);
                    } else {

                        DocumentDTO updated = documentApi.updateDocument(doc.getId(), files.get(i)).getBody();
                        saved.add(updated);
                    }
                }
            }

            KycRecordDTO updatedRecord = kycRecordService.updateRecordFiles(id, saved);

            return ResponseEntity.ok(updatedRecord);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public @Nullable ResponseEntity<Page<KycRecordListDTO>> findMyRecordsPaged(@Nullable Integer pageNumber,
            @Nullable Integer pageSize) throws Exception {

        KycRecordSearchCriteria criteria = buildSearchCriteriaForCurrentUser();

        SearchObject<KycRecordSearchCriteria> searchObject = new SearchObject<>();
        searchObject.setCriteria(criteria);
        searchObject.setPageNumber(pageNumber);
        searchObject.setPageSize(pageSize);

        Collection<PropertySearchOrder> sortings = new HashSet<>();
        sortings.add(new PropertySearchOrder("uploadDate", SortOrder.DESC));

        searchObject.setSortings(sortings);

        Page<KycRecordListDTO> records = kycRecordService.search(searchObject);
        // updateOrganisations(records.getContent());

        return ResponseEntity.ok(records);

    }

    @Override
    public ResponseEntity<KycRecordSummary> findSummaryById(String id) throws Exception {
        
        try {

            KycRecordSummary summary = kycRecordService.findSummaryById(id);

            return ResponseEntity.ok(summary);

        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> runVerification(String id) throws Exception {
        
        try {

            String username = "anonymousUser";
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication != null) {

                username = authentication.getName();
            }
            
            KycRecordDTO record = kycRecordService.runVerification(id, username);

            return ResponseEntity.ok(record);

        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }
}
