// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::contact::ContactIntent
 */
export enum ContactIntent {
    /** TODO: Model Documentation for Enumeration Literal VERIFICATION_STATUS value "VERIFICATION_STATUS": $literal.enumerationLiteralDisplay */
    VERIFICATION_STATUS = "VERIFICATION_STATUS",
    /** TODO: Model Documentation for Enumeration Literal DOCUMENT_REJECTED value "DOCUMENT_REJECTED": $literal.enumerationLiteralDisplay */
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED",
    /** TODO: Model Documentation for Enumeration Literal UPLOAD_PROBLEM value "UPLOAD_PROBLEM": $literal.enumerationLiteralDisplay */
    UPLOAD_PROBLEM = "UPLOAD_PROBLEM",
    /** TODO: Model Documentation for Enumeration Literal VERIFICATION_DELAY value "VERIFICATION_DELAY": $literal.enumerationLiteralDisplay */
    VERIFICATION_DELAY = "VERIFICATION_DELAY",
    /** TODO: Model Documentation for Enumeration Literal ACCOUNT_LOCKED value "ACCOUNT_LOCKED": $literal.enumerationLiteralDisplay */
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
    /** TODO: Model Documentation for Enumeration Literal UPDATE_INFORMATION value "UPDATE_INFORMATION": $literal.enumerationLiteralDisplay */
    UPDATE_INFORMATION = "UPDATE_INFORMATION",
    /** TODO: Model Documentation for Enumeration Literal RESUBMIT_DOCUMENTS value "RESUBMIT_DOCUMENTS": $literal.enumerationLiteralDisplay */
    RESUBMIT_DOCUMENTS = "RESUBMIT_DOCUMENTS",
    /** TODO: Model Documentation for Enumeration Literal TECHNICAL_PROBLEM value "TECHNICAL_PROBLEM": $literal.enumerationLiteralDisplay */
    TECHNICAL_PROBLEM = "TECHNICAL_PROBLEM",
    /** TODO: Model Documentation for Enumeration Literal KYC_PROCESS_QUESTION value "KYC_PROCESS_QUESTION": $literal.enumerationLiteralDisplay */
    KYC_PROCESS_QUESTION = "KYC_PROCESS_QUESTION",
    /** TODO: Model Documentation for Enumeration Literal VERIFICATION_APPROVED value "VERIFICATION_APPROVED": $literal.enumerationLiteralDisplay */
    VERIFICATION_APPROVED = "VERIFICATION_APPROVED",
    /** TODO: Model Documentation for Enumeration Literal DATA_PRIVACY_CONCERN value "DATA_PRIVACY_CONCERN": $literal.enumerationLiteralDisplay */
    DATA_PRIVACY_CONCERN = "DATA_PRIVACY_CONCERN",
    /** TODO: Model Documentation for Enumeration Literal IDENTITY_THEFT_REPORT value "IDENTITY_THEFT_REPORT": $literal.enumerationLiteralDisplay */
    IDENTITY_THEFT_REPORT = "IDENTITY_THEFT_REPORT",
    /** TODO: Model Documentation for Enumeration Literal TRANSACTION_BLOCKED value "TRANSACTION_BLOCKED": $literal.enumerationLiteralDisplay */
    TRANSACTION_BLOCKED = "TRANSACTION_BLOCKED",
    /** TODO: Model Documentation for Enumeration Literal KYB_VERIFICATION value "KYB_VERIFICATION": $literal.enumerationLiteralDisplay */
    KYB_VERIFICATION = "KYB_VERIFICATION",
    /** TODO: Model Documentation for Enumeration Literal GENERAL_SUPPORT value "GENERAL_SUPPORT": $literal.enumerationLiteralDisplay */
    GENERAL_SUPPORT = "GENERAL_SUPPORT"
}
