// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::contact::ContactSentiment
 */
export enum ContactSentiment {
    /** TODO: Model Documentation for Enumeration Literal POSITIVE value "POSITIVE": $literal.enumerationLiteralDisplay */
    POSITIVE = "POSITIVE",
    /** TODO: Model Documentation for Enumeration Literal NEUTRAL value "NEUTRAL": $literal.enumerationLiteralDisplay */
    NEUTRAL = "NEUTRAL",
    /** TODO: Model Documentation for Enumeration Literal NEGATIVE value "NEGATIVE": $literal.enumerationLiteralDisplay */
    NEGATIVE = "NEGATIVE",
    /** TODO: Model Documentation for Enumeration Literal CONFUSED value "CONFUSED": $literal.enumerationLiteralDisplay */
    CONFUSED = "CONFUSED",
    /** TODO: Model Documentation for Enumeration Literal SUSPICIOUS value "SUSPICIOUS": $literal.enumerationLiteralDisplay */
    SUSPICIOUS = "SUSPICIOUS"
}
