// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by controller-advice.java.vsl in andromda-spring-cartridge. Do not modify by hand!.
//
package bw.co.knowvera.user;

import bw.co.knowvera.ErrorResponse;
import java.time.Instant;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Translates the errors thrown by {@link UserApiServiceBase}
 * into human-readable API responses for the userApi endpoints.
 *
 * Scoped to {@link UserApi} only, and ordered ahead
 * of global exception handlers so that this advice's friendlier messages take precedence.
 */
@RestControllerAdvice(assignableTypes = UserApi.class)
@Order(Ordered.HIGHEST_PRECEDENCE)
public class UserApiControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(UserApiControllerAdvice.class);

    /**
     * Handles manual argument validation checks thrown by UserApiServiceBase.
     * Maps generated validation messages to friendly human-readable descriptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ErrorResponse> handleIllegalArgument(IllegalArgumentException ex) {
        String message = ex.getMessage() == null ? "" : ex.getMessage();
        String friendly = toFriendlyMessage(message);

        LOGGER.warn("UserApi validation failed: {}", message);

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.BAD_REQUEST.value(),
                HttpStatus.BAD_REQUEST.name(),
                friendly,
                Arrays.asList(ex.getMessage()),
                Instant.now()
        );

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(errorResponse);
    }


    /**
     * Maps validation messages thrown by UserApiServiceBase to plain-language equivalents.
     */
    private String toFriendlyMessage(String message) {
        if (message.contains(".saveUser(") && message.contains("'user'")) {
            return "User is required.";
        }

        if (message.contains(".updateUserName(") && message.contains("'userId'")) {
            return "User Id is required.";
        }

        if (message.contains(".updateUserName(") && message.contains("'username'")) {
            return "Username is required.";
        }

        if (message.contains(".addClientRoles(") && message.contains("'clientId'")) {
            return "Client Id is required.";
        }

        if (message.contains(".addClientRoles(") && message.contains("'userId'")) {
            return "User Id is required.";
        }

        if (message.contains(".findUserById(") && message.contains("'userId'")) {
            return "User Id is required.";
        }

        if (message.contains(".changePassword(") && message.contains("'userId'")) {
            return "User Id is required.";
        }

        if (message.contains(".changePassword(") && message.contains("'newPassword'")) {
            return "New Password is required.";
        }

        if (message.contains(".findByClientRoles(") && message.contains("'clientId'")) {
            return "Client Id is required.";
        }

        if (message.contains(".addRole(") && message.contains("'userId'")) {
            return "User Id is required.";
        }

        if (message.contains(".addRole(") && message.contains("'role'")) {
            return "Role is required.";
        }

        if (message.contains(".findByOrganisationName(") && message.contains("'organisation'")) {
            return "Organisation is required.";
        }

        if (message.contains(".findByBranchName(") && message.contains("'branch'")) {
            return "Branch is required.";
        }


        // Fallback for any unmapped validation message
        return message;
    }
}