// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.knowvera.user;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import bw.co.knowvera.keycloak.KeycloakUserService;
import bw.co.knowvera.user.UserApi;
import bw.co.knowvera.user.UserDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@Tag(name = "Users", description = "Operations related to users.")
public class UserApiImpl implements UserApi {

    protected Logger logger = LoggerFactory.getLogger(UserApiImpl.class);    

    private final KeycloakUserService keycloakUserService;

    public UserApiImpl(KeycloakUserService keycloakUserService) {

        this.keycloakUserService = keycloakUserService;
    }

    @Override
    @Operation(summary = "Add Client Roles", description = "Add roles to a user for a specific client")
    public ResponseEntity<UserDTO> addClientRoles(
            String clientId, Set<String> roles, String userId) {
        try {
            logger.debug(
                    "Add user/client roles with client Id " + clientId + ",roles " + roles
                            + " and user Id " + userId);
            UserDTO rep = this.keycloakUserService.addClientRoles(clientId, roles, userId);
            return ResponseEntity.ok(rep);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Add Role", description = "Add a role to a user")
    public ResponseEntity<Boolean> addRole(String userId,
            String role) {

        try {
            
            return ResponseEntity.ok(this.keycloakUserService.updateUserRoles(userId, role, 1));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Change Password", description = "Change the password of a user")
    public ResponseEntity<String> changePassword(String userId,
            String newPassword) {
        try {
            
            this.keycloakUserService.updateUserPassword(userId, newPassword);
            return ResponseEntity.ok(true ? "Password changed successfully" : "Failed to change password.");

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Find Users by Client Roles", description = "Find users by their roles for a specific client")
    public ResponseEntity<List<UserDTO>> findByClientRoles(
            Set<String> roles, String clientId) {
        try {

            List<UserDTO> data = this.keycloakUserService.getUsersByClientRoles(clientId, roles).stream().toList();

            return ResponseEntity.ok(data);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Find Users by Realm Roles", description = "Find users by their roles for the realm")
    public ResponseEntity<List<UserDTO>> findByRealmRoles(
            Set<String> roles) {
        try {
            List<UserDTO> data = this.keycloakUserService.getUsersByRealmRoles(roles).stream().toList();
            return ResponseEntity.ok(data);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Find User by ID", description = "Find a user by their ID")
    public ResponseEntity<UserDTO> findUserById(String userId) {
        try {
            logger.debug("Search user by Id " + userId);
            UserDTO rep = this.keycloakUserService.findUserById(userId);
            return ResponseEntity.ok(rep);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Load All Users", description = "Load all users from the system")
    public ResponseEntity<List<UserDTO>> loadUsers() {
        try {
            
            List<UserDTO> data = this.keycloakUserService.findAll().stream().toList();
            return ResponseEntity.ok(data);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Remove Role", description = "Remove a role from a user")
    public ResponseEntity<Boolean> removeRole(String userId,
            String role) {
        try {
            Boolean responseData = this.keycloakUserService.updateUserRoles(userId, role, -1);
            return ResponseEntity.ok(responseData);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    @Operation(summary = "Save User", description = "Save a user")
    public ResponseEntity<UserDTO> saveUser(
            UserDTO user) {
        try {
            logger.debug("Save User " + user);

            if (StringUtils.isBlank(user.getUserId()))
                user = this.keycloakUserService.createUser(user);
            else {
                keycloakUserService.updateUser(user);
            }

            return ResponseEntity.ok(user);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Search Users", description = "Search users based on criteria")
    public ResponseEntity<List<UserDTO>> search(String criteria) {
        try {
            
            logger.debug("Search user by criteria" + criteria);

            List<UserDTO> users = this.keycloakUserService.search(criteria);

            return ResponseEntity.ok(users);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Update User Name", description = "Update the username of a user")
    public ResponseEntity<Boolean> updateUserName(String userId,
            String username) {
        try {
            
            Optional<Boolean> data = Optional.empty(); // TODO: Add custom code here;
            return ResponseEntity.ok(data.get());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Find Users by Branch ID", description = "Find users by their branch ID")
    public ResponseEntity<List<UserDTO>> findByBranchId(String branchId) {

        try {
            
            List<UserDTO> data = this.keycloakUserService.getBranchUsers(branchId).stream().toList();
            return ResponseEntity.ok(data);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Find Users by Branch Name", description = "Find users by their branch name")
    public ResponseEntity<List<UserDTO>> findByBranchName(String branch) {

        try {
            
            Optional<List<UserDTO>> data = Optional.empty(); // TODO: Add custom code here;
            return ResponseEntity.ok(data.get());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Find Users by Organisation ID", description = "Find users by their organisation ID")
    public ResponseEntity<List<UserDTO>> findByOrganisationId(String organisationId) {

        try {
            List<UserDTO> data = this.keycloakUserService.getOrganisationUsers(organisationId).stream().toList();
            return ResponseEntity.ok(data);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Find Users by Organisation Name", description = "Find users by their organisation name")
    public ResponseEntity<List<UserDTO>> findByOrganisationName(String organisation) {


        try {
            
            Optional<List<UserDTO>> data = Optional.empty(); // TODO: Add custom code here;
            return ResponseEntity.ok(data.get());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    @Operation(summary = "Find User by Identity No", description = "Find a user by their identity number")
    public ResponseEntity<UserDTO> findByIdentityNo(String identityNo) {

        try {
            return ResponseEntity.ok(this.keycloakUserService.getUserByIdentityNo(identityNo));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }
}