// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.knowvera::contact::ContactType
 */
export enum ContactType {
    /** TODO: Model Documentation for Enumeration Literal ENQUIRY value "ENQUIRY": $literal.enumerationLiteralDisplay */
    ENQUIRY = "ENQUIRY",
    /** TODO: Model Documentation for Enumeration Literal COMMENT value "COMMENT": $literal.enumerationLiteralDisplay */
    COMMENT = "COMMENT",
    /** TODO: Model Documentation for Enumeration Literal COMPLAINT value "COMPLAINT": $literal.enumerationLiteralDisplay */
    COMPLAINT = "COMPLAINT"
}
