// license-header java merge-point
//
// Attention: Partially Generated code! Can be modified by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.document.type.verification;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.centralkyc.AuditTracker;

@RestController
@Tag(name = "Document Type", description = "Managing document types.")
public class VerificationDataConfigApiImpl implements VerificationDataConfigApi {

    private static final Logger logger = LoggerFactory.getLogger(VerificationDataConfigApiImpl.class);
        protected final VerificationDataConfigService verificationDataConfigService;
    
    public VerificationDataConfigApiImpl(
        VerificationDataConfigService verificationDataConfigService    ) {
        
        this.verificationDataConfigService = verificationDataConfigService;
    }



    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<VerificationDataConfigDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new Exception(e.getCause()) : e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new Exception(e.getCause()) : e;
        } 
    }


    @Override
    public ResponseEntity<VerificationDataConfigDTO> save(@Valid VerificationDataConfigDTO verificationDataConfig) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(verificationDataConfig, authentication);
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            logger.error("An error occurred while processing the request", e);
            throw e.getCause() != null ? new Exception(e.getCause()) : e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return verificationDataConfigService
     */
    protected VerificationDataConfigService getVerificationDataConfigService()
    {
        return this.verificationDataConfigService;
    }
}