// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by controller-advice.java.vsl in andromda-spring-cartridge. Do not modify by hand!.
//
package bw.co.knowvera.document;

import bw.co.knowvera.ErrorResponse;
import java.time.Instant;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Translates the errors thrown by {@link DocumentApiServiceBase}
 * into human-readable API responses for the documentApi endpoints.
 *
 * Scoped to {@link DocumentApi} only, and ordered ahead
 * of global exception handlers so that this advice's friendlier messages take precedence.
 */
@RestControllerAdvice(assignableTypes = DocumentApi.class)
@Order(Ordered.HIGHEST_PRECEDENCE)
public class DocumentApiControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(DocumentApiControllerAdvice.class);

    /**
     * Handles manual argument validation checks thrown by DocumentApiServiceBase.
     * Maps generated validation messages to friendly human-readable descriptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ErrorResponse> handleIllegalArgument(IllegalArgumentException ex) {
        String message = ex.getMessage() == null ? "" : ex.getMessage();
        String friendly = toFriendlyMessage(message);

        LOGGER.warn("DocumentApi validation failed: {}", message);

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.BAD_REQUEST.value(),
                HttpStatus.BAD_REQUEST.name(),
                friendly,
                Arrays.asList(ex.getMessage()),
                Instant.now()
        );

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(errorResponse);
    }

    /**
     * Handles {@link DocumentServiceException} thrown by referenced services.
     */
    @ExceptionHandler(DocumentServiceException.class)
    public ResponseEntity<ErrorResponse> handleDocumentServiceException(DocumentServiceException ex) {
        LOGGER.error("Referenced service error (DocumentService)", ex);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ErrorResponse(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        HttpStatus.INTERNAL_SERVER_ERROR.name(),
                        "An error occurred while communicating with dependent services. Please try again shortly.",
                        null,
                        Instant.now()
                ));
    }

    /**
     * Maps validation messages thrown by DocumentApiServiceBase to plain-language equivalents.
     */
    private String toFriendlyMessage(String message) {
        if (message.contains(".findById(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".save(") && message.contains("'document'")) {
            return "Document is required.";
        }

        if (message.contains(".remove(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".search(") && message.contains("'criteria'")) {
            return "Criteria is required.";
        }

        if (message.contains(".findByDocumentType(") && message.contains("'documentTypeId'")) {
            return "Document Type Id is required.";
        }

        if (message.contains(".upload(") && message.contains("'target'")) {
            return "Target is required.";
        }

        if (message.contains(".upload(") && message.contains("'targetId'")) {
            return "Target Id is required.";
        }

        if (message.contains(".upload(") && message.contains("'documentTypeId'")) {
            return "Document Type Id is required.";
        }

        if (message.contains(".upload(") && message.contains("'file'")) {
            return "File is required.";
        }

        if (message.contains(".findByTarget(") && message.contains("'target'")) {
            return "Target is required.";
        }

        if (message.contains(".findByTarget(") && message.contains("'targetId'")) {
            return "Target Id is required.";
        }

        if (message.contains(".downloadFile(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".downloadFileByUrl(") && message.contains("'objectName'")) {
            return "Object Name is required.";
        }

        if (message.contains(".updateDocument(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".updateDocument(") && message.contains("'file'")) {
            return "File is required.";
        }

        if (message.contains(".searchPaged(") && message.contains("'criteria'")) {
            return "Criteria is required.";
        }

        if (message.contains(".findMyDocuments(") && message.contains("'target'")) {
            return "Target is required.";
        }

        if (message.contains(".findMyDocumentsPaged(") && message.contains("'target'")) {
            return "Target is required.";
        }

        if (message.contains(".updateFileContent(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".updateFileContent(") && message.contains("'content'")) {
            return "Content is required.";
        }

        if (message.contains(".verifyData(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".analyseDocument(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".updateVerificationStatus(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".updateVerificationStatus(") && message.contains("'verificationStatus'")) {
            return "Verification Status is required.";
        }

        if (message.contains(".textExtration(") && message.contains("'id'")) {
            return "Id is required.";
        }


        // Fallback for any unmapped validation message
        return message;
    }
}