// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.kyvera::individual::PepStatus
 */
export enum PepStatus {
    /** TODO: Model Documentation for Enumeration Literal NOT_PEP value "NOT_PEP": $literal.enumerationLiteralDisplay */
    NOT_PEP = "NOT_PEP",
    /** TODO: Model Documentation for Enumeration Literal PEP_SELF value "PEP_SELF": $literal.enumerationLiteralDisplay */
    PEP_SELF = "PEP_SELF",
    /** TODO: Model Documentation for Enumeration Literal PEP_RELATIVE value "PEP_RELATIVE": $literal.enumerationLiteralDisplay */
    PEP_RELATIVE = "PEP_RELATIVE",
    /** TODO: Model Documentation for Enumeration Literal PEP_ASSOCIATE value "PEP_ASSOCIATE": $literal.enumerationLiteralDisplay */
    PEP_ASSOCIATE = "PEP_ASSOCIATE"
}
