// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { DocumentController } from '@controllers/document/document-controller';

@Injectable()
export class DocumentControllerImpl extends DocumentController {

    constructor() {
        super();
    }

}
