// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycSubscriptionDTO } from '@models/bw/co/centralkyc/subscription/kyc-subscription-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';
import { SubscriptionSearchCriteria } from '@app/models/bw/co/centralkyc/subscription/subscription-search-criteria';

@Injectable({
  providedIn: 'root'
})
export class KycSubscriptionApi {

    protected path = '/subscription';

    private http = inject(HttpClient);

    public findById(id: string): Observable<KycSubscriptionDTO> {

        return this.http.get<KycSubscriptionDTO>(`${this.path}/${id}`);
    }

    public findByOrganisation(organisationId: string): Observable<KycSubscriptionDTO[]> {

        return this.http.get<KycSubscriptionDTO[]>(`${this.path}/by-organisation/${organisationId}`);
    }

    public getAll(): Observable<KycSubscriptionDTO[]> {

        return this.http.get<KycSubscriptionDTO[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number, pageSize: number): Observable<Page<KycSubscriptionDTO>> {

        return this.http.get<Page<KycSubscriptionDTO>>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: SearchObject<SubscriptionSearchCriteria>): Observable<Page<KycSubscriptionDTO>> {

        return this.http.post<Page<KycSubscriptionDTO>>(`${this.path}/search/paged`, criteria);
    }

    public remove(id: string): Observable<boolean> {

        return this.http.delete<boolean>(`${this.path}/${id}`);
    }

    public save(subscription: KycSubscriptionDTO): Observable<KycSubscriptionDTO> {

        return this.http.post<KycSubscriptionDTO>(`${this.path}`, subscription);
    }

    public search(criteria: SearchObject<SubscriptionSearchCriteria>): Observable<KycSubscriptionDTO[]> {

        return this.http.post<KycSubscriptionDTO[]>(`${this.path}/search`, criteria);
    }

}
