// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.kyvera::invoice::UploadPurpose
 */
export enum UploadPurpose {
    /** TODO: Model Documentation for Enumeration Literal INVOICE value "INVOICE": $literal.enumerationLiteralDisplay */
    INVOICE = "INVOICE",
    /** TODO: Model Documentation for Enumeration Literal PAYMENT value "PAYMENT": $literal.enumerationLiteralDisplay */
    PAYMENT = "PAYMENT"
}
