// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.settings;

import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityNotFoundException;

/**
 * @see SalaryRange
 */
@Repository("salaryRangeDao")
public class SalaryRangeDaoImpl
    extends SalaryRangeDaoBase
{
    
    public SalaryRangeDaoImpl(
        SettingsRepository settingsRepository,
        SalaryRangeRepository salaryRangeRepository
    ) {

        super(
            settingsRepository,
            salaryRangeRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toSalaryRangeDTO(
        SalaryRange source,
        SalaryRangeDTO target)
    {
        // TODO verify behavior of toSalaryRangeDTO
        super.toSalaryRangeDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRangeDTO toSalaryRangeDTO(final SalaryRange entity)
    {
        // TODO verify behavior of toSalaryRangeDTO
        return super.toSalaryRangeDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private SalaryRange loadSalaryRangeFromSalaryRangeDTO(SalaryRangeDTO salaryRangeDTO)
    {
        if (salaryRangeDTO.getId() == null)
        {
            return  SalaryRange.Factory.newInstance();
        }
        else
        {
            return this.salaryRangeRepository.findById(salaryRangeDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + salaryRangeDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public SalaryRange salaryRangeDTOToEntity(SalaryRangeDTO salaryRangeDTO)
    {
        // TODO verify behavior of salaryRangeDTOToEntity
        SalaryRange entity = this.loadSalaryRangeFromSalaryRangeDTO(salaryRangeDTO);
        this.salaryRangeDTOToEntity(salaryRangeDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void salaryRangeDTOToEntity(
        SalaryRangeDTO source,
        SalaryRange target,
        boolean copyIfNull)
    {
        // TODO verify behavior of salaryRangeDTOToEntity
        super.salaryRangeDTOToEntity(source, target, copyIfNull);
    }
}