// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.settings;

import bw.co.centralkyc.document.DocumentMapper;
import bw.co.centralkyc.document.type.DocumentTypeMapper;
import bw.co.centralkyc.document.type.field.ExpectedFieldMapper;
import bw.co.centralkyc.settings.kyc.GroupFieldMapper;
import bw.co.centralkyc.settings.kyc.KycFieldGroupMapper;
import bw.co.centralkyc.utils.MappingUtils;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        DocumentTypeMapper.class,
        DocumentMapper.class,
        SalaryRangeMapper.class,
        ExpectedFieldMapper.class,
        KycFieldGroupMapper.class,
        GroupFieldMapper.class,
        ToolSelectorMapper.class,
        MappingUtils.class
    }
)
public abstract class SettingsMapper {
    
    /**
     * Converts this entity to an object of type {@link SettingsDTO}.
     * @param entity
     * @return SettingsDTO
     */
    @Mapping(source = "organisationDocuments", target = "organisationDocuments")
    @Mapping(source = "individualDocuments", target = "individualDocuments")
    @Mapping(source = "indKycDocuments", target = "indKycDocuments")
    @Mapping(source = "orgKycDocuments", target = "orgKycDocuments")
    @Mapping(source = "invoiceDocumentType", target = "invoiceDocumentType")
    @Mapping(source = "invoiceTemplate", target = "invoiceTemplate")
    @Mapping(source = "invoiceTemplateType", target = "invoiceTemplateType")
    @Mapping(source = "quotationDocumentType", target = "quotationDocumentType")
    @Mapping(source = "quotationTemplateType", target = "quotationTemplateType")
    @Mapping(source = "quotationTemplate", target = "quotationTemplate")
    @Mapping(source = "clientRequestFileType", target = "clientRequestFileType")
    @Mapping(source = "salaryRanges", target = "salaryRanges")
    @Mapping(source = "individualKycFieldGroups", target = "individualKycFieldGroups")
    @Mapping(source = "organisationKycFieldGroups", target = "organisationKycFieldGroups")
    @Mapping(source = "documentConfirmationTools", target = "documentConfirmationTools")
    @Mapping(source = "textProcessingTools", target = "textProcessingTools")
    @Mapping(source = "textCleanupTools", target = "textCleanupTools")
    @Mapping(source = "textExtractionTools", target = "textExtractionTools")
    public abstract SettingsDTO toSettingsDTO(Settings entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link SettingsDTO}.
     * @param entities
     * @return Collection<SettingsDTO>     */
    public abstract List<SettingsDTO> toSettingsDTOCollection(Collection<Settings> entities);

    /**
     * Converts an instance of type {@link SettingsDTO} to this DAO's entity.
     * @param settingsDTO
     * @return Settings
     */
    @InheritInverseConfiguration
    public abstract Settings settingsDTOToEntity(SettingsDTO settingsDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateSettingsFromSettingsDTO(SettingsDTO settingsDTO, @MappingTarget Settings entity);

}