// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, computed, effect, inject, Signal, linkedSignal, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { PageEvent } from '@angular/material/paginator';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { Loader } from '@app/@shared/loader/loader';
import { EditDocumentTypeComponent, EditDocumentTypeVarsForm } from './edit-document-type';
import { DocumentTypeDTO } from '@app/models/bw/co/kyvera/document/type/document-type-dto';
import { ExpectedField } from '@app/models/bw/co/kyvera/document/type/expected-field';
import { ExpectedFieldDialogComponent } from '@app/views/document/type/expected-field-dialog/expected-field-dialog';
import { FormField } from '@angular/forms/signals';

@Component({
  selector: 'app-edit-document-type',
  templateUrl: './edit-document-type.html',
  styleUrls: ['./edit-document-type.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    Loader,
    FormField,
  ],
})
export class EditDocumentTypeImplComponent extends EditDocumentTypeComponent {
  readonly expectedFieldsTableColumns = ['field', 'keyField', 'mandatory', 'format', 'actions'];
  readonly expectedFieldsTableData = computed(() => this.editDocumentTypeSignal().expectedFields || []);
  readonly expectedFieldsPageSizeOptions = [5, 10, 25];
  readonly expectedFieldsPageSize = signal(this.expectedFieldsPageSizeOptions[0]);
  readonly expectedFieldsPageIndex = signal(0);
  readonly expectedFieldsPagedData = computed(() => {
    const pageIndex = this.expectedFieldsPageIndex();
    const pageSize = this.expectedFieldsPageSize();
    const startIndex = pageIndex * pageSize;

    return this.expectedFieldsTableData().slice(startIndex, startIndex + pageSize);
  });

  override error = linkedSignal(() => false);
  override messages = linkedSignal(() => false);
  override success = linkedSignal(() => false);
  override loading = linkedSignal(() => false);
  override loaderMessage = linkedSignal(() => 'Loading...');

  constructor() {
    super();

    effect(() => {
      // let documentType = this.documentTypeApiStore.data();
      // this.editDocumentTypeForm.patchValue(documentType);
    });

    effect(() => {
      const totalItems = this.expectedFieldsTableData().length;
      const pageSize = this.expectedFieldsPageSize();
      const currentPageIndex = this.expectedFieldsPageIndex();
      const maxPageIndex = totalItems === 0 ? 0 : Math.floor((totalItems - 1) / pageSize);

      if (currentPageIndex > maxPageIndex) {
        this.expectedFieldsPageIndex.set(maxPageIndex);
      }
    });
  }

  updateDocumentTypeSignal(documentType: DocumentTypeDTO): EditDocumentTypeVarsForm {
    return {
      code: documentType.code,
      createdAt: documentType.createdAt,
      createdBy: documentType.createdBy,
      description: documentType.description,
      id: documentType.id,
      modifiedAt: documentType.modifiedAt,
      modifiedBy: documentType.modifiedBy,
      name: documentType.name,
      expectedFields: documentType.expectedFields || [],
      textExtractionPrompts: documentType.textExtractionPrompts || [],
      validationPrompts: documentType.validationPrompts || [],
    };
  }

  override ngOnInit() {
    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        this.documentTypeApi.findById(params.id).subscribe({
          next: (documentType: DocumentTypeDTO) => {
            this.editDocumentTypeSignal.set(this.updateDocumentTypeSignal(documentType));
          },
        });
      }
    });
  }

  doNgOnDestroy(): void { }

  override expectedFieldsAdd(): void {
    const dialogRef = this.dialog.open(ExpectedFieldDialogComponent, {
      width: '36rem',
      maxWidth: '95vw',
      data: {
        keyFieldMap: this.KeyFieldT,
        keyFieldOptions: this.KeyFieldOptions,
      },
    });

    dialogRef.afterClosed().subscribe({
      next: (expectedField?: ExpectedField) => {
        if (!expectedField) {
          return;
        }

        const nextCount = this.expectedFieldsTableData().length + 1;
        this.expectedFieldsPageIndex.set(
          Math.floor((nextCount - 1) / this.expectedFieldsPageSize())
        );

        this.editDocumentTypeSignal.update((value) => ({
          ...value,
          expectedFields: [...(value.expectedFields || []), expectedField],
        }));
      },
    });
  }

  expectedFieldsEdit(index: number, expectedField: ExpectedField): void {
    const dialogRef = this.dialog.open(ExpectedFieldDialogComponent, {
      width: '36rem',
      maxWidth: '95vw',
      data: {
        expectedField,
        keyFieldMap: this.KeyFieldT,
        keyFieldOptions: this.KeyFieldOptions,
      },
    });

    dialogRef.afterClosed().subscribe({
      next: (updatedExpectedField?: ExpectedField) => {
        if (!updatedExpectedField) {
          return;
        }

        this.editDocumentTypeSignal.update((value) => ({
          ...value,
          expectedFields: (value.expectedFields || []).map((item, itemIndex) => (
            itemIndex === index ? updatedExpectedField : item
          )),
        }));
      },
    });
  }

  onExpectedFieldsPageChange(event: PageEvent): void {
    this.expectedFieldsPageIndex.set(event.pageIndex);
    this.expectedFieldsPageSize.set(event.pageSize);
  }

  override beforeEditDocumentTypeSave(form: any): void {
    this.loading.set(true);

    let formData: EditDocumentTypeVarsForm = this.editDocumentTypeSignal();
    let docType = new DocumentTypeDTO();
    docType.code = formData.code;
    docType.createdAt = formData.createdAt;
    docType.createdBy = formData.createdBy;
    docType.description = formData.description;
    docType.id = formData.id;
    docType.modifiedAt = formData.modifiedAt;
    docType.modifiedBy = formData.modifiedBy;
    docType.name = formData.name;
    docType.expectedFields = formData.expectedFields || [];
    docType.textExtractionPrompts = formData.textExtractionPrompts || [];
    docType.validationPrompts = formData.validationPrompts || [];

    this.documentTypeApi.save(docType).subscribe({
      next: (documentType: DocumentTypeDTO) => {
        this.editDocumentTypeSignal.set(this.updateDocumentTypeSignal(documentType));
        this.loading.set(false);
      },
      error: (error) => {
        console.log(error);
        this.toaster.error(
          error.error?.message ? error.error.message : error.message
        )
        this.loading.set(false);
      }
    });
  }
}
