// Generated by andromda-angular cartridge (view\view.component.ts.vsl) DO NOT EDIT
// false
import {
  Component,
  OnInit,
  effect,
  inject,
  Input,
  AfterViewInit,
  signal,
  Signal,
  OnDestroy,
} from '@angular/core';
import {
  form,
  required,
} from "@angular/forms/signals";
import { ActivatedRoute, Router } from '@angular/router';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import {
  FormControl,
} from '@angular/forms';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { MatDialog } from '@angular/material/dialog';
import { DocumentTypeApiStore } from '@store/bw/co/kyvera/document/type/document-type-api.store';

import { CompletionRequestMessage } from '@models/bw/co/kyvera/lmstudio/completion-request-message';
import { DocumentTypeDTO } from '@models/bw/co/kyvera/document/type/document-type-dto';
import { DocumentTypeApi } from '@services/bw/co/kyvera/document/type/document-type-api';
import { DocumentTypeControllerImpl } from '@controllers/document/type/document-type-controller-impl';
import { ExpectedField } from '@models/bw/co/kyvera/document/type/expected-field';
import { KeyField } from '@models/bw/co/kyvera/key-field';
import { ToastrService } from 'ngx-toastr';

export class EditDocumentTypeVarsForm {
  id: string | any = null;
  createdAt: Date | any = null;
  createdBy: string | any = null;
  modifiedAt: Date | any = null;
  modifiedBy: string | any = null;
  code: string | any = null;
  name: string | any = null;
  description: string | any = null;
  expectedFields: Array<ExpectedField> = [];
  validationPrompts: Array<CompletionRequestMessage> = [];
  textExtractionPrompts: Array<CompletionRequestMessage> = [];
}

@Component({
  selector: 'app-edit-document-type-base',
  template: ''
})
export abstract class EditDocumentTypeComponent implements OnInit, AfterViewInit, OnDestroy {

  separatorKeysCodes: number[] = [ENTER, COMMA];
  @Input() editDocumentTypeVarsForm: EditDocumentTypeVarsForm = new EditDocumentTypeVarsForm();
  editDocumentTypeSignal = signal(this.editDocumentTypeVarsForm);
  editDocumentTypeSignalForm = form(this.editDocumentTypeSignal, (path) => {
    required(path.code, { message: 'code.required' })
    required(path.name, { message: 'name.required' })
  });

  idFilterControl = new FormControl('');

  createdAtFilterControl = new FormControl('');

  createdByFilterControl = new FormControl('');

  modifiedAtFilterControl = new FormControl('');

  modifiedByFilterControl = new FormControl('');

  codeFilterControl = new FormControl('');

  nameFilterControl = new FormControl('');

  descriptionFilterControl = new FormControl('');

  expectedFieldsFilterControl = new FormControl('');

  validationPromptsFilterControl = new FormControl('');

  textExtractionPromptsFilterControl = new FormControl('');

  hide: boolean = false;
  protected route: ActivatedRoute = inject(ActivatedRoute);
  protected router: Router = inject(Router);
  protected useCaseScope: UseCaseScope = inject(UseCaseScope);
  dialog: MatDialog = inject(MatDialog);
  toaster: ToastrService = inject(ToastrService);
  documentTypeController: DocumentTypeControllerImpl = inject(DocumentTypeControllerImpl);
  readonly documentTypeApi = inject(DocumentTypeApi);
  readonly documentTypeApiStore = inject(DocumentTypeApiStore);

  createNewExpectedFields(): ExpectedField {
    return new ExpectedField();
  }

  expectedFieldsAdd() {

    this.editDocumentTypeSignal.update((value) => ({
      ...value,
      expectedFields: [
        ...value.expectedFields,
        this.createNewExpectedFields()
      ]
    }))
  }

  expectedFieldsRemove(i: number, selected: ExpectedField) {
    this.editDocumentTypeSignal.update((value) => {
      const expectedFields = value.expectedFields.filter((_: any, index: number) => index !== i);

      return {
        ...value,
        expectedFields: expectedFields
      }
    });
  }

  createNewValidationPrompts(): CompletionRequestMessage {
    return new CompletionRequestMessage();
  }

  validationPromptsAdd() {

    this.editDocumentTypeSignal.update((value) => ({
      ...value,
      validationPrompts: [
        ...value.validationPrompts,
        this.createNewValidationPrompts()
      ]
    }))
  }

  validationPromptsRemove(i: number, selected: CompletionRequestMessage) {
    this.editDocumentTypeSignal.update((value) => {
      const validationPrompts = value.validationPrompts.filter((_: any, index: number) => index !== i);

      return {
        ...value,
        validationPrompts: validationPrompts
      }
    });
  }

  createNewTextExtractionPrompts(): CompletionRequestMessage {
    return new CompletionRequestMessage();
  }

  textExtractionPromptsAdd() {

    this.editDocumentTypeSignal.update((value) => ({
      ...value,
      textExtractionPrompts: [
        ...value.textExtractionPrompts,
        this.createNewTextExtractionPrompts()
      ]
    }))
  }

  textExtractionPromptsRemove(i: number, selected: CompletionRequestMessage) {
    this.editDocumentTypeSignal.update((value) => {
      const textExtractionPrompts = value.textExtractionPrompts.filter((_: any, index: number) => index !== i);

      return {
        ...value,
        textExtractionPrompts: textExtractionPrompts
      }
    });
  }

  KeyFieldT: any = KeyField;
  KeyFieldOptions = Object.keys(this.KeyFieldT);
  loaderMessage: Signal<string> = signal('');
  messages: Signal<any> = signal({});
  success: Signal<boolean> = signal(false);
  loading: Signal<boolean> = signal(false);
  error: Signal<boolean> = signal(false);
  selected: any = null;
  deleteUnrestricted = signal(false);


  constructor() {


    effect(() => {
      let messages = this.messages();

      if (this.success() && !this.loading()) {
        this.toaster.success(messages[0]);
      }

      if (this.error() && !this.loading()) {
        this.toaster.error(messages[0]);
      }
    })
  }


  ngOnInit() { }

  handleFormChanges(change: any): void {

  }

  editDocumentTypeFormReset() {

    this.editDocumentTypeSignal.set(new EditDocumentTypeVarsForm());
  }


  doNgAfterViewInit(): void { }

  ngAfterViewInit() {
    this.doNgAfterViewInit();
    this.documentTypeController.resetUseCaseScope();
  }

  abstract doNgOnDestroy(): void;

  ngOnDestroy() {
    this.doNgOnDestroy();
  }


  /**
   * This method may be overwritten
   */
  beforeEditDocumentTypeSave(form: any): void { }

  /**
   * This method may be overwritten
   */
  afterEditDocumentTypeSave(form: any): void { }

  /**
   * This method may be overwritten
   */
  get editDocumentTypeSaveDocumentType(): DocumentTypeDTO {
    return {} as DocumentTypeDTO;
  }

  editDocumentTypeSave(): void {

    let form: any = {
      documentType: this.editDocumentTypeSaveDocumentType,
    };

    this.beforeEditDocumentTypeSave(form);

    this.documentTypeController.editDocumentTypeSave(form.documentType);
    this.afterEditDocumentTypeSave(form);
  }


  /**
   * This method may be overwritten
   */
  beforeEditDocumentTypeSearch(form: any): void { }

  /**
   * This method may be overwritten
   */
  afterEditDocumentTypeSearch(form: any): void { }

  editDocumentTypeSearch(): void {

    let form: any = {
    };

    this.beforeEditDocumentTypeSearch(form);

    this.documentTypeController.editDocumentTypeSearch();
    this.afterEditDocumentTypeSearch(form);
  }


  /**
   * This method may be overwritten
   */
  beforeEditDocumentTypeDelete(form: any): void { }

  /**
   * This method may be overwritten
   */
  afterEditDocumentTypeDelete(form: any): void { }

  /**
   * This method may be overwritten
   */
  get editDocumentTypeDeleteDocumentType(): DocumentTypeDTO {
    return {} as DocumentTypeDTO;
  }

  editDocumentTypeDelete(): void {

    let form: any = {
      documentType: this.editDocumentTypeDeleteDocumentType,
    };

    this.beforeEditDocumentTypeDelete(form);

    this.documentTypeController.editDocumentTypeDelete(form.documentType);
    this.afterEditDocumentTypeDelete(form);
  }
}
