// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, computed, effect, inject, Signal, linkedSignal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { Loader } from '@app/@shared/loader/loader';
import { EditDocumentTypeComponent, EditDocumentTypeVarsForm } from './edit-document-type';
import { DocumentTypeDTO } from '@app/models/bw/co/centralkyc/document/type/document-type-dto';
import { FormField } from '@angular/forms/signals';

@Component({
  selector: 'app-edit-document-type',
  templateUrl: './edit-document-type.html',
  styleUrls: ['./edit-document-type.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    Loader,
    FormField,
  ],
})
export class EditDocumentTypeImplComponent extends EditDocumentTypeComponent {
  override error = linkedSignal(() => false);
  override messages = linkedSignal(() => false);
  override success = linkedSignal(() => false);
  override loading = linkedSignal(() => false);
  override loaderMessage = linkedSignal(() => 'Loading...');

  constructor() {
    super();

    effect(() => {
      // let documentType = this.documentTypeApiStore.data();
      // this.editDocumentTypeForm.patchValue(documentType);
    });
  }

  updateDocumentTypeSignal(documentType: DocumentTypeDTO): EditDocumentTypeVarsForm {
    return {
      code: documentType.code,
      createdAt: documentType.createdAt,
      createdBy: documentType.createdBy,
      description: documentType.description,
      id: documentType.id,
      modifiedAt: documentType.modifiedAt,
      modifiedBy: documentType.modifiedBy,
      name: documentType.name,
      expectedInformation: documentType.expectedInformation,
    };
  }

  override ngOnInit() {
    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        this.documentTypeApi.findById(params.id).subscribe({
          next: (documentType: DocumentTypeDTO) => {
            this.editDocumentTypeSignal.set(this.updateDocumentTypeSignal(documentType));
          },
        });
      }
    });
  }

  doNgOnDestroy(): void {}

  override beforeEditDocumentTypeSave(form: any): void {
    this.loading.set(true);

    this.documentTypeApi.save(this.editDocumentTypeSignal()).subscribe({
      next: (documentType: DocumentTypeDTO) => {
        this.editDocumentTypeSignal.set(this.updateDocumentTypeSignal(documentType));
        this.loading.set(false);
      },
      error: (error) => {
        console.log(error);
        this.toaster.error(
          error.error?.message ? error.error.message : error.message
        )
        this.loading.set(false);
      }
    });
  }
}
