// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { DocumentDTO } from '@models/bw/co/knowvera/document/document-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { TargetEntity } from '@models/bw/co/knowvera/target-entity';
import { SearchObject } from '@models/search-object';
import { DocumentSearchCriteria } from '@models/bw/co/knowvera/document/document-search-criteria';
import { DocumentVerificationStatus } from '@app/models/bw/co/knowvera/document/document-verification-status';

@Injectable({
  providedIn: 'root',
})
export class DocumentApi {
  protected path = '/document';

  private http = inject(HttpClient);

  public findByDocumentType(documentTypeId: string | any): Observable<DocumentDTO[] | any[]> {
    return this.http.get<DocumentDTO[] | any[]>(`${this.path}/documentTypeId/${documentTypeId}`);
  }

  public findById(id: string | any): Observable<DocumentDTO | any> {
    return this.http.get<DocumentDTO | any>(`${this.path}/${id}`);
  }

  public findByTarget(
    target: TargetEntity | any,
    targetId: string | any,
  ): Observable<DocumentDTO[] | any[]> {
    return this.http.get<DocumentDTO[] | any[]>(`${this.path}/target/${target}/${targetId}`);
  }

  public getAll(): Observable<DocumentDTO[] | any[]> {
    return this.http.get<DocumentDTO[] | any[]>(`${this.path}`);
  }

  public getAllPaged(
    pageNumber: number | any,
    pageSize: number | any,
  ): Observable<Page<DocumentDTO> | any> {
    return this.http.get<Page<DocumentDTO> | any>(
      `${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`,
    );
  }

  public remove(id: string | any): Observable<boolean | any> {
    return this.http.delete<boolean | any>(`${this.path}/${id}`);
  }

  public save(document: DocumentDTO | any): Observable<DocumentDTO | any> {
    return this.http.post<DocumentDTO | any>(`${this.path}`, document);
  }

  public search(
    criteria: SearchObject<DocumentSearchCriteria>): Observable<DocumentDTO[]> {

    return this.http.post<DocumentDTO[]>(`${this.path}/search`, criteria);
  }

  public searchPaged(
    criteria: SearchObject<DocumentSearchCriteria>): Observable<Page<DocumentDTO>> {

    return this.http.post<Page<DocumentDTO>>(`${this.path}/search/paged`, criteria);
  }

  public upload(
    target: TargetEntity,
    targetId: string,
    documentTypeId: string,
    file: File,
    purpose?: string
  ): Observable<DocumentDTO | any> {
    const formData: FormData = new FormData();
    formData.append('file', file);

    let url = `${this.path}/upload/${target}/${targetId}/type/${documentTypeId}`;

    if (purpose) {
      url += `?purpose=${purpose}`;
    }

    return this.http.post<DocumentDTO | any>(
      url,
      formData,
    );
  }

  public downloadFile(id: string | any): Observable<any> {
    return this.http.get(`${this.path}/${id}/download`, {
      responseType: 'blob',
    });
  }

  public downloadFileByUrl(objectName: string | any): Observable<any> {
    return this.http.get(`${this.path}/download?objectName=${objectName}`, {
      responseType: 'blob',
    });
  }

  public updateFileContent(id: string, content: string): Observable<DocumentDTO> {
    return this.http.put<DocumentDTO>(`${this.path}/${id}/content`, content);
  }

  public analyseDocument(id: string): Observable<DocumentDTO> {
    return this.http.get<DocumentDTO>(`${this.path}/${id}/analysis`);
  }

  public verifyData(id: string): Observable<DocumentDTO> {
    return this.http.get<DocumentDTO>(`${this.path}/${id}/data-verification`);
  }

  public updateVerificationStatus(id: string, status: DocumentVerificationStatus): Observable<DocumentDTO> {
    return this.http.get<DocumentDTO>(`${this.path}/${id}/verification-status?verificationStatus=${status}`);
  }

  public geminiTextExtration(id: string): Observable<DocumentDTO> {
    return this.http.get<DocumentDTO>(`${this.path}/${id}/gemini-text-extraction`);
  }
}
