// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { SequenceController } from '@controllers/sequence/sequence-controller';

@Injectable()
export class SequenceControllerImpl extends SequenceController {

    constructor() {
        super();
    }

}
