// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by controller-advice.java.vsl in andromda-spring-cartridge. Do not modify by hand!.
//
package bw.co.knowvera.organisation;

import bw.co.knowvera.ErrorResponse;
import java.time.Instant;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Translates the errors thrown by {@link OrganisationApiServiceBase}
 * into human-readable API responses for the organisationApi endpoints.
 *
 * Scoped to {@link OrganisationApi} only, and ordered ahead
 * of global exception handlers so that this advice's friendlier messages take precedence.
 */
@RestControllerAdvice(assignableTypes = OrganisationApi.class)
@Order(Ordered.HIGHEST_PRECEDENCE)
public class OrganisationApiControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(OrganisationApiControllerAdvice.class);

    /**
     * Handles manual argument validation checks thrown by OrganisationApiServiceBase.
     * Maps generated validation messages to friendly human-readable descriptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ErrorResponse> handleIllegalArgument(IllegalArgumentException ex) {
        String message = ex.getMessage() == null ? "" : ex.getMessage();
        String friendly = toFriendlyMessage(message);

        LOGGER.warn("OrganisationApi validation failed: {}", message);

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.BAD_REQUEST.value(),
                HttpStatus.BAD_REQUEST.name(),
                friendly,
                Arrays.asList(ex.getMessage()),
                Instant.now()
        );

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(errorResponse);
    }

    /**
     * Handles {@link OrganisationServiceException} thrown by referenced services.
     */
    @ExceptionHandler(OrganisationServiceException.class)
    public ResponseEntity<ErrorResponse> handleOrganisationServiceException(OrganisationServiceException ex) {
        LOGGER.error("Referenced service error (OrganisationService)", ex);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ErrorResponse(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        HttpStatus.INTERNAL_SERVER_ERROR.name(),
                        "An error occurred while communicating with dependent services. Please try again shortly.",
                        null,
                        Instant.now()
                ));
    }

    /**
     * Maps validation messages thrown by OrganisationApiServiceBase to plain-language equivalents.
     */
    private String toFriendlyMessage(String message) {
        if (message.contains(".findById(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".save(") && message.contains("'organisation'")) {
            return "Organisation is required.";
        }

        if (message.contains(".remove(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".pagedSearch(") && message.contains("'criteria'")) {
            return "Criteria is required.";
        }

        if (message.contains(".loadRequestOrganisation(") && message.contains("'requestId'")) {
            return "Request Id is required.";
        }

        if (message.contains(".loadRequestOrganisation(") && message.contains("'identityConfirmationToken'")) {
            return "Identity Confirmation Token is required.";
        }

        if (message.contains(".loadRequestOrganisation(") && message.contains("'registrationNo'")) {
            return "Registration No is required.";
        }

        if (message.contains(".findByRegistrationNo(") && message.contains("'registrationNo'")) {
            return "Registration No is required.";
        }

        if (message.contains(".verifyOrganisation(") && message.contains("'id'")) {
            return "Id is required.";
        }


        // Fallback for any unmapped validation message
        return message;
    }
}