// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::document::DocumentVerificationStatus
 */
export enum DocumentVerificationStatus {
    /** TODO: Model Documentation for Enumeration Literal UNVERIFIED value "UNVERIFIED": $literal.enumerationLiteralDisplay */
    UNVERIFIED = "UNVERIFIED",
    /** TODO: Model Documentation for Enumeration Literal VERIFIED value "VERIFIED": $literal.enumerationLiteralDisplay */
    VERIFIED = "VERIFIED",
    /** TODO: Model Documentation for Enumeration Literal REJECTED value "REJECTED": $literal.enumerationLiteralDisplay */
    REJECTED = "REJECTED",
    /** TODO: Model Documentation for Enumeration Literal MANUAL_REVIEW value "MANUAL_REVIEW": $literal.enumerationLiteralDisplay */
    MANUAL_REVIEW = "MANUAL_REVIEW"
}
