// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.kyc.fields;

import bw.co.centralkyc.kyc.KycRecordMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        GroupFieldValueMapper.class,
        KycRecordMapper.class    }
)
public abstract class KycReportSectionMapper {
    
    /**
     * Converts this entity to an object of type {@link KycReportSectionDTO}.
     * @param entity
     * @return KycReportSectionDTO
     */
    public abstract KycReportSectionDTO toKycReportSectionDTO(KycReportSection entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link KycReportSectionDTO}.
     * @param entities
     * @return Collection<KycReportSectionDTO>     */
    public abstract List<KycReportSectionDTO> toKycReportSectionDTOCollection(Collection<KycReportSection> entities);

    /**
     * Converts an instance of type {@link KycReportSectionDTO} to this DAO's entity.
     * @param kycReportSectionDTO
     * @return KycReportSection
     */
    @InheritInverseConfiguration
    public abstract KycReportSection kycReportSectionDTOToEntity(KycReportSectionDTO kycReportSectionDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateKycReportSectionFromKycReportSectionDTO(KycReportSectionDTO kycReportSectionDTO, @MappingTarget KycReportSection entity);

}