// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.kyc.fields;

import bw.co.centralkyc.kyc.KycRecordRepository;
import org.springframework.stereotype.Repository;

/**
 * @see KycReportSection
 */
@Repository("kycReportSectionDao")
public class KycReportSectionDaoImpl
    extends KycReportSectionDaoBase
{
    
    public KycReportSectionDaoImpl(
        GroupFieldValueRepository groupFieldValueRepository,
        KycRecordRepository kycRecordRepository,
        KycReportSectionRepository kycReportSectionRepository
    ) {

        super(
            groupFieldValueRepository,
            kycRecordRepository,
            kycReportSectionRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toKycReportSectionDTO(
        KycReportSection source,
        KycReportSectionDTO target)
    {
        // TODO verify behavior of toKycReportSectionDTO
        super.toKycReportSectionDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KycReportSectionDTO toKycReportSectionDTO(final KycReportSection entity)
    {
        // TODO verify behavior of toKycReportSectionDTO
        return super.toKycReportSectionDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private KycReportSection loadKycReportSectionFromKycReportSectionDTO(KycReportSectionDTO kycReportSectionDTO)
    {
        // TODO implement loadKycReportSectionFromKycReportSectionDTO
        throw new UnsupportedOperationException("bw.co.centralkyc.kyc.fields.loadKycReportSectionFromKycReportSectionDTO(KycReportSectionDTO) not yet implemented.");

        /* A typical implementation looks like this:
        if (kycReportSectionDTO.getId() == null)
        {
            return  KycReportSection.Factory.newInstance();
        }
        else
        {
            return this.kycReportSectionRepository.findById(kycReportSectionDTO.getId())
                .orElseThrow(() -> new KycReportSectionServiceException("Entity not found for id: " + kycReportSectionDTO.getId()));
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public KycReportSection kycReportSectionDTOToEntity(KycReportSectionDTO kycReportSectionDTO)
    {
        // TODO verify behavior of kycReportSectionDTOToEntity
        KycReportSection entity = this.loadKycReportSectionFromKycReportSectionDTO(kycReportSectionDTO);
        this.kycReportSectionDTOToEntity(kycReportSectionDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void kycReportSectionDTOToEntity(
        KycReportSectionDTO source,
        KycReportSection target,
        boolean copyIfNull)
    {
        // TODO verify behavior of kycReportSectionDTOToEntity
        super.kycReportSectionDTOToEntity(source, target, copyIfNull);
    }
}