// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.user;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import bw.co.centralkyc.keycloak.KeycloakUserService;

@RestController
public class UserApiImpl implements UserApi {

    protected Logger logger = LoggerFactory.getLogger(UserApiImpl.class);    

    private final KeycloakUserService keycloakUserService;

    public UserApiImpl(KeycloakUserService keycloakUserService) {

        this.keycloakUserService = keycloakUserService;
    }

    @Override
    public ResponseEntity<UserDTO> addClientRoles(
            String clientId, Set<String> roles, String userId) {
        try {
            logger.debug(
                    "Add user/client roles with client Id " + clientId + ",roles " + roles
                            + " and user Id " + userId);
            UserDTO rep = this.keycloakUserService.addClientRoles(clientId, roles, userId);
            return ResponseEntity.ok(rep);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Boolean> addRole(String userId,
            String role) {

        try {
            
            return ResponseEntity.ok(this.keycloakUserService.updateUserRoles(userId, role, 1));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<String> changePassword(String userId,
            String newPassword) {
        try {
            
            this.keycloakUserService.updateUserPassword(userId, newPassword);
            return ResponseEntity.ok(true ? "Password changed successfully" : "Failed to change password.");

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<UserDTO>> findByClientRoles(
            Set<String> roles, String clientId) {
        try {
            return ResponseEntity.ok(this.keycloakUserService.getUsersByClientRoles(clientId, roles));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<UserDTO>> findByRealmRoles(
            Set<String> roles) {
        try {
            return ResponseEntity.ok(this.keycloakUserService.getUsersByRealmRoles(roles));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<UserDTO> findUserById(String userId) {
        try {
            logger.debug("Search user by Id " + userId);
            UserDTO rep = this.keycloakUserService.findUserById(userId);
            return ResponseEntity.ok(rep);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<UserDTO>> loadUsers() {
        try {
            
            Collection<UserDTO> data = this.keycloakUserService.findAll();
            return ResponseEntity.ok(data);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Boolean> removeRole(String userId,
            String role) {
        try {
            Boolean responseData = this.keycloakUserService.updateUserRoles(userId, role, -1);
            return ResponseEntity.ok(responseData);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<UserDTO> saveUser(
            UserDTO user) {
        try {
            logger.debug("Save User " + user);

            if (StringUtils.isBlank(user.getUserId()))
                user = this.keycloakUserService.createUser(user);
            else {
                keycloakUserService.updateUser(user);
            }

            return ResponseEntity.ok(user);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<UserDTO>> search(String criteria) {
        try {
            
            logger.debug("Search user by criteria" + criteria);

            List<UserDTO> users = this.keycloakUserService.search(criteria);

            return ResponseEntity.ok(users);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Boolean> updateUserName(String userId,
            String username) {
        try {
            
            Optional<Boolean> data = Optional.empty(); // TODO: Add custom code here;
            return ResponseEntity.ok(data.get());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<UserDTO>> findByBranchId(String branchId) {

        try {
            
            return ResponseEntity.ok(this.keycloakUserService.getBranchUsers(branchId));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<UserDTO>> findByBranchName(String branch) {

        try {
            
            Optional<Collection<UserDTO>> data = Optional.empty(); // TODO: Add custom code here;
            return ResponseEntity.ok(data.get());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<UserDTO>> findByOrganisationId(String organisationId) {

        try {
            
            return ResponseEntity.ok(this.keycloakUserService.getOrganisationUsers(organisationId));
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<UserDTO>> findByOrganisationName(String organisation) {

        try {
            
            Optional<Collection<UserDTO>> data = Optional.empty(); // TODO: Add custom code here;
            return ResponseEntity.ok(data.get());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<UserDTO> findByIdentityNo(String identityNo) {

        try {
            return ResponseEntity.ok(this.keycloakUserService.getUserByIdentityNo(identityNo));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }
}