// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.document.type;

import bw.co.centralkyc.document.type.field.ExpectedFieldMapper;
import bw.co.centralkyc.document.type.verification.VerificationDataConfig;
import bw.co.centralkyc.document.type.verification.VerificationDataConfigDTO;
import bw.co.centralkyc.document.type.verification.VerificationDataConfigMapper;
import bw.co.centralkyc.document.type.verification.VerificationDataConfigRepository;
import bw.co.centralkyc.utils.MappingUtils;

import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.beans.factory.annotation.Autowired;

@Mapper(
    componentModel = "spring",
    uses = {
        MappingUtils.class,
        VerificationDataConfigMapper.class,
        ExpectedFieldMapper.class
    }
)
public abstract class DocumentTypeMapper {
    
    @Autowired
    protected VerificationDataConfigRepository verificationDataConfigRepository;

    @Autowired
    private VerificationDataConfigMapper verificationDataConfigMapper;
    
    /**
     * Converts this entity to an object of type {@link DocumentTypeDTO}.
     * @param entity
     * @return DocumentTypeDTO
     */
    // @Mapping(source = "expectedFields", target = "expectedFields")
    @Mapping(target = "verificationDataConfigs", expression = "java(mapVerificationDataConfigs(entity.getVerificationDataConfigs()))")
    public abstract DocumentTypeDTO toDocumentTypeDTO(DocumentType entity);

    protected Collection<VerificationDataConfigDTO> mapVerificationDataConfigs(Collection<VerificationDataConfig> verificationDataConfigs) {

        Collection<UUID> ids = verificationDataConfigs.stream()
            .filter(config -> config.getId() != null)
            .map(VerificationDataConfig::getId)
            .toList();

        Collection<VerificationDataConfig> configs = verificationDataConfigRepository.findAllById(ids);
        return configs.stream()
            .map(verificationDataConfigMapper::toVerificationDataConfigDTO)
            .toList();
    }

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link DocumentTypeDTO}.
     * @param entities
     * @return Collection<DocumentTypeDTO>     */
    public abstract List<DocumentTypeDTO> toDocumentTypeDTOCollection(Collection<DocumentType> entities);

    /**
     * Converts an instance of type {@link DocumentTypeDTO} to this DAO's entity.
     * @param documentTypeDTO
     * @return DocumentType
     */
    @InheritInverseConfiguration
    public abstract DocumentType documentTypeDTOToEntity(DocumentTypeDTO documentTypeDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateDocumentTypeFromDocumentTypeDTO(DocumentTypeDTO documentTypeDTO, @MappingTarget DocumentType entity);

}