<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>bw.co.knowvera</groupId>
        <artifactId>knowvera</artifactId>
        <version>0.0.1</version>
    </parent>

    <groupId>bw.co.knowvera</groupId>
    <artifactId>knowvera-angular</artifactId>
    <version>0.0.1</version>
    <packaging>jar</packaging>

    <name>The Knowvera KYC Project Angular Frontend</name>
    <description>The Knowvera KYC Project angular front end</description>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven-antrun-plugin.version}</version>
                <executions>
                    <execution>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <target>
                        <copy todir="${project.basedir}/target/knowvera/src" overwrite="true" failonerror="false">
                            <fileset dir="${project.basedir}/target/src">
                                <include name="**/*"/>
                            </fileset>
                        </copy>
                        <copy todir="${project.basedir}/target/knowvera/src" overwrite="true" failonerror="false">
                            <fileset dir="${project.basedir}/src">
                                <include name="**/*"/>
                            </fileset>
                        </copy>
                        <copy todir="${project.basedir}/target/knowvera/public" overwrite="true" failonerror="false">
                            <fileset dir="${project.basedir}/public">
                                <include name="**/*"/>
                            </fileset>
                        </copy>
                        <copy todir="${project.basedir}/target/knowvera/.husky" overwrite="true" failonerror="false">
                            <fileset dir="${project.basedir}/.husky">
                                <include name="**/*"/>
                            </fileset>
                        </copy>
                        <copy todir="${project.basedir}/target/knowvera" overwrite="true" failonerror="false">
                            <fileset dir="${project.basedir}">
                                <include name=".browserslistrc"/>
                                <include name=".editorconfig"/>
                                <include name=".htmlhintrc"/>
                                <include name=".stylelintrc"/>
                                <include name="*.json"/>
                                <include name="*.js"/>
                                <include name="README.md"/>
                            </fileset>
                        </copy>
                    </target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
