// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, inject, linkedSignal } from '@angular/core';
import { SubscriptionsComponent } from '@views/subscription/search/subscriptions';
import { SubscriptionsVarsForm } from '@views/subscription/search/subscriptions';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule, CurrencyPipe, DatePipe } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { MatPaginator } from '@angular/material/paginator';
import { ColumnModel } from '@app/models/column.model';

@Component({
  selector: 'app-subscriptions',
  templateUrl: './subscriptions.html',
  styleUrls: ['./subscriptions.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
  ],
  providers: [DatePipe, CurrencyPipe],
})
export class SubscriptionsImplComponent extends SubscriptionsComponent {
override error = linkedSignal(() => this.kycSubscriptionApiStore.error());
  override messages = linkedSignal(() => this.kycSubscriptionApiStore.messages());
  override success = linkedSignal(() => this.kycSubscriptionApiStore.success());

  datePipe = inject(DatePipe);
  currencyPipe = inject(CurrencyPipe)

  override subscriptionsTableSignal = linkedSignal(() => this.kycSubscriptionApiStore.dataPage());

  override subscriptionsTableColumns: ColumnModel[] = [
    new ColumnModel('ref', 'ref', false),
    new ColumnModel('organisationName', 'organisation.name', false),
    new ColumnModel('startDate', 'start.date', false, undefined, this.datePipe, ['dd-MM-yyyy']),
    new ColumnModel('endDate', 'end.date', false, undefined, this.datePipe, ['dd-MM-yyyy']),
    new ColumnModel('amount', 'amount', false, undefined, this.currencyPipe, ['BWP']),
  ];

  constructor() {
    super();
  }

  override ngOnInit() {
    this.kycSubscriptionApiStore.reset();
  }

  doNgOnDestroy(): void {}

  override doNgAfterViewInit(): void {
    this.subscriptionsTable?.tablePaginator?.page?.subscribe({
      next: (paginator: MatPaginator) => {
        this.doSearch(paginator.pageIndex, paginator.pageSize);
      },
    });

    this.doSearch();
  }

  private doSearch(pageNumber: number = 0, pageSize: number = 10): void {
    let value = this.subscriptionsSignal().criteria || '';

    this.kycSubscriptionApiStore.pagedSearch({
      criteria: value,
      pageNumber: pageNumber,
      pageSize: pageSize,
    });
  }

  override beforeSubscriptionsSearch(form: any): void {
    this.doSearch();
  }
}
