// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.kyc;

import bw.co.centralkyc.document.DocumentMapper;
import bw.co.centralkyc.individual.IndividualMapper;
import bw.co.centralkyc.individual.IndividualRepository;
import bw.co.centralkyc.individual.employment.EmploymentRecordMapper;
import bw.co.centralkyc.kyc.verification.KycVerificationMapper;
import bw.co.centralkyc.utils.MappingUtils;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        DocumentMapper.class,
        EmploymentRecordMapper.class,
        KycVerificationMapper.class,
        IndividualRepository.class,
        IndividualMapper.class,
        MappingUtils.class    
    }
)
public interface KycRecordMapper {
    
    /**
     * Converts this entity to an object of type {@link KycRecordDTO}.
     * @param entity
     * @return KycRecordDTO
     */
    @Mapping(source = "documents", target = "documents")
    @Mapping(source = "employmentRecord", target = "employmentRecord")
    @Mapping(source = "kycVerification", target = "kycVerification")
    @Mapping(source = "pepStatus", target = "declaration.pepStatus")
    @Mapping(source = "pepDetails", target = "declaration.pepDetails")
    @Mapping(source = "sanctionsMatch", target = "declaration.sanctionsMatch")
    @Mapping(source = "sanctionsDetails", target = "declaration.sanctionsDetails")
    KycRecordDTO toKycRecordDTO(KycRecord entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link KycRecordDTO}.
     * @param entities
     * @return Collection<KycRecordDTO>     */
    List<KycRecordDTO> toKycRecordDTOCollection(Collection<KycRecord> entities);

    /**
     * Converts an instance of type {@link KycRecordDTO} to this DAO's entity.
     * @param kycRecordDTO
     * @return KycRecord
     */
    @InheritInverseConfiguration
    KycRecord kycRecordDTOToEntity(KycRecordDTO kycRecordDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateKycRecordFromKycRecordDTO(KycRecordDTO kycRecordDTO, @MappingTarget KycRecord entity);

}