// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.organisation.client;

import bw.co.centralkyc.document.DocumentMapper;
import bw.co.centralkyc.organisation.OrganisationMapper;
import bw.co.centralkyc.utils.MappingUtils;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        DocumentMapper.class,
        OrganisationMapper.class,
        MappingUtils.class
    }
)
public interface ClientRequestMapper {
    
    /**
     * Converts this entity to an object of type {@link ClientRequestDTO}.
     * @param entity
     * @return ClientRequestDTO
     */
    @Mapping(target = "organisation", source = "organisation.name")
    @Mapping(target = "organisationRegistrationNo", source = "organisation.registrationNo")
    @Mapping(target = "organisationId", source = "organisation.id")
    ClientRequestDTO toClientRequestDTO(ClientRequest entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link ClientRequestDTO}.
     * @param entities
     * @return Collection<ClientRequestDTO>     */
    List<ClientRequestDTO> toClientRequestDTOCollection(Collection<ClientRequest> entities);

    /**
     * Converts an instance of type {@link ClientRequestDTO} to this DAO's entity.
     * @param clientRequestDTO
     * @return ClientRequest
     */
    @InheritInverseConfiguration
    @Mapping(target = "organisation", ignore = true)
    ClientRequest clientRequestDTOToEntity(ClientRequestDTO clientRequestDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "organisation", ignore = true)
    void updateClientRequestFromClientRequestDTO(ClientRequestDTO clientRequestDTO, @MappingTarget ClientRequest entity);

}