// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.organisation.client;

import bw.co.centralkyc.document.DocumentMapper;
import bw.co.centralkyc.individual.IndividualMapper;
import bw.co.centralkyc.organisation.OrganisationMapper;
import bw.co.centralkyc.utils.MappingUtils;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.beans.factory.annotation.Autowired;

@Mapper(
    componentModel = "spring",
    uses = {
        DocumentMapper.class,
        OrganisationMapper.class,
        MappingUtils.class
    }
)
public abstract class ClientRequestMapper {
    
    /**
     * Converts this entity to an object of type {@link ClientRequestDTO}.
     * @param entity
     * @return ClientRequestDTO
     */
    // WARNING! No conversion for target.organisation (can't convert source.getOrganisation():bw.co.centralkyc.organisation.Organisation to java.lang.String)
    @Mapping(target = "organisation", source = "organisation.name")
    @Mapping(target = "organisationId", source = "organisation.id")
    @Mapping(target = "organisationCode", source = "organisation.code")
    @Mapping(target = "organisationRegistrationNo", source = "organisation.registrationNo")
    public abstract ClientRequestDTO toClientRequestDTO(ClientRequest entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link ClientRequestDTO}.
     * @param entities
     * @return Collection<ClientRequestDTO>     */
    public abstract List<ClientRequestDTO> toClientRequestDTOCollection(Collection<ClientRequest> entities);

    /**
     * Converts an instance of type {@link ClientRequestDTO} to this DAO's entity.
     * @param clientRequestDTO
     * @return ClientRequest
     */
    @InheritInverseConfiguration
    public abstract ClientRequest clientRequestDTOToEntity(ClientRequestDTO clientRequestDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateClientRequestFromClientRequestDTO(ClientRequestDTO clientRequestDTO, @MappingTarget ClientRequest entity);

}