// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringServiceBase.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
/**
 * TEMPLATE:    SpringServiceBase.vsl in andromda-spring cartridge
 * MODEL CLASS: AndroMDAModel::backend::bw.co.knowvera::audit::AuditLogService
 * STEREOTYPE:  Service
 */
package bw.co.knowvera.audit;

import bw.co.knowvera.PrincipalStore;
import bw.co.knowvera.audit.AuditLogCriteria;
import bw.co.knowvera.audit.AuditLogDTO;
import jakarta.validation.Valid;
import java.security.Principal;
import java.util.List;
import java.util.Locale;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Page;

/**
 * <p>
 * Spring Service base class for <code>AuditLogService</code>,
 * provides access to all services and entities referenced by this service.
 * </p>
 *
 * @see AuditLogService
 */
public abstract class AuditLogServiceBase
    implements AuditLogService
{
    protected Logger logger = LoggerFactory.getLogger(AuditLogService.class);
    protected final AuditLogRepository auditLogRepository;
    protected final AuditLogMapper auditLogMapper;
    protected final MessageSource messageSource;

    public AuditLogServiceBase(
        AuditLogRepository auditLogRepository,
        AuditLogMapper auditLogMapper,
        MessageSource messageSource
    ) {
        this.auditLogRepository = auditLogRepository;
        this.auditLogMapper = auditLogMapper;
        this.messageSource = messageSource;
    }

    /**
     * Gets the reference to <code>auditLog</code>'s repository.
     * @return auditLogRepository
     */
    public AuditLogRepository getAuditLogRepository() {
        return auditLogRepository;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditLogDTO findById(final String id)
    {
        if (id == null || id.trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.findById(String id) - 'id' can not be null or empty");
        }
        try
        {
            return this.handleFindById(id);
        }
        catch (Throwable th)
        {
            throw new AuditLogServiceException(
                "Error performing 'AuditLogService.findById(String id)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #findById(String)}
     * @param id java.lang.String TODO: Model Documentation for AuditLogService.findById(id)
     * @return AuditLogDTO
     * @throws Exception
     */
    protected abstract AuditLogDTO handleFindById(String id)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditLogDTO save(final @Valid AuditLogDTO auditLog)
    {
        if (auditLog == null)
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog' can not be null");
        }
        if (auditLog.getUsername() == null || auditLog.getUsername().trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog.username' can not be null or empty");
        }
        if (auditLog.getTimestamp() == null)
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog.timestamp' can not be null");
        }
        if (auditLog.getEvent() == null || auditLog.getEvent().trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog.event' can not be null or empty");
        }
        if (auditLog.getIpAddress() == null || auditLog.getIpAddress().trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog.ipAddress' can not be null or empty");
        }
        if (auditLog.getAgent() == null || auditLog.getAgent().trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog.agent' can not be null or empty");
        }
        if (auditLog.getEventLabel() == null || auditLog.getEventLabel().trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog.eventLabel' can not be null or empty");
        }
        if (auditLog.getEntityType() == null || auditLog.getEntityType().trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog.entityType' can not be null or empty");
        }
        if (auditLog.getUserId() == null || auditLog.getUserId().trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.save(@Valid AuditLogDTO auditLog) - 'auditLog.userId' can not be null or empty");
        }
        try
        {
            return this.handleSave(auditLog);
        }
        catch (Throwable th)
        {
            throw new AuditLogServiceException(
                "Error performing 'AuditLogService.save(@Valid AuditLogDTO auditLog)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #save(@Valid AuditLogDTO)}
     * @param auditLog AuditLogDTO TODO: Model Documentation for AuditLogService.save(auditLog)
     * @return AuditLogDTO
     * @throws Exception
     */
    protected abstract AuditLogDTO handleSave(@Valid AuditLogDTO auditLog)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean remove(final String id)
    {
        if (id == null || id.trim().isEmpty())
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.remove(String id) - 'id' can not be null or empty");
        }
        try
        {
            return this.handleRemove(id);
        }
        catch (Throwable th)
        {
            throw new AuditLogServiceException(
                "Error performing 'AuditLogService.remove(String id)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #remove(String)}
     * @param id java.lang.String TODO: Model Documentation for AuditLogService.remove(id)
     * @return boolean
     * @throws Exception
     */
    protected abstract boolean handleRemove(String id)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public List<AuditLogDTO> getAll()
    {
        try
        {
            return this.handleGetAll();
        }
        catch (Throwable th)
        {
            throw new AuditLogServiceException(
                "Error performing 'AuditLogService.getAll()' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #getAll()}
     * @return List<AuditLogDTO>
     * @throws Exception
     */
    protected abstract List<AuditLogDTO> handleGetAll()
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public List<AuditLogDTO> search(final @Valid AuditLogCriteria criteria)
    {
        if (criteria == null)
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.search(@Valid AuditLogCriteria criteria) - 'criteria' can not be null");
        }
        try
        {
            return this.handleSearch(criteria);
        }
        catch (Throwable th)
        {
            throw new AuditLogServiceException(
                "Error performing 'AuditLogService.search(@Valid AuditLogCriteria criteria)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #search(@Valid AuditLogCriteria)}
     * @param criteria AuditLogCriteria TODO: Model Documentation for AuditLogService.search(criteria)
     * @return List<AuditLogDTO>
     * @throws Exception
     */
    protected abstract List<AuditLogDTO> handleSearch(@Valid AuditLogCriteria criteria)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Page<AuditLogDTO> getAll(final Integer pageNumber, final Integer pageSize)
    {
        try
        {
            return this.handleGetAll(pageNumber, pageSize);
        }
        catch (Throwable th)
        {
            throw new AuditLogServiceException(
                "Error performing 'AuditLogService.getAll(Integer pageNumber, Integer pageSize)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #getAll(Integer, Integer)}
     * @param pageNumber java.lang.Integer TODO: Model Documentation for AuditLogService.getAll(pageNumber)
     * @param pageSize java.lang.Integer TODO: Model Documentation for AuditLogService.getAll(pageSize)
     * @return Page<AuditLogDTO>
     * @throws Exception
     */
    protected abstract Page<AuditLogDTO> handleGetAll(Integer pageNumber, Integer pageSize)
        throws Exception;

    /**
     * {@inheritDoc}
     */
    @Override
    public Page<AuditLogDTO> search(final @Valid AuditLogCriteria criteria, final Integer pageNumber, final Integer pageSize)
    {
        if (criteria == null)
        {
            throw new IllegalArgumentException(
                "bw.co.knowvera.audit.AuditLogService.search(@Valid AuditLogCriteria criteria, Integer pageNumber, Integer pageSize) - 'criteria' can not be null");
        }
        try
        {
            return this.handleSearch(criteria, pageNumber, pageSize);
        }
        catch (Throwable th)
        {
            throw new AuditLogServiceException(
                "Error performing 'AuditLogService.search(@Valid AuditLogCriteria criteria, Integer pageNumber, Integer pageSize)' --> " + th,
                th);
        }
    }

    /**
     * Performs the core logic for {@link #search(@Valid AuditLogCriteria, Integer, Integer)}
     * @param criteria AuditLogCriteria TODO: Model Documentation for AuditLogService.search(criteria)
     * @param pageNumber java.lang.Integer TODO: Model Documentation for AuditLogService.search(pageNumber)
     * @param pageSize java.lang.Integer TODO: Model Documentation for AuditLogService.search(pageSize)
     * @return Page<AuditLogDTO>
     * @throws Exception
     */
    protected abstract Page<AuditLogDTO> handleSearch(@Valid AuditLogCriteria criteria, Integer pageNumber, Integer pageSize)
        throws Exception;

    /**
     * Gets the current <code>principal</code> if one has been set,
     * otherwise returns <code>null</code>.
     *
     * @return the current principal
     */
    protected Principal getPrincipal()
    {
        return PrincipalStore.get();
    }

    /**
     * Gets the message source available to this service.
     * @return MessageSource
     */
    protected MessageSource getMessages()
    {
        return messageSource;
    }

    /**
     * Gets the message having the given <code>key</code> in the underlying message bundle.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @return String
     */
    protected String getMessage(final String key)
    {
        return this.getMessages().getMessage(key, null, null);
    }

    /**
     * Gets the message having the given <code>key</code> and <code>arguments</code> in the
     * underlying message bundle.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @param arguments any arguments to substitute when resolving the message.
     * @return String
     */
    protected String getMessage(final String key, final Object[] arguments)
    {
        return this.getMessages().getMessage(key, arguments, null);
    }

    /**
     * Gets the message having the given <code>key</code> using the given <code>arguments</code>
     * for the given <code>locale</code>.
     *
     * @param key the key of the message in the messages.properties message bundle.
     * @param arguments any arguments to substitute when resolving the message.
     * @param locale the locale of the messages to retrieve.
     * @return String
     */
    protected String getMessage(
        final String key, final Object[] arguments,
        final Locale locale)
    {
        return this.getMessages().getMessage(key, arguments, locale);
    }


// spring-service-base merge-point
}