// license-header java merge-point
//
/**
 * @author Generated by Service.vsl in andromda-java-cartridge on 05/24/2026 16:42:38+0200 Do not modify by hand!
 *
 * TEMPLATE:     Service.vsl in andromda-java-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.knowvera::audit::AuditLogService
 * STEREOTYPE:   Service
 */
package bw.co.knowvera.audit;

import jakarta.validation.Valid;
import java.util.List;
import org.springframework.data.domain.Page;

import bw.co.knowvera.audit.AuditLogCriteria;
import bw.co.knowvera.audit.AuditLogDTO;

/**
 * TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService
 */
public interface AuditLogService
{
    /**
     * TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.findById
     * @param id TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.findById(id)
     * @return AuditLogDTO
     */
    public AuditLogDTO findById(String id) ;

    /**
     * TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.save
     * @param auditLog TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.save(auditLog)
     * @return AuditLogDTO
     */
    public AuditLogDTO save(@Valid AuditLogDTO auditLog) ;

    /**
     * TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.remove
     * @param id TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.remove(id)
     * @return boolean
     */
    public boolean remove(String id) ;

    /**
     * TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.getAll
     * @return List<AuditLogDTO>
     */
    public List<AuditLogDTO> getAll() ;

    /**
     * TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.search
     * @param criteria TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.search(criteria)
     * @return List<AuditLogDTO>
     */
    public List<AuditLogDTO> search(@Valid AuditLogCriteria criteria) ;

    /**
     * TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.getAll
     * @param pageNumber TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.getAll(pageNumber)
     * @param pageSize TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.getAll(pageSize)
     * @return Page<AuditLogDTO>
     */
    public Page<AuditLogDTO> getAll(Integer pageNumber, Integer pageSize) ;

    /**
     * TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.search
     * @param criteria TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.search(criteria)
     * @param pageNumber TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.search(pageNumber)
     * @param pageSize TODO: Model Documentation for bw.co.knowvera.audit.AuditLogService.search(pageSize)
     * @return Page<AuditLogDTO>
     */
    public Page<AuditLogDTO> search(@Valid AuditLogCriteria criteria, Integer pageNumber, Integer pageSize) ;

}