// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { IndividualListDTO } from '@models/bw/co/kyvera/individual/individual-list-dto';
import { IndividualDTO } from '@models/bw/co/kyvera/individual/individual-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';
import { IndividualSearchCriteria } from '@models/bw/co/kyvera/individual/individual-search-criteria';

@Injectable({
  providedIn: 'root'
})
export class IndividualApi {

  protected path = '/individual';

  private http = inject(HttpClient);

  public findById(id: string | any): Observable<IndividualDTO | any> {

    return this.http.get<IndividualDTO | any>(`${this.path}/${id}`);
  }

  public getAll(): Observable<IndividualListDTO[] | any[]> {

    return this.http.get<IndividualListDTO[] | any[]>(`${this.path}`);
  }

  public getAllPaged(pageNumber: number | any, pageSize: number | any): Observable<Page<IndividualListDTO> | any> {

    return this.http.get<Page<IndividualListDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public getOrganisationClients(organisationId: string | any): Observable<IndividualListDTO[] | any[]> {

    return this.http.get<IndividualListDTO[] | any[]>(`${this.path}/organisation/{organisationId}/organisationId/${organisationId}`);
  }

  public getOrganisationClientsPaged(organisationId: string | any, pageNumber: number | any, pageSize: number | any): Observable<Page<IndividualListDTO> | any> {

    return this.http.get<Page<IndividualListDTO> | any>(`${this.path}/organisation/${organisationId}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public pagedSearch(criteria: SearchObject<IndividualSearchCriteria> | any): Observable<Page<IndividualListDTO> | any> {

    return this.http.post<Page<IndividualListDTO> | any>(`${this.path}/search/paged`, criteria);
  }

  public remove(id: string | any): Observable<boolean | any> {

    return this.http.delete<boolean | any>(`${this.path}/${id}`);
  }

  public save(individual: IndividualDTO | any): Observable<IndividualDTO | any> {

    return this.http.post<IndividualDTO | any>(`${this.path}`, individual);
  }

  public search(criteria: SearchObject<IndividualSearchCriteria> | any): Observable<IndividualListDTO[] | any[]> {

    return this.http.post<IndividualListDTO[] | any[]>(`${this.path}/search`, criteria);
  }

  public loadRequestIndividual(requestId: string, identityConfirmationToken: string, identityNo: string): Observable<IndividualDTO> {
    return this.http.get<IndividualDTO>(`${this.path}/request/${requestId}?identityConfirmationToken=${identityConfirmationToken}&identityNo=${identityNo}`);
  }

  public loadMe(): Observable<IndividualDTO> {
    return this.http.get<IndividualDTO>(`${this.path}/me`);
  }
}
