// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { TemplateMappings } from '@models/bw/co/knowvera/settings/template-mappings';
import { SettingsDTO } from '@models/bw/co/knowvera/settings/settings-dto';
import { SettingsFieldGroups } from '@models/bw/co/knowvera/settings/settings-field-groups';
import { OperationalMetrics } from '@models/bw/co/knowvera/settings/operational-metrics';
import { DocumentRequirements } from '@models/bw/co/knowvera/settings/document-requirements';
import { FinancialSettings } from '@models/bw/co/knowvera/settings/financial-settings';
import { PlatformIdentity } from '@models/bw/co/knowvera/settings/platform-identity';
import { SettingsToolSelectors } from '@models/bw/co/knowvera/settings/settings-tool-selectors';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class SettingsApi {
    
    protected path = '/settings';

    private http = inject(HttpClient);

    public attachDocumentType(documentTypeId: string, purpose: DocumentTypePurpose): Observable<SettingsDTO> {

        return this.http.get<SettingsDTO>(`${this.path}/attach-document-type/${documentTypeId}?purpose=${purpose}`);
    }

    public detachDocumentType(documentTypeId: string, purpose: DocumentTypePurpose): Observable<SettingsDTO> {

        return this.http.delete<SettingsDTO>(`${this.path}/detach-document-type/${documentTypeId}?purpose=${purpose}`);
    }

    public findById(id: string): Observable<SettingsDTO> {

        return this.http.get<SettingsDTO>(`${this.path}/${id}`);
    }

    public getAll(): Observable<SettingsDTO[]> {

        return this.http.get<SettingsDTO[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number, pageSize: number): Observable<Page<SettingsDTO>> {

        return this.http.get<Page<SettingsDTO>>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public getDocumentRequirements(): Observable<DocumentRequirements> {

        return this.http.get<DocumentRequirements>(`${this.path}/documents`);
    }

    public getFinancialSettings(): Observable<FinancialSettings> {

        return this.http.get<FinancialSettings>(`${this.path}/financials`);
    }

    public getOperationalMetrics(): Observable<OperationalMetrics> {

        return this.http.get<OperationalMetrics>(`${this.path}/operational-metrics`);
    }

    public getPlatformIdentity(): Observable<PlatformIdentity> {

        return this.http.get<PlatformIdentity>(`${this.path}/platform-identity`);
    }

    public getSettingsFieldGroups(): Observable<SettingsFieldGroups> {

        return this.http.get<SettingsFieldGroups>(`${this.path}/field-groups`);
    }

    public getSettingsToolSelectors(): Observable<SettingsToolSelectors> {

        return this.http.get<SettingsToolSelectors>(`${this.path}/tool-selectors`);
    }

    public getTemplateMappings(): Observable<TemplateMappings> {

        return this.http.get<TemplateMappings>(`${this.path}/template-mappings`);
    }

    public loadSettings(): Observable<SettingsDTO> {

        return this.http.get<SettingsDTO>(`${this.path}/one`);
    }

    public pagedSearch(criteria: string, pageNumber: number, pageSize: number): Observable<Page<SettingsDTO>> {

        return this.http.get<Page<SettingsDTO>>(`${this.path}/search/paged?criteria=${criteria}&pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string): Observable<boolean> {

        return this.http.delete<boolean>(`${this.path}/${id}`);
    }

    public save(setttings: SettingsDTO): Observable<SettingsDTO> {

        return this.http.post<SettingsDTO>(`${this.path}`, setttings);
    }

    public saveDocumentRequirements(documentRequirements: DocumentRequirements): Observable<DocumentRequirements> {

        return this.http.post<DocumentRequirements>(`${this.path}/documents`, documentRequirements);
    }

    public saveFinancialSettings(financialSettings: FinancialSettings): Observable<FinancialSettings> {

        return this.http.post<FinancialSettings>(`${this.path}/financials`, financialSettings);
    }

    public saveOperationalMetrics(operationalMetrics: OperationalMetrics): Observable<OperationalMetrics> {

        return this.http.post<OperationalMetrics>(`${this.path}/operational-metrics`, operationalMetrics);
    }

    public savePlatformIdentity(platformIdentity: PlatformIdentity): Observable<PlatformIdentity> {

        return this.http.post<PlatformIdentity>(`${this.path}/platform-identity`, platformIdentity);
    }

    public saveSettingsFieldGroups(settingsFieldGroups: SettingsFieldGroups): Observable<SettingsFieldGroups> {

        return this.http.post<SettingsFieldGroups>(`${this.path}/field-groups`, settingsFieldGroups);
    }

    public saveSettingsToolSelectors(settingsToolSelectors: SettingsToolSelectors): Observable<SettingsToolSelectors> {

        return this.http.post<SettingsToolSelectors>(`${this.path}/tool-selectors`, settingsToolSelectors);
    }

    public saveTemplateMappings(templateMappings: TemplateMappings): Observable<TemplateMappings> {

        return this.http.post<TemplateMappings>(`${this.path}/template-mappings`, templateMappings);
    }

    public search(criteria: string): Observable<SettingsDTO[]> {

        return this.http.get<SettingsDTO[]>(`${this.path}/search?criteria=${criteria}`);
    }

    public uploadTemplate(template: MultipartFile, target: TargetEntity): Observable<SettingsDTO> {

        return this.http.post<SettingsDTO>(`${this.path}/upload?target=${target}`, {template: template, target: target});
    }

}
