// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.organisation.document;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.SearchObject;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class OrganisationDocumentApiImpl implements OrganisationDocumentApi {

    private final OrganisationDocumentService organisationDocumentService;
    
    public OrganisationDocumentApiImpl(
        OrganisationDocumentService organisationDocumentService    ) {
        
        this.organisationDocumentService = organisationDocumentService;
    }



    @Override
    public ResponseEntity<OrganisationDocumentDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<OrganisationDocumentDTO>> findByOrganisation(String organisationId) throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.findByOrganisation(organisationId));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<OrganisationDocumentDTO>> findByOrganisationPaged(String organisationId, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.findByOrganisation(organisationId, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<OrganisationDocumentDTO>> findByStatus(OrganisationDocumentStatus status) throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.findByStatus(status));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<OrganisationDocumentDTO>> findByStatusPaged(OrganisationDocumentStatus status, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.findByStatus(status, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<OrganisationDocumentDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<OrganisationDocumentDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<OrganisationDocumentDTO>> pagedSearch(SearchObject<OrganisationDocumentSearchCriteria> criteria) throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(organisationDocumentService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<OrganisationDocumentDTO> save(OrganisationDocumentDTO clientRequest) throws Exception {
        try {
            
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(clientRequest, authentication);
            return ResponseEntity.ok(organisationDocumentService.save(clientRequest));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<OrganisationDocumentDTO>> search(SearchObject<OrganisationDocumentSearchCriteria> criteria) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
}