// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { SettingsDTO } from '@models/bw/co/centralkyc/settings/settings-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { TargetEntity } from '@models/bw/co/centralkyc/target-entity';
import { DocumentTypePurpose } from '@app/models/bw/co/centralkyc/settings/document-type-purpose';

@Injectable({
  providedIn: 'root'
})
export class SettingsApi {

  protected path = '/settings';

  private http = inject(HttpClient);

  public findById(id: string | any): Observable<SettingsDTO | any> {

    return this.http.get<SettingsDTO | any>(`${this.path}/${id}`);
  }

  public getAll(): Observable<SettingsDTO[] | any[]> {

    return this.http.get<SettingsDTO[] | any[]>(`${this.path}`);
  }

  public getAllPaged(pageNumber: number | any, pageSize: number | any): Observable<Page<SettingsDTO> | any> {

    return this.http.get<Page<SettingsDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public pagedSearch(criteria: string | any, pageNumber: number | any, pageSize: number | any): Observable<Page<SettingsDTO> | any> {

    return this.http.get<Page<SettingsDTO> | any>(`${this.path}/search/paged?criteria=${criteria}&pageNumber=${pageNumber}&pageSize=${pageSize}`);
  }

  public remove(id: string | any): Observable<boolean | any> {

    return this.http.delete<boolean | any>(`${this.path}/${id}`);
  }

  public save(setttings: SettingsDTO | any): Observable<SettingsDTO | any> {

    return this.http.post<SettingsDTO | any>(`${this.path}`, setttings);
  }

  public search(criteria: string | any): Observable<SettingsDTO[] | any[]> {

    return this.http.get<SettingsDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
  }

  uploadTemplate(template: File, target: TargetEntity): Observable<SettingsDTO> {

    const formData: FormData = new FormData();
    formData.append('template', template);

    return this.http.post<SettingsDTO>(`${this.path}/upload?target=${target}`, formData);
  }

  public attachDocumentType(documentTypeId: string, purpose: DocumentTypePurpose): Observable<SettingsDTO> {

    return this.http.get<SettingsDTO>(`${this.path}/attach-document-type/${documentTypeId}?purpose=${purpose}`);
  }

  public detachDocumentType(documentTypeId: string, purpose: DocumentTypePurpose): Observable<SettingsDTO> {

    return this.http.delete<SettingsDTO>(`${this.path}/detach-document-type/${documentTypeId}?purpose=${purpose}`);
  }
}
