// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, linkedSignal } from '@angular/core';
import { DocumentDetailsComponent } from '@views/document/details/document-details';
import { CommonModule } from '@angular/common';
import { MaterialModule } from '@app/material.module';
import { TranslateModule } from '@ngx-translate/core';
import { Loader } from '@shared/loader/loader';
import { take } from 'rxjs';
import { DocumentDTO } from '@app/models/bw/co/kyvera/document/document-dto';

@Component({
  selector: 'app-document-details',
  templateUrl: './document-details.html',
  styleUrls: ['./document-details.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    Loader,
  ],
})
export class DocumentDetailsImplComponent extends DocumentDetailsComponent {
  override loaderMessage = linkedSignal(() => this.documentApiStore.loaderMessage());
  override messages = linkedSignal(() => this.documentApiStore.messages());
  override success = linkedSignal(() => this.documentApiStore.success());
  override loading = linkedSignal(() => this.documentApiStore.loading());
  override error = linkedSignal(() => this.documentApiStore.error());

  document = linkedSignal<DocumentDTO | any>(() => this.documentApiStore.data());

  constructor() {
    super();
  }

  override ngOnInit(): void {
    this.loadDocumentFromRoute();

    this.route.paramMap.subscribe((params) => {
      const id = params.get('id');
      if (id) {
        this.documentApiStore.findById({ id });
      }
    });

    this.route.queryParamMap.subscribe((params) => {
      const id = params.get('id');
      if (id) {
        this.documentApiStore.findById({ id });
      }
    });
  }

  downloadDocument(): void {
    const item = this.document();

    if (!item?.id) {
      return;
    }

    this.documentApi.downloadFile(item.id).pipe(take(1)).subscribe({
      next: (blob: Blob) => {
        const objectUrl = URL.createObjectURL(blob);
        const anchor = window.document.createElement('a');
        anchor.href = objectUrl;
        anchor.download = item.fileName || `document-${item.id}`;
        anchor.click();
        URL.revokeObjectURL(objectUrl);
      },
    });
  }

  goToEdit(): void {
    const id = this.document()?.id;

    if (!id) {
      return;
    }

    this.router.navigate(['/documents/edit', id]);
  }

  goBackToSearch(): void {
    this.router.navigate(['/documents']);
  }

  doNgOnDestroy(): void {
  }

  private loadDocumentFromRoute(): void {
    const id = this.route.snapshot.paramMap.get('id') || this.route.snapshot.queryParamMap.get('id');

    if (!id) {
      return;
    }

    this.documentApiStore.findById({ id });
  }
}
