// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.knowvera::organisation::document::OrganisationDocumentStatus
 */
export enum OrganisationDocumentStatus {
    /** TODO: Model Documentation for Enumeration Literal ACTIVE value "ACTIVE": $literal.enumerationLiteralDisplay */
    ACTIVE = "ACTIVE",
    /** TODO: Model Documentation for Enumeration Literal INACTIVE value "INACTIVE": $literal.enumerationLiteralDisplay */
    INACTIVE = "INACTIVE"
}
