// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.knowvera.individual.employment;

import bw.co.knowvera.document.DocumentMapper;
import bw.co.knowvera.individual.IndividualMapper;
import bw.co.knowvera.kyc.KycRecordMapper;
import bw.co.knowvera.settings.SalaryRangeMapper;
import bw.co.knowvera.utils.MappingUtils;
import bw.co.knowvera.individual.employment.EmploymentRecord;
import bw.co.knowvera.individual.employment.EmploymentRecordDTO;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.beans.factory.annotation.Autowired;

@Mapper(
    componentModel = "spring",
    uses = {
        DocumentMapper.class,
        IndividualMapper.class,
        SalaryRangeMapper.class,
        MappingUtils.class
    }
)
public abstract class EmploymentRecordMapper {
    
    /**
     * Converts this entity to an object of type {@link EmploymentRecordDTO}.
     * @param entity
     * @return EmploymentRecordDTO
     */
    @Mapping(target = "kycRecords", ignore = true)
    @Mapping(source = "salaryRange", target = "salaryRange")
    public abstract EmploymentRecordDTO toEmploymentRecordDTO(EmploymentRecord entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link EmploymentRecordDTO}.
     * @param entities
     * @return Collection<EmploymentRecordDTO>     */
    public abstract List<EmploymentRecordDTO> toEmploymentRecordDTOCollection(Collection<EmploymentRecord> entities);

    /**
     * Converts an instance of type {@link EmploymentRecordDTO} to this DAO's entity.
     * @param employmentRecordDTO
     * @return EmploymentRecord
     */
    @InheritInverseConfiguration
    @Mapping(target = "kycRecords", ignore = true)
    public abstract EmploymentRecord employmentRecordDTOToEntity(EmploymentRecordDTO employmentRecordDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    @Mapping(target = "kycRecords", ignore = true)
    public abstract void updateEmploymentRecordFromEmploymentRecordDTO(EmploymentRecordDTO employmentRecordDTO, @MappingTarget EmploymentRecord entity);

}