// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.subscription;

import bw.co.centralkyc.invoice.KycInvoiceRepository;
import bw.co.centralkyc.organisation.Organisation;
import bw.co.centralkyc.organisation.OrganisationRepository;
import jakarta.persistence.EntityNotFoundException;

import java.util.Collection;
import java.util.UUID;

import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Repository;

/**
 * @see KycSubscription
 */
@Repository("kycSubscriptionDao")
public class KycSubscriptionDaoImpl
    extends KycSubscriptionDaoBase
{

    public KycSubscriptionDaoImpl(KycInvoiceRepository kycInvoiceRepository,
            OrganisationRepository organisationRepository, KycSubscriptionRepository kycSubscriptionRepository) {
        super(kycInvoiceRepository, organisationRepository, kycSubscriptionRepository);
        //TODO Auto-generated constructor stub
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toKycSubscriptionDTO(
        KycSubscription source,
        KycSubscriptionDTO target)
    {
        // TODO verify behavior of toKycSubscriptionDTO
        super.toKycSubscriptionDTO(source, target);
        // WARNING! No conversion for target.startDate (can't convert source.getStartDate():java.util.Date to java.util.Date
        target.setStartDate(source.getStartDate());
        // WARNING! No conversion for target.endDate (can't convert source.getEndDate():java.util.Date to java.util.Date
        target.setEndDate(source.getEndDate());

        if(source.getOrganisation() != null) {

            target.setOrganisationId(source.getOrganisation().getId().toString());
            target.setOrganisationCode(source.getOrganisation().getCode());
            target.setOrganisationName(source.getOrganisation().getName());
            target.setOrganisationRegistrationNo(source.getOrganisation().getRegistrationNo());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KycSubscriptionDTO toKycSubscriptionDTO(final KycSubscription entity)
    {
        // TODO verify behavior of toKycSubscriptionDTO
        return super.toKycSubscriptionDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private KycSubscription loadKycSubscriptionFromKycSubscriptionDTO(KycSubscriptionDTO kycSubscriptionDTO)
    {
        if (kycSubscriptionDTO.getId() == null)
        {
            return  KycSubscription.Factory.newInstance();
        }
        else
        {
            return this.kycSubscriptionRepository.findById(UUID.fromString(kycSubscriptionDTO.getId()))
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + kycSubscriptionDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public KycSubscription kycSubscriptionDTOToEntity(KycSubscriptionDTO kycSubscriptionDTO)
    {
        // TODO verify behavior of kycSubscriptionDTOToEntity
        KycSubscription entity = this.loadKycSubscriptionFromKycSubscriptionDTO(kycSubscriptionDTO);
        this.kycSubscriptionDTOToEntity(kycSubscriptionDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void kycSubscriptionDTOToEntity(
        KycSubscriptionDTO source,
        KycSubscription target,
        boolean copyIfNull)
    {
        // TODO verify behavior of kycSubscriptionDTOToEntity
        super.kycSubscriptionDTOToEntity(source, target, copyIfNull);
        // No conversion for target.startDate (can't convert source.getStartDate():java.util.Date to java.util.Date
        target.setStartDate(source.getStartDate());
        // No conversion for target.endDate (can't convert source.getEndDate():java.util.Date to java.util.Date
        target.setEndDate(source.getEndDate());

        if(StringUtils.isNotBlank(source.getOrganisationId())) {

            Organisation organisation = this.organisationRepository.getReferenceById(UUID.fromString(source.getOrganisationId()));
            target.setOrganisation(organisation);
        }
    }
}