// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.knowvera::TargetEntity
 */
export enum TargetEntity {
    /** TODO: Model Documentation for Enumeration Literal INDIVIDUAL value "INDIVIDUAL": $literal.enumerationLiteralDisplay */
    INDIVIDUAL = "INDIVIDUAL",
    /** TODO: Model Documentation for Enumeration Literal ORGANISATION value "ORGANISATION": $literal.enumerationLiteralDisplay */
    ORGANISATION = "ORGANISATION",
    /** TODO: Model Documentation for Enumeration Literal BRANCH value "BRANCH": $literal.enumerationLiteralDisplay */
    BRANCH = "BRANCH",
    /** TODO: Model Documentation for Enumeration Literal SUBSCRIPTION value "SUBSCRIPTION": $literal.enumerationLiteralDisplay */
    SUBSCRIPTION = "SUBSCRIPTION",
    /** TODO: Model Documentation for Enumeration Literal INVOICE value "INVOICE": $literal.enumerationLiteralDisplay */
    INVOICE = "INVOICE",
    /** TODO: Model Documentation for Enumeration Literal QUOTATION value "QUOTATION": $literal.enumerationLiteralDisplay */
    QUOTATION = "QUOTATION",
    /** TODO: Model Documentation for Enumeration Literal CLIENT_REQUEST value "CLIENT_REQUEST": $literal.enumerationLiteralDisplay */
    CLIENT_REQUEST = "CLIENT_REQUEST",
    /** TODO: Model Documentation for Enumeration Literal KYC_RECORD value "KYC_RECORD": $literal.enumerationLiteralDisplay */
    KYC_RECORD = "KYC_RECORD",
    /** TODO: Model Documentation for Enumeration Literal CONTACT value "CONTACT": $literal.enumerationLiteralDisplay */
    CONTACT = "CONTACT",
    /** TODO: Model Documentation for Enumeration Literal SETTINGS value "SETTINGS": $literal.enumerationLiteralDisplay */
    SETTINGS = "SETTINGS",
    /** TODO: Model Documentation for Enumeration Literal DOCUMENT value "DOCUMENT": $literal.enumerationLiteralDisplay */
    DOCUMENT = "DOCUMENT"
}
