// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { KycSubscriptionController } from '@controllers/subscription/kyc-subscription-controller';

@Injectable()
export class KycSubscriptionControllerImpl extends KycSubscriptionController {

    constructor() {
        super();
    }

}
