// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { KycRecordController } from '@controllers/kyc/kyc-record-controller';

@Injectable()
export class KycRecordControllerImpl extends KycRecordController {

    constructor() {
        super();
    }

}
