// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.knowvera.document.type.field;

import bw.co.knowvera.document.type.DocumentTypeMapper;
import bw.co.knowvera.utils.MappingUtils;
import bw.co.knowvera.document.type.field.ExpectedField;
import bw.co.knowvera.document.type.field.ExpectedFieldDTO;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.beans.factory.annotation.Autowired;

@Mapper(
    componentModel = "spring",
    uses = {
        DocumentTypeMapper.class,
        MappingUtils.class
    }
)
public abstract class ExpectedFieldMapper {
    
    /**
     * Converts this entity to an object of type {@link ExpectedFieldDTO}.
     * @param entity
     * @return ExpectedFieldDTO
     */
    // WARNING! No conversion for target.documentType (can't convert source.getDocumentType():bw.co.knowvera.document.type.DocumentType to java.lang.String)
    @Mapping(target = "documentType", source = "documentType.name")
    @Mapping(source = "documentType.id", target = "documentTypeId")
    public abstract ExpectedFieldDTO toExpectedFieldDTO(ExpectedField entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link ExpectedFieldDTO}.
     * @param entities
     * @return Collection<ExpectedFieldDTO>     */
    public abstract List<ExpectedFieldDTO> toExpectedFieldDTOCollection(Collection<ExpectedField> entities);

    /**
     * Converts an instance of type {@link ExpectedFieldDTO} to this DAO's entity.
     * @param expectedFieldDTO
     * @return ExpectedField
     */
    @InheritInverseConfiguration
    public abstract ExpectedField expectedFieldDTOToEntity(ExpectedFieldDTO expectedFieldDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    public abstract void updateExpectedFieldFromExpectedFieldDTO(ExpectedFieldDTO expectedFieldDTO, @MappingTarget ExpectedField entity);

}