// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.organisation;

import bw.co.centralkyc.GeneralStatus;
import bw.co.centralkyc.PhoneNumberMapper;
import bw.co.centralkyc.document.DocumentRepository;
import bw.co.centralkyc.document.type.DocumentTypeRepository;
import bw.co.centralkyc.individual.IndividualRepository;
import bw.co.centralkyc.invoice.KycInvoiceRepository;
import bw.co.centralkyc.kyc.KycComplianceStatus;
import bw.co.centralkyc.organisation.branch.BranchRepository;
import bw.co.centralkyc.organisation.client.ClientRequestRepository;
import bw.co.centralkyc.subscription.KycSubscriptionRepository;
import jakarta.persistence.EntityNotFoundException;

import java.util.Collection;
import java.util.UUID;

import org.springframework.stereotype.Repository;

/**
 * @see Organisation
 */
@Repository("organisationDao")
public class OrganisationDaoImpl
    extends OrganisationDaoBase
{

    private final PhoneNumberMapper phoneNumberMapper;
    private final OrganisationDomainMapper organisationDomainMapper;
    
    public OrganisationDaoImpl(DocumentRepository documentRepository, DocumentTypeRepository documentTypeRepository,
            BranchRepository branchRepository, KycSubscriptionRepository kycSubscriptionRepository,
            KycInvoiceRepository kycInvoiceRepository, ClientRequestRepository clientRequestRepository,
            IndividualRepository individualRepository, OrganisationRepository organisationRepository,
            PhoneNumberMapper phoneNumberMapper, OrganisationDomainMapper organisationDomainMapper) {
        super(documentRepository, documentTypeRepository, branchRepository, kycSubscriptionRepository, kycInvoiceRepository,
                clientRequestRepository, individualRepository, organisationRepository);
        //TODO Auto-generated constructor stub

        this.phoneNumberMapper = phoneNumberMapper;
        this.organisationDomainMapper = organisationDomainMapper;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toOrganisationDTO(
        Organisation source,
        OrganisationDTO target)
    {
        // TODO verify behavior of toOrganisationDTO
        super.toOrganisationDTO(source, target);
        // WARNING! No conversion for target.documents (can't convert source.getDocuments():bw.co.centralkyc.document.Document to bw.co.centralkyc.document.DocumentDTO
        // WARNING! No conversion for target.phoneNumbers (can't convert source.getPhoneNumbers():java.util.Map to bw.co.centralkyc.PhoneNumber
        target.setPhoneNumbers(this.phoneNumberMapper.toPhoneNumberCollection(source.getPhoneNumbers()));
        // WARNING! No conversion for target.clientKycDocuments (can't convert source.getClientKycDocuments():bw.co.centralkyc.document.type.DocumentType to bw.co.centralkyc.document.type.DocumentTypeDTO
        // WARNING! No conversion for target.clientRequestsFiles (can't convert source.getClientRequestsFiles():bw.co.centralkyc.document.Document to bw.co.centralkyc.document.DocumentDTO
        // WARNING! No conversion for target.domains (can't convert source.getDomains():java.util.Map to bw.co.centralkyc.organisation.OrganisationDomain
        target.setDomains(this.organisationDomainMapper.toOrganisationDomainCollection(source.getDomains()));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationDTO toOrganisationDTO(final Organisation entity)
    {
        // TODO verify behavior of toOrganisationDTO
        return super.toOrganisationDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Organisation loadOrganisationFromOrganisationDTO(OrganisationDTO organisationDTO)
    {
        if (organisationDTO.getId() == null)
        {
            return  Organisation.Factory.newInstance();
        }
        else
        {
            return this.organisationRepository.findById(UUID.fromString(organisationDTO.getId()))
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + organisationDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public Organisation organisationDTOToEntity(OrganisationDTO organisationDTO)
    {
        // TODO verify behavior of organisationDTOToEntity
        Organisation entity = this.loadOrganisationFromOrganisationDTO(organisationDTO);
        this.organisationDTOToEntity(organisationDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void organisationDTOToEntity(
        OrganisationDTO source,
        Organisation target,
        boolean copyIfNull)
    {
        // TODO verify behavior of organisationDTOToEntity
        super.organisationDTOToEntity(source, target, copyIfNull);
        // No conversion for target.phoneNumbers (can't convert source.getPhoneNumbers():bw.co.centralkyc.PhoneNumber to java.util.Map
        target.setPhoneNumbers(this.phoneNumberMapper.toMapCollection(source.getPhoneNumbers()));
        // No conversion for target.domains (can't convert source.getDomains():bw.co.centralkyc.organisation.OrganisationDomain to java.util.Map
        target.setDomains(this.organisationDomainMapper.toMapCollection(source.getDomains()));
    }
    
    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationListDTO toOrganisationListDTO(final Organisation entity)
    {

        // No conversion for target.id (can't convert entity.getId():java.lang.Long to String)
        String id = entity.getId().toString(); 
        String code = entity.getCode(); 
        String name = entity.getName(); 
        String registrationNo = entity.getRegistrationNo(); 
        GeneralStatus status = entity.getStatus(); 
        String contactEmailAddress = entity.getContactEmailAddress(); 
        KycComplianceStatus kycStatus = entity.getKycStatus(); 
        Boolean isClient = entity.getIsClient(); 
        // No matching property found for target.keycloakId in entity Organisation
        String keycloakId = null;

        return new OrganisationListDTO(
            id, 
            code, 
            name, 
            registrationNo, 
            status, 
            contactEmailAddress, 
            kycStatus, 
            isClient, 
            keycloakId
        );
    }
}