// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.organisation;

import bw.co.centralkyc.document.DocumentMapper;
import bw.co.centralkyc.document.type.DocumentTypeMapper;
import bw.co.centralkyc.invoice.KycInvoiceMapper;
import bw.co.centralkyc.organisation.branch.BranchMapper;
import bw.co.centralkyc.subscription.KycSubscriptionMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        DocumentMapper.class,
        DocumentTypeMapper.class,
        BranchMapper.class,
        KycSubscriptionMapper.class,
        KycInvoiceMapper.class
    }
)
public interface OrganisationMapper {
    
    /**
     * Converts this entity to an object of type {@link OrganisationDTO}.
     * @param entity
     * @return OrganisationDTO
     */
    @Mapping(source = "documents", target = "documents")
    // WARNING! No conversion for target.phoneNumbers (can't convert source.getPhoneNumbers():java.util.Map to bw.co.centralkyc.PhoneNumber
    @Mapping(source = "phoneNumbers", target = "phoneNumbers")
    @Mapping(source = "clientKycDocuments", target = "clientKycDocuments")
    @Mapping(source = "clientRequestsFiles", target = "clientRequestsFiles")
    // WARNING! No conversion for target.domains (can't convert source.getDomains():java.util.Map to bw.co.centralkyc.organisation.OrganisationDomain
    OrganisationDTO toOrganisationDTO(Organisation entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link OrganisationDTO}.
     * @param entities
     * @return Collection<OrganisationDTO>     */
    List<OrganisationDTO> toOrganisationDTOCollection(Collection<Organisation> entities);

    /**
     * Converts an instance of type {@link OrganisationDTO} to this DAO's entity.
     * @param organisationDTO
     * @return Organisation
     */
    // No conversion for target.phoneNumbers (can't convert source.getPhoneNumbers():bw.co.centralkyc.PhoneNumber to java.util.Map
    // No conversion for target.domains (can't convert source.getDomains():bw.co.centralkyc.organisation.OrganisationDomain to java.util.Map
    @InheritInverseConfiguration
    Organisation organisationDTOToEntity(OrganisationDTO organisationDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    // No conversion for target.phoneNumbers (can't convert source.getPhoneNumbers():bw.co.centralkyc.PhoneNumber to java.util.Map
    // No conversion for target.domains (can't convert source.getDomains():bw.co.centralkyc.organisation.OrganisationDomain to java.util.Map
    @InheritInverseConfiguration
    void updateOrganisationFromOrganisationDTO(OrganisationDTO organisationDTO, @MappingTarget Organisation entity);

    /**
     * Converts this entity to an object of type {@link OrganisationListDTO}.
     * @param entity
     * @return OrganisationListDTO
     */
    OrganisationListDTO toOrganisationListDTO(Organisation entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link OrganisationListDTO}.
     * @param entities
     * @return Collection<OrganisationListDTO>     */
    List<OrganisationListDTO> toOrganisationListDTOCollection(Collection<Organisation> entities);

    /**
     * Converts an instance of type {@link OrganisationListDTO} to this DAO's entity.
     * @param organisationListDTO
     * @return Organisation
     */
    @InheritInverseConfiguration
    Organisation organisationListDTOToEntity(OrganisationListDTO organisationListDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    void updateOrganisationFromOrganisationListDTO(OrganisationListDTO organisationListDTO, @MappingTarget Organisation entity);

}