// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycFieldGroupDTO } from '@models/bw/co/kyvera/settings/kyc/kyc-field-group-dto';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class KycFieldGroupApi {
    
    protected path = '/kyc-field-groups';

    private http = inject(HttpClient);

    public findById(id: string): Observable<KycFieldGroupDTO> {

        return this.http.get<KycFieldGroupDTO>(`${this.path}/${id}`);
    }

    public remove(id: string): Observable<boolean> {

        return this.http.delete<boolean>(`${this.path}/${id}`);
    }

    public save(fieldGroup: KycFieldGroupDTO): Observable<KycFieldGroupDTO> {

        return this.http.post<KycFieldGroupDTO>(`${this.path}`, fieldGroup);
    }

    public removeField(id: string, fieldId: string): Observable<KycFieldGroupDTO> {

        return this.http.delete<KycFieldGroupDTO>(`${this.path}/${id}/field/${fieldId}`);
    }
}
