// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.document.type.verification;

import bw.co.centralkyc.document.type.DocumentTypeRepository;
import bw.co.centralkyc.document.type.field.ExpectedFieldRepository;

import org.springframework.stereotype.Repository;

/**
 * @see VerificationDataConfig
 */
@Repository("verificationDataConfigDao")
public class VerificationDataConfigDaoImpl
    extends VerificationDataConfigDaoBase
{

    public VerificationDataConfigDaoImpl(DocumentTypeRepository documentTypeRepository,
            ExpectedFieldRepository expectedFieldRepository,
            VerificationDataConfigRepository verificationDataConfigRepository) {
        super(documentTypeRepository, expectedFieldRepository, verificationDataConfigRepository);
        //TODO Auto-generated constructor stub
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toVerificationDataConfigDTO(
        VerificationDataConfig source,
        VerificationDataConfigDTO target)
    {
        // TODO verify behavior of toVerificationDataConfigDTO
        super.toVerificationDataConfigDTO(source, target);
        // WARNING! No conversion for target.documentType (can't convert source.getDocumentType():bw.co.centralkyc.document.type.DocumentType to java.lang.String
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VerificationDataConfigDTO toVerificationDataConfigDTO(final VerificationDataConfig entity)
    {
        // TODO verify behavior of toVerificationDataConfigDTO
        return super.toVerificationDataConfigDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private VerificationDataConfig loadVerificationDataConfigFromVerificationDataConfigDTO(VerificationDataConfigDTO verificationDataConfigDTO)
    {
        // TODO implement loadVerificationDataConfigFromVerificationDataConfigDTO
        throw new UnsupportedOperationException("bw.co.centralkyc.document.type.verification.loadVerificationDataConfigFromVerificationDataConfigDTO(VerificationDataConfigDTO) not yet implemented.");

        /* A typical implementation looks like this:
        if (verificationDataConfigDTO.getId() == null)
        {
            return  VerificationDataConfig.Factory.newInstance();
        }
        else
        {
            return this.verificationDataConfigRepository.findById(verificationDataConfigDTO.getId())
                .orElseThrow(() -> new VerificationDataConfigServiceException("Entity not found for id: " + verificationDataConfigDTO.getId()));
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public VerificationDataConfig verificationDataConfigDTOToEntity(VerificationDataConfigDTO verificationDataConfigDTO)
    {
        // TODO verify behavior of verificationDataConfigDTOToEntity
        VerificationDataConfig entity = this.loadVerificationDataConfigFromVerificationDataConfigDTO(verificationDataConfigDTO);
        this.verificationDataConfigDTOToEntity(verificationDataConfigDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void verificationDataConfigDTOToEntity(
        VerificationDataConfigDTO source,
        VerificationDataConfig target,
        boolean copyIfNull)
    {
        // TODO verify behavior of verificationDataConfigDTOToEntity
        super.verificationDataConfigDTOToEntity(source, target, copyIfNull);
    }
}