// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditSequenceComponent } from '@views/sequence/edit/edit-sequence';
import { EditSequenceVarsForm } from '@views/sequence/edit/edit-sequence';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { TranslateModule } from '@ngx-translate/core';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { ReactiveFormsModule } from '@angular/forms';
import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';

@Component({
  selector: 'app-edit-sequence',
  templateUrl: './edit-sequence.html',
  styleUrls: ['./edit-sequence.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
    ReactiveFormsModule,
    NgxMatSelectSearchModule,
  ],
})
export class EditSequenceImplComponent extends EditSequenceComponent {

    constructor() {
        super();
    }

    doNgOnDestroy(): void {
    }
}