// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by controller-advice.java.vsl in andromda-spring-cartridge. Do not modify by hand!.
//
package bw.co.knowvera.kyc;

import bw.co.knowvera.ErrorResponse;
import java.time.Instant;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Translates the errors thrown by {@link KycRecordApiServiceBase}
 * into human-readable API responses for the kycRecordApi endpoints.
 *
 * Scoped to {@link KycRecordApi} only, and ordered ahead
 * of global exception handlers so that this advice's friendlier messages take precedence.
 */
@RestControllerAdvice(assignableTypes = KycRecordApi.class)
@Order(Ordered.HIGHEST_PRECEDENCE)
public class KycRecordApiControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(KycRecordApiControllerAdvice.class);

    /**
     * Handles manual argument validation checks thrown by KycRecordApiServiceBase.
     * Maps generated validation messages to friendly human-readable descriptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ErrorResponse> handleIllegalArgument(IllegalArgumentException ex) {
        String message = ex.getMessage() == null ? "" : ex.getMessage();
        String friendly = toFriendlyMessage(message);

        LOGGER.warn("KycRecordApi validation failed: {}", message);

        ErrorResponse errorResponse = new ErrorResponse(
                HttpStatus.BAD_REQUEST.value(),
                HttpStatus.BAD_REQUEST.name(),
                friendly,
                Arrays.asList(ex.getMessage()),
                Instant.now()
        );

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(errorResponse);
    }

    /**
     * Handles {@link KycRecordServiceException} thrown by referenced services.
     */
    @ExceptionHandler(KycRecordServiceException.class)
    public ResponseEntity<ErrorResponse> handleKycRecordServiceException(KycRecordServiceException ex) {
        LOGGER.error("Referenced service error (KycRecordService)", ex);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ErrorResponse(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        HttpStatus.INTERNAL_SERVER_ERROR.name(),
                        "An error occurred while communicating with dependent services. Please try again shortly.",
                        null,
                        Instant.now()
                ));
    }

    /**
     * Maps validation messages thrown by KycRecordApiServiceBase to plain-language equivalents.
     */
    private String toFriendlyMessage(String message) {
        if (message.contains(".findById(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".save(") && message.contains("'kycRecord'")) {
            return "Kyc Record is required.";
        }

        if (message.contains(".remove(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".findByIndividual(") && message.contains("'individualId'")) {
            return "Individual Id is required.";
        }

        if (message.contains(".findByIdentityNo(") && message.contains("'identityNo'")) {
            return "Identity No is required.";
        }

        if (message.contains(".findByOrganisation(") && message.contains("'organisationId'")) {
            return "Organisation Id is required.";
        }

        if (message.contains(".findByIndividualPaged(") && message.contains("'individualId'")) {
            return "Individual Id is required.";
        }

        if (message.contains(".findByIdentityNoPaged(") && message.contains("'identityNo'")) {
            return "Identity No is required.";
        }

        if (message.contains(".findByOrganisationRegistration(") && message.contains("'registrationNo'")) {
            return "Registration No is required.";
        }

        if (message.contains(".findByOrganisationRegistrationPaged(") && message.contains("'registrationNo'")) {
            return "Registration No is required.";
        }

        if (message.contains(".createIndividualRecord(") && message.contains("'individualId'")) {
            return "Individual Id is required.";
        }

        if (message.contains(".createOrganisationRecord(") && message.contains("'organisationId'")) {
            return "Organisation Id is required.";
        }

        if (message.contains(".findMyCurrentRecord(") && message.contains("'ownerType'")) {
            return "Owner Type is required.";
        }

        if (message.contains(".createNew(") && message.contains("'record'")) {
            return "Record is required.";
        }

        if (message.contains(".updateRecordFiles(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".updateRecordFiles(") && message.contains("'documents'")) {
            return "Documents is required.";
        }

        if (message.contains(".updateRecordFiles(") && message.contains("'files'")) {
            return "Files is required.";
        }

        if (message.contains(".removeRecordFile(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".removeRecordFile(") && message.contains("'documentId'")) {
            return "Document Id is required.";
        }

        if (message.contains(".findSummaryById(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".runVerification(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".generateKycReport(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".updateStatus(") && message.contains("'id'")) {
            return "Id is required.";
        }

        if (message.contains(".updateStatus(") && message.contains("'kycStatus'")) {
            return "Kyc Status is required.";
        }


        // Fallback for any unmapped validation message
        return message;
    }
}