// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by controller-advice.java.vsl in andromda-spring-cartridge. Do not modify by hand!.
//
package bw.co.knowvera.kyc;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.context.request.WebRequest;

import bw.co.knowvera.ValidationMapping;

import java.net.URI;
import java.time.Instant;
import java.util.List;

/**
 * Translates the errors thrown by {@link KycRecordApiServiceBase}
 * into human-readable API responses for the kycRecordApi endpoints.
 *
 * Scoped to {@link KycRecordApi} only, and ordered ahead
 * of global exception handlers so that this advice's friendlier messages take precedence.
 */
@RestControllerAdvice(assignableTypes = KycRecordApi.class)
@Order(Ordered.HIGHEST_PRECEDENCE)
public class KycRecordApiControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(KycRecordApiControllerAdvice.class);

    /**
     * Ordered list of validation-message mappings.
     * Each entry matches a method-name substring and (optionally) a
     * field-name substring against the raw exception message, and
     * supplies the user-facing replacement text.
     */
    private static final List<ValidationMapping> VALIDATION_MAPPINGS = List.of(

            new ValidationMapping(".findById(", "'id'",
                    "Id is required."),

            new ValidationMapping(".save(", "'kycRecord'",
                    "Kyc Record is required."),

            new ValidationMapping(".remove(", "'id'",
                    "Id is required."),

            new ValidationMapping(".findByIndividual(", "'individualId'",
                    "Individual Id is required."),

            new ValidationMapping(".findByIdentityNo(", "'identityNo'",
                    "Identity No is required."),

            new ValidationMapping(".findByOrganisation(", "'organisationId'",
                    "Organisation Id is required."),

            new ValidationMapping(".findByIndividualPaged(", "'individualId'",
                    "Individual Id is required."),

            new ValidationMapping(".findByIdentityNoPaged(", "'identityNo'",
                    "Identity No is required."),

            new ValidationMapping(".findByOrganisationRegistration(", "'registrationNo'",
                    "Registration No is required."),

            new ValidationMapping(".findByOrganisationRegistrationPaged(", "'registrationNo'",
                    "Registration No is required."),

            new ValidationMapping(".createIndividualRecord(", "'individualId'",
                    "Individual Id is required."),

            new ValidationMapping(".createOrganisationRecord(", "'organisationId'",
                    "Organisation Id is required."),

            new ValidationMapping(".findMyCurrentRecord(", "'ownerType'",
                    "Owner Type is required."),

            new ValidationMapping(".createNew(", "'record'",
                    "Record is required."),

            new ValidationMapping(".updateRecordFiles(", "'id'",
                    "Id is required."),
            new ValidationMapping(".updateRecordFiles(", "'documents'",
                    "Documents is required."),
            new ValidationMapping(".updateRecordFiles(", "'files'",
                    "Files is required."),

            new ValidationMapping(".removeRecordFile(", "'id'",
                    "Id is required."),
            new ValidationMapping(".removeRecordFile(", "'documentId'",
                    "Document Id is required."),

            new ValidationMapping(".findSummaryById(", "'id'",
                    "Id is required."),

            new ValidationMapping(".runVerification(", "'id'",
                    "Id is required."),

            new ValidationMapping(".generateKycReport(", "'id'",
                    "Id is required."),

            new ValidationMapping(".updateStatus(", "'id'",
                    "Id is required."),
            new ValidationMapping(".updateStatus(", "'kycStatus'",
                    "Kyc Status is required.")
    );

    /**
     * Handles manual argument validation checks thrown by KycRecordApiServiceBase.
     * Maps generated validation messages to friendly human-readable descriptions.
     */
    @ExceptionHandler(IllegalArgumentException.class)
    public ResponseEntity<ProblemDetail> handleIllegalArgument(
            IllegalArgumentException ex,
            WebRequest request) {

        String message = ex.getMessage() == null ? "" : ex.getMessage();
        String friendly = toFriendlyMessage(message);

        List<String> errors = message.isBlank()
                ? List.of()
                : List.of(message);

        LOGGER.warn("KycRecordApi validation failed: {}", message);

        ProblemDetail problemDetail = buildProblemDetail(
                HttpStatus.BAD_REQUEST,
                "service-validation-error",
                "KycRecordApi validation failed",
                friendly,
                request,
                errors
        );

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(problemDetail);
    }

    /**
     * Handles {@link KycRecordServiceException} thrown by referenced services.
     */
    @ExceptionHandler(KycRecordServiceException.class)
    public ResponseEntity<ProblemDetail> handleKycRecordServiceException(
            KycRecordServiceException ex,
            WebRequest request) {

        LOGGER.error("Referenced service error (KycRecordService)", ex);

        ProblemDetail problemDetail = buildProblemDetail(
                HttpStatus.INTERNAL_SERVER_ERROR,
                "service-error",
                "KycRecordApi service error",
                "An error occurred while communicating with dependent services. Please try again shortly.",
                request,
                List.of()
        );

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(problemDetail);
    }

    /**
     * Builds an RFC 9457 {@link ProblemDetail} response body, with
     * {@code timestamp} and {@code errors} as extension members.
     */
    private ProblemDetail buildProblemDetail(
            HttpStatus status,
            String type,
            String title,
            String detail,
            WebRequest request,
            List<String> errors) {

        ProblemDetail problemDetail = ProblemDetail.forStatusAndDetail(status, detail);
        problemDetail.setType(URI.create(type));
        problemDetail.setTitle(title);
        problemDetail.setInstance(URI.create(getInstanceUri(request)));
        problemDetail.setProperty("timestamp", Instant.now());
        problemDetail.setProperty("errors", errors);

        return problemDetail;
    }

    /**
     * Extracts the request URI from the Spring WebRequest.
     */
    private String getInstanceUri(WebRequest request) {
        return request.getDescription(false)
                .replace("uri=", "");
    }

    /**
     * Maps validation messages thrown by KycRecordApiServiceBase to
     * plain-language equivalents, using {@link #VALIDATION_MAPPINGS}.
     *
     * <p>
     * The fallback returns the raw exception message rather than a
     * generic sentence — preserved from the original generated behavior.
     * </p>
     */
    private String toFriendlyMessage(String message) {

        return VALIDATION_MAPPINGS.stream()
                .filter(mapping -> mapping.matches(message))
                .map(ValidationMapping::friendlyMessage)
                .findFirst()
                .orElse(message);
    }
}