// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.document.type.field;

import bw.co.centralkyc.document.type.DocumentTypeRepository;
import org.springframework.stereotype.Repository;

/**
 * @see ExpectedField
 */
@Repository("expectedFieldDao")
public class ExpectedFieldDaoImpl
    extends ExpectedFieldDaoBase
{
    
    public ExpectedFieldDaoImpl(
        DocumentTypeRepository documentTypeRepository,
        ExpectedFieldRepository expectedFieldRepository
    ) {

        super(
            documentTypeRepository,
            expectedFieldRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toExpectedFieldDTO(
        ExpectedField source,
        ExpectedFieldDTO target)
    {
        // TODO verify behavior of toExpectedFieldDTO
        super.toExpectedFieldDTO(source, target);
        // WARNING! No conversion for target.documentType (can't convert source.getDocumentType():bw.co.centralkyc.document.type.DocumentType to java.lang.String
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExpectedFieldDTO toExpectedFieldDTO(final ExpectedField entity)
    {
        // TODO verify behavior of toExpectedFieldDTO
        return super.toExpectedFieldDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private ExpectedField loadExpectedFieldFromExpectedFieldDTO(ExpectedFieldDTO expectedFieldDTO)
    {
        // TODO implement loadExpectedFieldFromExpectedFieldDTO
        throw new UnsupportedOperationException("bw.co.centralkyc.document.type.field.loadExpectedFieldFromExpectedFieldDTO(ExpectedFieldDTO) not yet implemented.");

        /* A typical implementation looks like this:
        if (expectedFieldDTO.getId() == null)
        {
            return  ExpectedField.Factory.newInstance();
        }
        else
        {
            return this.expectedFieldRepository.findById(expectedFieldDTO.getId())
                .orElseThrow(() -> new ExpectedFieldServiceException("Entity not found for id: " + expectedFieldDTO.getId()));
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public ExpectedField expectedFieldDTOToEntity(ExpectedFieldDTO expectedFieldDTO)
    {
        // TODO verify behavior of expectedFieldDTOToEntity
        ExpectedField entity = this.loadExpectedFieldFromExpectedFieldDTO(expectedFieldDTO);
        this.expectedFieldDTOToEntity(expectedFieldDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void expectedFieldDTOToEntity(
        ExpectedFieldDTO source,
        ExpectedField target,
        boolean copyIfNull)
    {
        // TODO verify behavior of expectedFieldDTOToEntity
        super.expectedFieldDTOToEntity(source, target, copyIfNull);
    }
}